/// MEGA Dream Symbols Database Part 7 - Relationships & Social
/// Iliskiler, Sosyal Durumlar, Aile, Arkadaslik
library;

import '../models/dream_interpretation_models.dart';

/// Part 7: Iliskiler ve Sosyal Semboller - 80+ Sembol
class MegaDreamSymbolsPart7 {
  static const List<DreamSymbolData> symbols = [
    // ════════════════════════════════════════════════════════════════════════
    // AILE ILISKILERI - 25+ Sembol
    // ════════════════════════════════════════════════════════════════════════
    DreamSymbolData(
      symbol: 'grandmother',
      symbolTr: 'Buyukanne',
      emoji: '👵',
      category: SymbolCategory.insan,
      universalMeanings: [
        'Bilgelik ve deneyim',
        'Kosulsuz sevgi',
        'Atalarin sesi',
        'Koruyucu enerji',
        'Gecmisin mirasi',
        'Sifa ve bakim',
      ],
      emotionVariants: {
        EmotionalTone.huzur: 'Guvenli kollarda, sefkat',
        EmotionalTone.ozlem: 'Kaybedilen sevgiye hasret',
        EmotionalTone.merak: 'Atalardan mesaj',
        EmotionalTone.korku: 'Yaslanma, olum korkusu',
      },
      archetypes: ['Bilge Kadin', 'Buyuk Anne', 'Ata'],
      relatedSymbols: ['mother', 'ancestor', 'wisdom', 'home'],
      shadowAspect: 'Gecmise takilmak, eski kaliplar',
      lightAspect: 'Bilgelik, sefkat, rehberlik',
    ),

    DreamSymbolData(
      symbol: 'grandfather',
      symbolTr: 'Buyukbaba',
      emoji: '👴',
      category: SymbolCategory.insan,
      universalMeanings: [
        'Otorite ve bilgelik',
        'Aile mirasi',
        'Koruyucu guc',
        'Yasam dersleri',
        'Gelenek ve degerler',
        'Erkek ata enerjisi',
      ],
      emotionVariants: {
        EmotionalTone.huzur: 'Guclu koruma hissi',
        EmotionalTone.ozlem: 'Kayip rehbere hasret',
        EmotionalTone.merak: 'Hikaye ve ders',
        EmotionalTone.korku: 'Otorite korkusu',
      },
      archetypes: ['Bilge Yasli', 'Kral', 'Ata'],
      relatedSymbols: ['father', 'ancestor', 'authority', 'tradition'],
      shadowAspect: 'Katı kurallar, eski dusunce',
      lightAspect: 'Rehberlik, koruma, miras',
    ),

    DreamSymbolData(
      symbol: 'sibling',
      symbolTr: 'Kardes',
      emoji: '👫',
      category: SymbolCategory.insan,
      universalMeanings: [
        'Ic cocuk yansimasi',
        'Rekabet ve isbirligi',
        'Paylasilmis gecmis',
        'Benlik parcasi',
        'Aile dinamikleri',
        'Sadakat ve catisma',
      ],
      emotionVariants: {
        EmotionalTone.huzur: 'Birlik ve destek',
        EmotionalTone.korku: 'Rekabet, kiskanclık',
        EmotionalTone.ozlem: 'Uzaklasan yakinlik',
        EmotionalTone.heyecan: 'Paylasilmis macera',
      },
      archetypes: ['Ikiz', 'Golge', 'Ortak'],
      relatedSymbols: ['family', 'child', 'competition', 'bond'],
      shadowAspect: 'Kiskanclık, karsilastirma',
      lightAspect: 'Destek, paylasim, anlayis',
    ),

    DreamSymbolData(
      symbol: 'aunt',
      symbolTr: 'Teyze/Hala',
      emoji: '👩',
      category: SymbolCategory.insan,
      universalMeanings: [
        'Alternatif anne figuru',
        'Farkli bakis acisi',
        'Aile sirlari',
        'Destek sistemi',
        'Kadinlik modeli',
        'Ozel bag',
      ],
      emotionVariants: {
        EmotionalTone.huzur: 'Anlayisli yakinlik',
        EmotionalTone.merak: 'Aile hikayeleri',
        EmotionalTone.ozlem: 'Kayip baglanti',
        EmotionalTone.heyecan: 'Surpriz ve hediyeler',
      },
      archetypes: ['Yardimci', 'Rehber', 'Sirdar'],
      relatedSymbols: ['mother', 'family', 'secret', 'support'],
      shadowAspect: 'Dedikodu, mudahaleci',
      lightAspect: 'Destek, ozel ilgi, bilgelik',
    ),

    DreamSymbolData(
      symbol: 'uncle',
      symbolTr: 'Dayi/Amca',
      emoji: '👨',
      category: SymbolCategory.insan,
      universalMeanings: [
        'Alternatif baba figuru',
        'Macera ve eglence',
        'Erkeklik modeli',
        'Koruyucu dayanak',
        'Aile baglari',
        'Mentor enerjisi',
      ],
      emotionVariants: {
        EmotionalTone.huzur: 'Guvenilir yakinlik',
        EmotionalTone.heyecan: 'Macera ortagi',
        EmotionalTone.ozlem: 'Kayip rol model',
        EmotionalTone.korku: 'Otorite, uzaklik',
      },
      archetypes: ['Mentor', 'Koruyucu', 'Maceract'],
      relatedSymbols: ['father', 'family', 'adventure', 'guidance'],
      shadowAspect: 'Uzak, erislemez',
      lightAspect: 'Rehberlik, koruma, eglence',
    ),

    DreamSymbolData(
      symbol: 'cousin',
      symbolTr: 'Kuzen',
      emoji: '🧑',
      category: SymbolCategory.insan,
      universalMeanings: [
        'Genetik baglanti',
        'Cocukluk anilari',
        'Paralel yasam',
        'Aile genislemesi',
        'Karsilastirma noktasi',
        'Sosyal cevrenin parcasi',
      ],
      emotionVariants: {
        EmotionalTone.heyecan: 'Bulusma sevinci',
        EmotionalTone.ozlem: 'Uzak akrabalar',
        EmotionalTone.merak: 'Hayat karsilastirmasi',
        EmotionalTone.korku: 'Rekabet, karsilastirma',
      },
      archetypes: ['Yansima', 'Paralel', 'Bag'],
      relatedSymbols: ['sibling', 'family', 'childhood', 'reunion'],
      shadowAspect: 'Karsilastirma, kiskanclık',
      lightAspect: 'Kok baglantisi, paylasim',
    ),

    DreamSymbolData(
      symbol: 'in_laws',
      symbolTr: 'Kayinlar',
      emoji: '👨‍👩‍👧',
      category: SymbolCategory.insan,
      universalMeanings: [
        'Yeni aile dinamikleri',
        'Kabul ve entegrasyon',
        'Farkli degerler',
        'Evlilik zorlugu',
        'Sinir belirleme',
        'Aidiyet arayisi',
      ],
      emotionVariants: {
        EmotionalTone.korku: 'Kabul edilmeme korkusu',
        EmotionalTone.huzur: 'Harmonik iliski',
        EmotionalTone.sucluluk: 'Beklentileri karsilayamama',
        EmotionalTone.heyecan: 'Yeni aile baglari',
      },
      archetypes: ['Sinav', 'Entegrasyon', 'Sinir'],
      relatedSymbols: ['marriage', 'family', 'boundary', 'acceptance'],
      shadowAspect: 'Catisma, mudahale',
      lightAspect: 'Kabul, genisleyen sevgi',
    ),

    DreamSymbolData(
      symbol: 'stepparent',
      symbolTr: 'Uvey Ebeveyn',
      emoji: '👤',
      category: SymbolCategory.insan,
      universalMeanings: [
        'Degisen aile yapisi',
        'Yeni otorite',
        'Adaptasyon sureci',
        'Cift ebeveynlik',
        'Sadakat catismasi',
        'Kabul ve red',
      ],
      emotionVariants: {
        EmotionalTone.korku: 'Yerini alma korkusu',
        EmotionalTone.huzur: 'Yeni baglanti',
        EmotionalTone.ofke: 'Istenmeyen degisim',
        EmotionalTone.merak: 'Yeni iliskiyi tanimlama',
      },
      archetypes: ['Yaratici', 'Yabanci', 'Kopru'],
      relatedSymbols: ['parent', 'change', 'family', 'adaptation'],
      shadowAspect: 'Catisma, sadakat bolinmesi',
      lightAspect: 'Genisleyen sevgi kapasitesi',
    ),

    DreamSymbolData(
      symbol: 'twin',
      symbolTr: 'Ikiz',
      emoji: '👯',
      category: SymbolCategory.insan,
      universalMeanings: [
        'Ruhun ikili dogasi',
        'Tam yansima',
        'Tamamlayici parca',
        'Kimlik sorgusu',
        'Derin baglanti',
        'Aynilik ve farklilik',
      ],
      emotionVariants: {
        EmotionalTone.huzur: 'Tam anlasılma',
        EmotionalTone.korku: 'Kimlik kaybetme',
        EmotionalTone.merak: 'Diger ben kim?',
        EmotionalTone.ozlem: 'Kayip parca',
      },
      archetypes: ['Golge', 'Ayna', 'Ikili'],
      relatedSymbols: ['mirror', 'self', 'sibling', 'duality'],
      shadowAspect: 'Kimlik karmasasi, karsilastirma',
      lightAspect: 'Butunluk, derin bag',
    ),

    DreamSymbolData(
      symbol: 'orphan',
      symbolTr: 'Yetim',
      emoji: '😢',
      category: SymbolCategory.insan,
      universalMeanings: [
        'Terk edilme korkusu',
        'Ic cocugun yarasi',
        'Bagimsizlik zorunlulugu',
        'Aidiyet arayisi',
        'Kayip koruma',
        'Kendine yeterlilik',
      ],
      emotionVariants: {
        EmotionalTone.korku: 'Terk edilme, yalnizlik',
        EmotionalTone.ozlem: 'Ebeveyn hasreti',
        EmotionalTone.heyecan: 'Bagimsizlik gucu',
        EmotionalTone.sucluluk: 'Sevilmeme hissi',
      },
      archetypes: ['Yetim', 'Kahraman', 'Arayisci'],
      relatedSymbols: ['child', 'abandonment', 'home', 'belonging'],
      shadowAspect: 'Terk edilme yarasi, guvenszlik',
      lightAspect: 'Ic guc, dayaniklilik',
    ),

    // ════════════════════════════════════════════════════════════════════════
    // ROMANTIK ILISKILER - 20+ Sembol
    // ════════════════════════════════════════════════════════════════════════
    DreamSymbolData(
      symbol: 'lover',
      symbolTr: 'Sevgili',
      emoji: '💑',
      category: SymbolCategory.insan,
      universalMeanings: [
        'Romantik arzu',
        'Anima/Animus',
        'Tutku ve baglanma',
        'Iliski dinamikleri',
        'Ic erkek/kadin',
        'Ask potansiyeli',
      ],
      emotionVariants: {
        EmotionalTone.heyecan: 'Tutku ve cekimlik',
        EmotionalTone.korku: 'Kaybetme korkusu',
        EmotionalTone.ozlem: 'Uzaklık acisi',
        EmotionalTone.huzur: 'Derin baglanti',
      },
      archetypes: ['Asik', 'Anima/Animus', 'Tutku'],
      relatedSymbols: ['kiss', 'heart', 'bed', 'wedding'],
      shadowAspect: 'Bagimlilik, obsesyon',
      lightAspect: 'Gercek ask, butunluk',
    ),

    DreamSymbolData(
      symbol: 'kiss',
      symbolTr: 'Opucuk',
      emoji: '💋',
      category: SymbolCategory.eylem,
      universalMeanings: [
        'Yakinlik ve sevgi',
        'Baglanti kurma',
        'Kabul ve onay',
        'Ruh alisverisi',
        'Romantik birlesme',
        'Guclu baglanti',
      ],
      emotionVariants: {
        EmotionalTone.heyecan: 'Tutkulu bulusma',
        EmotionalTone.huzur: 'Sefkatli kabul',
        EmotionalTone.korku: 'Istenmeyen yakinlik',
        EmotionalTone.ozlem: 'Hasret giderme',
      },
      archetypes: ['Birlesme', 'Kabul', 'Ask'],
      relatedSymbols: ['lover', 'lips', 'heart', 'romance'],
      shadowAspect: 'Aldatma, sahte yakinlik',
      lightAspect: 'Gercek sevgi, ruhsal bag',
    ),

    DreamSymbolData(
      symbol: 'embrace',
      symbolTr: 'Kucaklasma',
      emoji: '🤗',
      category: SymbolCategory.eylem,
      universalMeanings: [
        'Koruma ve guvenlik',
        'Kabul etme',
        'Duygusal destek',
        'Yakinlik ihtiyaci',
        'Birlesme arzusu',
        'Sifali dokunma',
      ],
      emotionVariants: {
        EmotionalTone.huzur: 'Guvende hissetme',
        EmotionalTone.ozlem: 'Fiziksel temas hasreti',
        EmotionalTone.korku: 'Bogulma, sinir ihlali',
        EmotionalTone.heyecan: 'Bulusma sevinci',
      },
      archetypes: ['Anne', 'Koruyucu', 'Birlik'],
      relatedSymbols: ['arms', 'warmth', 'comfort', 'safety'],
      shadowAspect: 'Bagimlilik, yapismak',
      lightAspect: 'Kosulsuz kabul, sifa',
    ),

    DreamSymbolData(
      symbol: 'proposal',
      symbolTr: 'Evlenme Teklifi',
      emoji: '💍',
      category: SymbolCategory.eylem,
      universalMeanings: [
        'Taahhut karari',
        'Yasam degisimi',
        'Secim ani',
        'Birlesme teklifi',
        'Gelecek planlama',
        'Kabul veya red',
      ],
      emotionVariants: {
        EmotionalTone.heyecan: 'Yeni baslangiç heyecani',
        EmotionalTone.korku: 'Taahhut korkusu',
        EmotionalTone.merak: 'Karar sureci',
        EmotionalTone.huzur: 'Dogru insan bulma',
      },
      archetypes: ['Gecis', 'Taahhut', 'Birlesme'],
      relatedSymbols: ['ring', 'wedding', 'love', 'commitment'],
      shadowAspect: 'Baski, erken karar',
      lightAspect: 'Bilinçli secim, olgun ask',
    ),

    DreamSymbolData(
      symbol: 'divorce',
      symbolTr: 'Bosanma',
      emoji: '💔',
      category: SymbolCategory.soyut,
      universalMeanings: [
        'Ayrilik ve son',
        'Kimlik yeniden tanimlama',
        'Ozgurluk ve kayip',
        'Iliski bitmesi',
        'Yeni baslangic',
        'Acinın islenmesi',
      ],
      emotionVariants: {
        EmotionalTone.korku: 'Yalnizlik korkusu',
        EmotionalTone.sucluluk: 'Basarisizlik hissi',
        EmotionalTone.heyecan: 'Yeni ozgurluk',
        EmotionalTone.ozlem: 'Gecmise ozlem',
      },
      archetypes: ['Olum', 'Yeniden Dogus', 'Ayrilik'],
      relatedSymbols: ['marriage', 'separation', 'freedom', 'ending'],
      shadowAspect: 'Aci, terk edilme',
      lightAspect: 'Yeni baslangiç, ozgurluk',
    ),

    DreamSymbolData(
      symbol: 'affair',
      symbolTr: 'Aldatma/Iliski',
      emoji: '🤫',
      category: SymbolCategory.soyut,
      universalMeanings: [
        'Gizli arzular',
        'Ihmal edilen ihtiyaclar',
        'Guven sorunu',
        'Bastırılmis tutku',
        'Cift hayat',
        'Risk ve heyecan',
      ],
      emotionVariants: {
        EmotionalTone.korku: 'Yakalanma, kayip',
        EmotionalTone.sucluluk: 'Ihanet bilinci',
        EmotionalTone.heyecan: 'Yasak meyve',
        EmotionalTone.merak: 'Baska olasiliklar',
      },
      archetypes: ['Golge', 'Gizli', 'Yasak'],
      relatedSymbols: ['secret', 'betrayal', 'passion', 'guilt'],
      shadowAspect: 'Ihanet, guven kirma',
      lightAspect: 'Ihtiyaclari fark etme, dogruluk',
    ),

    DreamSymbolData(
      symbol: 'jealousy',
      symbolTr: 'Kiskanclik',
      emoji: '😒',
      category: SymbolCategory.soyut,
      universalMeanings: [
        'Guvenszlik',
        'Kayip korkusu',
        'Deger hissi eksikligi',
        'Sahiplenme',
        'Karsilastirma',
        'Korku maskesi',
      ],
      emotionVariants: {
        EmotionalTone.korku: 'Kaybetme panik',
        EmotionalTone.ofke: 'Haksizlik hissi',
        EmotionalTone.sucluluk: 'Sahip olmama',
        EmotionalTone.donukluk: 'Tukenmislik',
      },
      archetypes: ['Golge', 'Korku', 'Ego'],
      relatedSymbols: ['love', 'fear', 'comparison', 'insecurity'],
      shadowAspect: 'Kontrol, sahiplenme',
      lightAspect: 'Oz deger farkindigi',
    ),

    DreamSymbolData(
      symbol: 'flirt',
      symbolTr: 'Flort',
      emoji: '😏',
      category: SymbolCategory.eylem,
      universalMeanings: [
        'Cekicilik oyunu',
        'Potansiyel kesfetme',
        'Hafif baglanti',
        'Ozguven gosterisi',
        'Sosyal dans',
        'Romantik olasilik',
      ],
      emotionVariants: {
        EmotionalTone.heyecan: 'Yeni olasililar',
        EmotionalTone.korku: 'Red edilme',
        EmotionalTone.merak: 'Bu nereye gider?',
        EmotionalTone.huzur: 'Oyunsu keyfı',
      },
      archetypes: ['Oyuncu', 'Cekici', 'Arayisci'],
      relatedSymbols: ['attraction', 'smile', 'dance', 'romance'],
      shadowAspect: 'Yuzeysellik, oyun',
      lightAspect: 'Cekicilik, kesfetme',
    ),

    DreamSymbolData(
      symbol: 'breakup',
      symbolTr: 'Ayrilik',
      emoji: '💔',
      category: SymbolCategory.soyut,
      universalMeanings: [
        'Iliski sonu',
        'Aci ve yas',
        'Yeni baslangic',
        'Kimlik yenilenmesi',
        'Kayip isleme',
        'Ozgurluk ve yalnizlik',
      ],
      emotionVariants: {
        EmotionalTone.korku: 'Yalniz kalma',
        EmotionalTone.sucluluk: 'Yapamadim hissi',
        EmotionalTone.ozlem: 'Gecmise ozlem',
        EmotionalTone.heyecan: 'Yeni sayfa',
      },
      archetypes: ['Olum', 'Son', 'Baslangic'],
      relatedSymbols: ['ending', 'tears', 'freedom', 'change'],
      shadowAspect: 'Terk edilme, basarisizlik',
      lightAspect: 'Buyume, yeni olasiliklar',
    ),

    DreamSymbolData(
      symbol: 'first_love',
      symbolTr: 'Ilk Ask',
      emoji: '💕',
      category: SymbolCategory.insan,
      universalMeanings: [
        'Masumiyet ve saflik',
        'Ilk romantik uyanis',
        'Nostalji',
        'Tamamlanmamis hikaye',
        'Ideal ask imgesi',
        'Genclik enerjisi',
      ],
      emotionVariants: {
        EmotionalTone.ozlem: 'Gecmise hasret',
        EmotionalTone.huzur: 'Tatli ani',
        EmotionalTone.merak: 'Simdi nerede?',
        EmotionalTone.sucluluk: 'Kapanmamis defter',
      },
      archetypes: ['Masumiyet', 'Baslangic', 'Ideal'],
      relatedSymbols: ['youth', 'innocence', 'memory', 'nostalgia'],
      shadowAspect: 'Gecmise takılma',
      lightAspect: 'Ilk uyanis, saflik',
    ),

    // ════════════════════════════════════════════════════════════════════════
    // SOSYAL ILISKILER - 20+ Sembol
    // ════════════════════════════════════════════════════════════════════════
    DreamSymbolData(
      symbol: 'best_friend',
      symbolTr: 'En Yakin Arkadas',
      emoji: '👯‍♂️',
      category: SymbolCategory.insan,
      universalMeanings: [
        'Ruh esi dostluk',
        'Kosulsuz kabul',
        'Aynalanma',
        'Destek sistemi',
        'Secilmis aile',
        'Derin guven',
      ],
      emotionVariants: {
        EmotionalTone.huzur: 'Tam anlasilma',
        EmotionalTone.ozlem: 'Uzak dostluk',
        EmotionalTone.heyecan: 'Paylasim sevinci',
        EmotionalTone.korku: 'Arkadasi kaybetme',
      },
      archetypes: ['Sadik', 'Ayna', 'Destek'],
      relatedSymbols: ['trust', 'loyalty', 'support', 'mirror'],
      shadowAspect: 'Bagimlilik, hayal kirikligi',
      lightAspect: 'Gercek dostluk, sadakat',
    ),

    DreamSymbolData(
      symbol: 'enemy',
      symbolTr: 'Dusman',
      emoji: '😠',
      category: SymbolCategory.insan,
      universalMeanings: [
        'Golge yansimasi',
        'Ic catisma',
        'Reddedilen benlik',
        'Dis tehdit',
        'Mucadele',
        'Projeksyon',
      ],
      emotionVariants: {
        EmotionalTone.korku: 'Tehdit altinda',
        EmotionalTone.ofke: 'Saldirganlik',
        EmotionalTone.merak: 'Neden dusman?',
        EmotionalTone.donukluk: 'Yorgunluk, teslim',
      },
      archetypes: ['Golge', 'Antagonist', 'Ayna'],
      relatedSymbols: ['shadow', 'fight', 'fear', 'projection'],
      shadowAspect: 'Nefret, intikam',
      lightAspect: 'Golge entegrasyonu, baris',
    ),

    DreamSymbolData(
      symbol: 'boss',
      symbolTr: 'Patron',
      emoji: '👔',
      category: SymbolCategory.insan,
      universalMeanings: [
        'Otorite figuru',
        'Guc dinamikleri',
        'Degerlendirme',
        'Baba projeksiyonu',
        'Kariyer stresi',
        'Kontrol sorunu',
      ],
      emotionVariants: {
        EmotionalTone.korku: 'Yetersizlik, kovulma',
        EmotionalTone.huzur: 'Onay ve basari',
        EmotionalTone.ofke: 'Adaletsizlik',
        EmotionalTone.merak: 'Terfi, firsatlar',
      },
      archetypes: ['Kral', 'Otorite', 'Yargic'],
      relatedSymbols: ['work', 'authority', 'father', 'judgment'],
      shadowAspect: 'Baskı, korku',
      lightAspect: 'Rehberlik, firsatlar',
    ),

    DreamSymbolData(
      symbol: 'colleague',
      symbolTr: 'Is Arkadasi',
      emoji: '🧑‍💼',
      category: SymbolCategory.insan,
      universalMeanings: [
        'Profesyonel iliski',
        'Rekabet ve isbirligi',
        'Sosyal maske',
        'Kariyer yansimasi',
        'Takim dinamigi',
        'Sinirlar',
      ],
      emotionVariants: {
        EmotionalTone.huzur: 'Uyumlu calisma',
        EmotionalTone.korku: 'Rekabet, entrika',
        EmotionalTone.merak: 'Firsatlar',
        EmotionalTone.donukluk: 'Rutin, sikicilik',
      },
      archetypes: ['Ortak', 'Rakip', 'Yansima'],
      relatedSymbols: ['work', 'office', 'team', 'competition'],
      shadowAspect: 'Rekabet, guvenszlik',
      lightAspect: 'Isbirligi, ogrenme',
    ),

    DreamSymbolData(
      symbol: 'neighbor',
      symbolTr: 'Komsu',
      emoji: '🏘️',
      category: SymbolCategory.insan,
      universalMeanings: [
        'Yakin cevre',
        'Gundelik iliski',
        'Sinir komsulugu',
        'Topluluk',
        'Karsilastirma',
        'Gozetim',
      ],
      emotionVariants: {
        EmotionalTone.huzur: 'Dostca iliski',
        EmotionalTone.korku: 'Gizlilik ihlali',
        EmotionalTone.merak: 'Kapali kapilar ardinda ne var?',
        EmotionalTone.ofke: 'Sinir ihlali',
      },
      archetypes: ['Tanik', 'Komsuluk', 'Sinir'],
      relatedSymbols: ['home', 'fence', 'community', 'privacy'],
      shadowAspect: 'Merak, dedikodu',
      lightAspect: 'Topluluk, destek',
    ),

    DreamSymbolData(
      symbol: 'crowd',
      symbolTr: 'Kalabalik',
      emoji: '👥',
      category: SymbolCategory.insan,
      universalMeanings: [
        'Kolektif bilinc',
        'Sosyal baski',
        'Anonimlik',
        'Toplum',
        'Kaybolma veya ait olma',
        'Kamuoyu',
      ],
      emotionVariants: {
        EmotionalTone.korku: 'Bogulma, kaybolma',
        EmotionalTone.huzur: 'Ait olma',
        EmotionalTone.donukluk: 'Anonimlik',
        EmotionalTone.heyecan: 'Enerji, heyecan',
      },
      archetypes: ['Kolektif', 'Toplum', 'Kalabalik'],
      relatedSymbols: ['society', 'public', 'anonymity', 'belonging'],
      shadowAspect: 'Bireysellik kaybi',
      lightAspect: 'Aidiyet, guc',
    ),

    DreamSymbolData(
      symbol: 'party',
      symbolTr: 'Parti',
      emoji: '🎉',
      category: SymbolCategory.eylem,
      universalMeanings: [
        'Kutlama ve eglence',
        'Sosyal baglanti',
        'Hayatin kutlanmasi',
        'Maskelerin dusmesi',
        'Firsatlar',
        'Rahatlama',
      ],
      emotionVariants: {
        EmotionalTone.heyecan: 'Keyif ve eglence',
        EmotionalTone.korku: 'Sosyal anksiyete',
        EmotionalTone.huzur: 'Ait olma hissi',
        EmotionalTone.ozlem: 'Genc gunlere ozlem',
      },
      archetypes: ['Kutlama', 'Toplanti', 'Maske'],
      relatedSymbols: ['celebration', 'dance', 'friends', 'mask'],
      shadowAspect: 'Yuzeysellik, kacis',
      lightAspect: 'Baglanti, kutlama',
    ),

    DreamSymbolData(
      symbol: 'reunion',
      symbolTr: 'Kavusma/Bulusma',
      emoji: '🤝',
      category: SymbolCategory.eylem,
      universalMeanings: [
        'Yeniden baglanti',
        'Gecmisin islenmesi',
        'Nostalji',
        'Tamamlanmamis is',
        'Dongu tamamlama',
        'Eskilerle yuzlesme',
      ],
      emotionVariants: {
        EmotionalTone.ozlem: 'Hasret giderme',
        EmotionalTone.korku: 'Karsilastirma, degisim',
        EmotionalTone.heyecan: 'Yeniden bulusma sevinci',
        EmotionalTone.merak: 'Nasil degismisler?',
      },
      archetypes: ['Dongu', 'Baglanti', 'Gecmis'],
      relatedSymbols: ['past', 'memory', 'friends', 'change'],
      shadowAspect: 'Gecmise takilma',
      lightAspect: 'Tamamlanma, baris',
    ),

    DreamSymbolData(
      symbol: 'argument',
      symbolTr: 'Tartisma',
      emoji: '🗣️',
      category: SymbolCategory.eylem,
      universalMeanings: [
        'Ic catisma',
        'Ifade edilmemis duygular',
        'Sinir belirleme',
        'Guc mucadelesi',
        'Farkli bakis acilari',
        'Cozum arayisi',
      ],
      emotionVariants: {
        EmotionalTone.ofke: 'Patlamis duygular',
        EmotionalTone.korku: 'Iliski kaybi',
        EmotionalTone.sucluluk: 'Soylediklerim',
        EmotionalTone.huzur: 'Sonunda ifade',
      },
      archetypes: ['Catisma', 'Ifade', 'Sinir'],
      relatedSymbols: ['anger', 'voice', 'conflict', 'resolution'],
      shadowAspect: 'Kontrolsuz ofke',
      lightAspect: 'Dogruyu soylemek, netlik',
    ),

    DreamSymbolData(
      symbol: 'apology',
      symbolTr: 'Ozur',
      emoji: '🙏',
      category: SymbolCategory.eylem,
      universalMeanings: [
        'Pismanlik ve kabul',
        'Iliski onarimi',
        'Alcakgonulluluk',
        'Sorumluluk alma',
        'Affetme sureci',
        'Barış arayisi',
      ],
      emotionVariants: {
        EmotionalTone.sucluluk: 'Hatanin kabulu',
        EmotionalTone.huzur: 'Rahatlama',
        EmotionalTone.korku: 'Red edilme',
        EmotionalTone.ozlem: 'Eskisi gibi olsun',
      },
      archetypes: ['Tevazu', 'Onarim', 'Baris'],
      relatedSymbols: ['forgiveness', 'healing', 'guilt', 'peace'],
      shadowAspect: 'Sahte ozur, manipülasyon',
      lightAspect: 'Gercek pismanlik, sifa',
    ),

    // ════════════════════════════════════════════════════════════════════════
    // TOPLUMSAL ROLLER - 15+ Sembol
    // ════════════════════════════════════════════════════════════════════════
    DreamSymbolData(
      symbol: 'king',
      symbolTr: 'Kral',
      emoji: '👑',
      category: SymbolCategory.insan,
      universalMeanings: [
        'Ust benlik',
        'Otorite ve guc',
        'Liderlik',
        'Sorumluluk',
        'Erkek arketipi',
        'Hakimiyet',
      ],
      emotionVariants: {
        EmotionalTone.huzur: 'Ic guc ve hakimiyet',
        EmotionalTone.korku: 'Ezici otorite',
        EmotionalTone.heyecan: 'Guc potansiyeli',
        EmotionalTone.merak: 'Liderlik cagirisi',
      },
      archetypes: ['Kral', 'Lider', 'Baba'],
      relatedSymbols: ['crown', 'throne', 'power', 'father'],
      shadowAspect: 'Tiran, diktatör',
      lightAspect: 'Adil lider, koruyucu',
    ),

    DreamSymbolData(
      symbol: 'queen',
      symbolTr: 'Kralice',
      emoji: '👸',
      category: SymbolCategory.insan,
      universalMeanings: [
        'Feminin guc',
        'Sezgi ve bilgelik',
        'Bolluk ve bereket',
        'Ic kralice',
        'Liderlik',
        'Sevgi ve otorite dengesi',
      ],
      emotionVariants: {
        EmotionalTone.huzur: 'Ic guc ve zarafet',
        EmotionalTone.heyecan: 'Guc uyanisi',
        EmotionalTone.korku: 'Golgede kalan guc',
        EmotionalTone.merak: 'Kadinlik kesfı',
      },
      archetypes: ['Kralice', 'Anne', 'Bilge Kadin'],
      relatedSymbols: ['crown', 'mother', 'power', 'wisdom'],
      shadowAspect: 'Manipulatif, soguk',
      lightAspect: 'Bilge lider, besleyici',
    ),

    DreamSymbolData(
      symbol: 'priest',
      symbolTr: 'Rahip/Din Adami',
      emoji: '⛪',
      category: SymbolCategory.insan,
      universalMeanings: [
        'Ruhani otorite',
        'Ahlaki rehberlik',
        'Kutsal baglanti',
        'Araci figur',
        'Geleneksel bilgelik',
        'Manevi yol',
      ],
      emotionVariants: {
        EmotionalTone.huzur: 'Ruhani rehberlik',
        EmotionalTone.korku: 'Yargilama, gunah',
        EmotionalTone.merak: 'Manevi arayis',
        EmotionalTone.sucluluk: 'Itiraf ihtiyaci',
      },
      archetypes: ['Bilge', 'Araci', 'Otorite'],
      relatedSymbols: ['church', 'god', 'prayer', 'confession'],
      shadowAspect: 'Ikiyuzluluk, kontrol',
      lightAspect: 'Gercek rehberlik, sifa',
    ),

    DreamSymbolData(
      symbol: 'judge',
      symbolTr: 'Hakim/Yargiç',
      emoji: '⚖️',
      category: SymbolCategory.insan,
      universalMeanings: [
        'Ic yargiç',
        'Adalet arayisi',
        'Karar verme',
        'Degerlendirme',
        'Vicdan',
        'Sonuc ve hukum',
      ],
      emotionVariants: {
        EmotionalTone.korku: 'Yargilanma korkusu',
        EmotionalTone.sucluluk: 'Hukum beklentisi',
        EmotionalTone.huzur: 'Adalet tecellisi',
        EmotionalTone.merak: 'Sonuc ne olacak?',
      },
      archetypes: ['Yargiç', 'Vicdan', 'Otorite'],
      relatedSymbols: ['court', 'justice', 'guilt', 'decision'],
      shadowAspect: 'Asiri elestiri, merhametsizlik',
      lightAspect: 'Adil degerlendirme, denge',
    ),

    DreamSymbolData(
      symbol: 'soldier',
      symbolTr: 'Asker',
      emoji: '🪖',
      category: SymbolCategory.insan,
      universalMeanings: [
        'Koruma ve savunma',
        'Disiplin',
        'Mucadele',
        'Kurallara uyma',
        'Fedakarlik',
        'Ic savasci',
      ],
      emotionVariants: {
        EmotionalTone.korku: 'Tehdit, savas',
        EmotionalTone.huzur: 'Koruma altinda',
        EmotionalTone.heyecan: 'Savaşma ruhu',
        EmotionalTone.donukluk: 'Mekanik itaat',
      },
      archetypes: ['Savasci', 'Koruyucu', 'Kahraman'],
      relatedSymbols: ['war', 'weapon', 'uniform', 'battle'],
      shadowAspect: 'Saldirganlik, kor itaat',
      lightAspect: 'Cesaret, koruma, disiplin',
    ),

    DreamSymbolData(
      symbol: 'healer',
      symbolTr: 'Sifaci',
      emoji: '🙌',
      category: SymbolCategory.insan,
      universalMeanings: [
        'Ic sifaci',
        'Iyilesme potansiyeli',
        'Sifa enerjisi',
        'Yardim eli',
        'Ruhani baglanti',
        'Butunlesme',
      ],
      emotionVariants: {
        EmotionalTone.huzur: 'Sifa alimi',
        EmotionalTone.heyecan: 'Iyilesiyo um',
        EmotionalTone.korku: 'Hastalik, zafiyet',
        EmotionalTone.merak: 'Sifa yolu',
      },
      archetypes: ['Sifaci', 'Bilge', 'Yardimci'],
      relatedSymbols: ['healing', 'hands', 'light', 'medicine'],
      shadowAspect: 'Yarali sifaci',
      lightAspect: 'Gercek sifa gucu',
    ),

    DreamSymbolData(
      symbol: 'beggar',
      symbolTr: 'Dilenci',
      emoji: '🙏',
      category: SymbolCategory.insan,
      universalMeanings: [
        'Ihtiyac ve eksiklik',
        'Alcakgonulluluk',
        'Golge benlik',
        'Bagimlilik',
        'Merhamet cagirisi',
        'Deger kaybi',
      ],
      emotionVariants: {
        EmotionalTone.korku: 'Yoksulluk korkusu',
        EmotionalTone.sucluluk: 'Yardim etmeme',
        EmotionalTone.ozlem: 'Kayip bolluk',
        EmotionalTone.merak: 'Ne eksik?',
      },
      archetypes: ['Golge', 'Yoksul', 'Alici'],
      relatedSymbols: ['poverty', 'need', 'humility', 'giving'],
      shadowAspect: 'Deger kaybi, umutsuzluk',
      lightAspect: 'Alcakgonulluluk, kabul',
    ),

    DreamSymbolData(
      symbol: 'thief',
      symbolTr: 'Hirsiz',
      emoji: '🦹',
      category: SymbolCategory.insan,
      universalMeanings: [
        'Kayip korkusu',
        'Enerji vampiri',
        'Sinir ihlali',
        'Golge davranis',
        'Gizli arzular',
        'Güvenszlik',
      ],
      emotionVariants: {
        EmotionalTone.korku: 'Kayip, ihlal',
        EmotionalTone.ofke: 'Adaletsizlik',
        EmotionalTone.merak: 'Ne caliniyor?',
        EmotionalTone.sucluluk: 'Benim hırsiz yanım',
      },
      archetypes: ['Golge', 'Trickster', 'Ihlalci'],
      relatedSymbols: ['loss', 'fear', 'boundary', 'shadow'],
      shadowAspect: 'Calma, ihlal',
      lightAspect: 'Sinir bilinci, koruma',
    ),
  ];
}
