/// MEGA Dream Symbols Database Part 3 - 200+ Sembol
/// Eylemler, Durumlar, Olaylar
library;

import '../models/dream_interpretation_models.dart';

/// Part 3: Eylemler ve Durumlar - 200+ Sembol
class MegaDreamSymbolsPart3 {
  static const List<DreamSymbolData> symbols = [
    // ════════════════════════════════════════════════════════════════════════
    // HAREKET & SEYAHAT - 50+ Sembol
    // ════════════════════════════════════════════════════════════════════════
    DreamSymbolData(
      symbol: 'flying',
      symbolTr: 'Ucmak',
      emoji: '🦅',
      category: SymbolCategory.eylem,
      universalMeanings: [
        'Ozgurluk ve yukselis',
        'Sinirlamalari asma',
        'Ruhsal yolculuk',
        'Kontrol ve guc',
        'Perspektif kazanma',
        'Ego askinligi',
      ],
      emotionVariants: {
        EmotionalTone.heyecan: 'Ozgurlesme - potansiyelini kesfediyorsun',
        EmotionalTone.huzur: 'Ruhsal huzur - yukaridan bakis',
        EmotionalTone.korku: 'Dusme korkusu - kontrol kaybi',
        EmotionalTone.merak: 'Kesfetme arzusu - yeni ufuklar',
      },
      archetypes: ['Ozgur Ruh', 'Kahraman', 'Askin Benlik'],
      relatedSymbols: ['bird', 'sky', 'falling', 'wings', 'airplane'],
      shadowAspect: 'Gerceklikten kacis, megalomani, temelsizlik',
      lightAspect: 'Ruhsal ozgurluk, yaratici vizyon, yuksek bakis',
    ),

    DreamSymbolData(
      symbol: 'falling',
      symbolTr: 'Dusmek',
      emoji: '⬇️',
      category: SymbolCategory.eylem,
      universalMeanings: [
        'Kontrol kaybi',
        'Basarisizlik korkusu',
        'Ego cokusu',
        'Teslim olma',
        'Gerceklige donus',
        'Dusus ve yeniden dogus',
      ],
      emotionVariants: {
        EmotionalTone.korku: 'Kontrol kaybetme - neyi birakamiyorsun?',
        EmotionalTone.donukluk: 'Uyusma - serbest dusus',
        EmotionalTone.heyecan: 'Eski kaliplarindan kurtulus',
        EmotionalTone.sucluluk: 'Dususu hak etme hissi',
      },
      archetypes: ['Dusmus Melek', 'Ego Olumu', 'Donusum'],
      relatedSymbols: ['flying', 'cliff', 'ground', 'abyss'],
      shadowAspect: 'Basarisizlik, degersizlik, yok olma',
      lightAspect: 'Teslim olma, yeniden dogus, alcakgonulluluk',
    ),

    DreamSymbolData(
      symbol: 'running',
      symbolTr: 'Kosmak',
      emoji: '🏃',
      category: SymbolCategory.eylem,
      universalMeanings: [
        'Kacis veya yakalama',
        'Aciliyet hissi',
        'Hayat ritmi',
        'Hedef odaklilik',
        'Enerji seviyesi',
        'Yasam mucadelesi',
      ],
      emotionVariants: {
        EmotionalTone.korku: 'Birinden/birseydenkacis - yuzlesme gerekliligi',
        EmotionalTone.heyecan: 'Hedefe dogru kosma - motivasyon',
        EmotionalTone.donukluk: 'Yorgunluk - kosarken ilerleyememe',
        EmotionalTone.merak: 'Nereye kosuyorum? - hayat yonu',
      },
      archetypes: ['Kacak', 'Avci', 'Atlet'],
      relatedSymbols: ['chasing', 'escape', 'speed', 'legs'],
      shadowAspect: 'Surekli kacis, tukenislik, varamamak',
      lightAspect: 'Kararlilk, dayaniklilik, hedefe ulasma',
    ),

    DreamSymbolData(
      symbol: 'chasing',
      symbolTr: 'Kovalanmak',
      emoji: '😰',
      category: SymbolCategory.eylem,
      universalMeanings: [
        'Bastirilmis korkular',
        'Kacinilan yonler',
        'Golge entegrasyonu',
        'Stres ve baski',
        'Yuzlesme ihtiyaci',
        'Icsel catisma',
      ],
      emotionVariants: {
        EmotionalTone.korku: 'Golge kovalamasi - neyle yuzlesmiyorsun?',
        EmotionalTone.ofke: 'Kovalayan seye ofke - sinir ihlali',
        EmotionalTone.donukluk: 'Kronik kacinma - yorgunluk',
        EmotionalTone.merak: 'Kovalayanin kimligi - golgeyi tani',
      },
      archetypes: ['Golge', 'Avci', 'Kurban'],
      relatedSymbols: ['monster', 'running', 'escape', 'shadow'],
      shadowAspect: 'Kacinma, bastirma, korkuyla yasama',
      lightAspect: 'Farkindalik, cesaret, golge entegrasyonu',
    ),

    DreamSymbolData(
      symbol: 'swimming',
      symbolTr: 'Yuzmek',
      emoji: '🏊',
      category: SymbolCategory.eylem,
      universalMeanings: [
        'Duygusal navigasyon',
        'Bilincdisiyla calismak',
        'Hayatta kalma',
        'Duygusal ustalık',
        'Derinlere dalma',
        'Akim icinde hareket',
      ],
      emotionVariants: {
        EmotionalTone.huzur: 'Duygularla uyum - rahat yuzus',
        EmotionalTone.korku: 'Bogulma korkusu - duygusal bunalma',
        EmotionalTone.heyecan: 'Kesfetme - derinliklere dalis',
        EmotionalTone.donukluk: 'Zor yuzus - duygusal zorluk',
      },
      archetypes: ['Dalgic', 'Gezgin', 'Hayatta Kalan'],
      relatedSymbols: ['water', 'ocean', 'pool', 'drowning'],
      shadowAspect: 'Bogulma, basarisizlik, yorgunluk',
      lightAspect: 'Duygusal ustalık, adaptasyon, akis',
    ),

    DreamSymbolData(
      symbol: 'climbing',
      symbolTr: 'Tirmanmak',
      emoji: '🧗',
      category: SymbolCategory.eylem,
      universalMeanings: [
        'Hedefe ilerleme',
        'Zorlukları asma',
        'Yukselis ve basari',
        'Caba ve kararlilik',
        'Spirituel yukselis',
        'Kariyer ilerleme',
      ],
      emotionVariants: {
        EmotionalTone.heyecan: 'Zirveye yaklasma - basari heyecani',
        EmotionalTone.korku: 'Dusme riski - basarisizlik',
        EmotionalTone.donukluk: 'Cikis yok - tikaniklik',
        EmotionalTone.merak: 'Zirvede ne var? - kesfetme',
      },
      archetypes: ['Kahraman', 'Basar Arayan', 'Mucadeci'],
      relatedSymbols: ['mountain', 'ladder', 'stairs', 'peak'],
      shadowAspect: 'Tukenislik, dusme, hedefe ulasamama',
      lightAspect: 'Azim, basari, ruhsal gelisim',
    ),

    DreamSymbolData(
      symbol: 'walking',
      symbolTr: 'Yurumek',
      emoji: '🚶',
      category: SymbolCategory.eylem,
      universalMeanings: [
        'Hayat yolculugu',
        'Istikrarli ilerleme',
        'Gunluk yasam',
        'Sabir ve sureklilik',
        'Bilinçli hareket',
        'Kendi hizinda ilerleme',
      ],
      emotionVariants: {
        EmotionalTone.huzur: 'Rahat yuruyus - dogru yoldasin',
        EmotionalTone.korku: 'Karanlik yol - belirsizlik',
        EmotionalTone.merak: 'Yeni kesfler - yolculuk zevki',
        EmotionalTone.donukluk: 'Yorucu yuruyus - monotonluk',
      },
      archetypes: ['Yolcu', 'Gezgin', 'Hacı'],
      relatedSymbols: ['path', 'road', 'journey', 'shoes'],
      shadowAspect: 'Hedefsizlik, kaybolma, yorgunluk',
      lightAspect: 'Istikrar, sabir, farkindalıklı yasam',
    ),

    DreamSymbolData(
      symbol: 'driving',
      symbolTr: 'Araba Kullanmak',
      emoji: '🚗',
      category: SymbolCategory.eylem,
      universalMeanings: [
        'Hayat kontrolu',
        'Ego ve irade',
        'Yon belirleme',
        'Guc ve hiz',
        'Kisisel ozerklik',
        'Yasam yonetimi',
      ],
      emotionVariants: {
        EmotionalTone.huzur: 'Kontrol - hayatini yonetiyorsun',
        EmotionalTone.korku: 'Fren tutmuyor - kontrol kaybi',
        EmotionalTone.heyecan: 'Hiz ve ilerleme - hedefe gidiş',
        EmotionalTone.donukluk: 'Arka koltuk - baskasi yonetiyor',
      },
      archetypes: ['Kaptan', 'Ego', 'Kontrolcu'],
      relatedSymbols: ['car', 'road', 'accident', 'steering'],
      shadowAspect: 'Kontrolculuk, kaza, yanlis yon',
      lightAspect: 'Ozerlik, kararlılık, dogru yon',
    ),

    DreamSymbolData(
      symbol: 'jumping',
      symbolTr: 'Ziplamak',
      emoji: '🦘',
      category: SymbolCategory.eylem,
      universalMeanings: [
        'Risk alma',
        'Inanc sicramasi',
        'Engel asma',
        'Enerji ve cosklu',
        'Ani karar',
        'Cesaret gerektiren adim',
      ],
      emotionVariants: {
        EmotionalTone.heyecan: 'Cesaretli adim - risk ve firsat',
        EmotionalTone.korku: 'Ucuruma atlama - buyuk risk',
        EmotionalTone.huzur: 'Hafif siçrama - kucuk mutluluklar',
        EmotionalTone.merak: 'Nereye? - belirsiz gelecek',
      },
      archetypes: ['Maceraci', 'Risk Alan', 'Cesur'],
      relatedSymbols: ['cliff', 'gap', 'flying', 'falling'],
      shadowAspect: 'Dusuncesizlik, tehlikeli risk, dusus',
      lightAspect: 'Cesaret, inanc, donusturucu adim',
    ),

    DreamSymbolData(
      symbol: 'dancing',
      symbolTr: 'Dans Etmek',
      emoji: '💃',
      category: SymbolCategory.eylem,
      universalMeanings: [
        'Ifade ozgurlugu',
        'Hayat ritmi',
        'Sevinc ve kutlama',
        'Iliski dinamikleri',
        'Evrenle uyum',
        'Yaratici enerji',
      ],
      emotionVariants: {
        EmotionalTone.heyecan: 'Coskulu dans - kutlama zamani',
        EmotionalTone.huzur: 'Nazik hareket - ic uyum',
        EmotionalTone.ozlem: 'Partner ariyisi - iliski arzusu',
        EmotionalTone.korku: 'Yanlis adim - uyumsuzluk',
      },
      archetypes: ['Yasam Gucu', 'Ifadeci', 'Asik'],
      relatedSymbols: ['music', 'partner', 'rhythm', 'celebration'],
      shadowAspect: 'Sahte performans, uyumsuzluk, izolasyon',
      lightAspect: 'Ozgun ifade, sevinc, uyum',
    ),

    DreamSymbolData(
      symbol: 'hiding',
      symbolTr: 'Saklanmak',
      emoji: '🙈',
      category: SymbolCategory.eylem,
      universalMeanings: [
        'Korunma ihtiyaci',
        'Kacis ve gizlenme',
        'Utanc veya korku',
        'Savunmasizlik',
        'Gizli yonler',
        'Kendinden kacis',
      ],
      emotionVariants: {
        EmotionalTone.korku: 'Tehditden saklanma - gercek tehlike mi?',
        EmotionalTone.sucluluk: 'Sir saklama - utanc',
        EmotionalTone.donukluk: 'Izolasyon - kendini geri cekme',
        EmotionalTone.huzur: 'Guvenli saklanma - dinlenme',
      },
      archetypes: ['Kacak', 'Gizlenen', 'Korunan Cocuk'],
      relatedSymbols: ['fear', 'secret', 'closet', 'safety'],
      shadowAspect: 'Kronik kacis, yalnizlik, yuzlesmeme',
      lightAspect: 'Stratejik geri cekilme, korunma, dinlenme',
    ),

    DreamSymbolData(
      symbol: 'searching',
      symbolTr: 'Aramak',
      emoji: '🔍',
      category: SymbolCategory.eylem,
      universalMeanings: [
        'Anlam arayisi',
        'Kayip parcayi bulma',
        'Kesfetme durtsu',
        'Eksik olan',
        'Hayat amaci',
        'Oz kesfin',
      ],
      emotionVariants: {
        EmotionalTone.merak: 'Aktif arayis - ne ariyorsun?',
        EmotionalTone.ozlem: 'Kayip sey - boslugun doldurmak',
        EmotionalTone.korku: 'Bulamama korkusu - basarisizlik',
        EmotionalTone.heyecan: 'Kesfin esiginde - yaklasiyorsun',
      },
      archetypes: ['Arayan', 'Dedektif', 'Gezgin'],
      relatedSymbols: ['lost', 'finding', 'key', 'treasure'],
      shadowAspect: 'Obsesif arayis, tatminsizlik, bulamama',
      lightAspect: 'Merak, kesif sevinci, anlam bulma',
    ),

    // ════════════════════════════════════════════════════════════════════════
    // ILETISIM & SOSYAL EYLEMLER - 30+ Sembol
    // ════════════════════════════════════════════════════════════════════════
    DreamSymbolData(
      symbol: 'speaking',
      symbolTr: 'Konusmak',
      emoji: '🗣️',
      category: SymbolCategory.eylem,
      universalMeanings: [
        'Ifade ve iletisim',
        'Gercegi soylemek',
        'Kendi sesini bulmak',
        'Sosyal baglanti',
        'Dusunceleri paylasma',
        'Guc ve etki',
      ],
      emotionVariants: {
        EmotionalTone.huzur: 'Rahat konusma - ifade ozgurlugu',
        EmotionalTone.korku: 'Ses cikmiyor - susturulma',
        EmotionalTone.ofke: 'Bagirma - duyulmak',
        EmotionalTone.merak: 'Dil farki - anlasma zorluklari',
      },
      archetypes: ['Haberci', 'Ogretmen', 'Ifadeci'],
      relatedSymbols: ['voice', 'mouth', 'language', 'silence'],
      shadowAspect: 'Susturulma, yanlis anlasılma, manipulasyon',
      lightAspect: 'Otantik ifade, etkileme, baglanti',
    ),

    DreamSymbolData(
      symbol: 'crying',
      symbolTr: 'Aglamak',
      emoji: '😢',
      category: SymbolCategory.eylem,
      universalMeanings: [
        'Duygusal salıveris',
        'Keder ve kayıp',
        'Arinma',
        'Kirilganlik',
        'Sifa süreci',
        'Ic cocuk acisi',
      ],
      emotionVariants: {
        EmotionalTone.huzur: 'Rahatlatici agıt - salıveris',
        EmotionalTone.sucluluk: 'Pismanlik gozyaslari - kefareti',
        EmotionalTone.ozlem: 'Kayip icin aglama - yas',
        EmotionalTone.ofke: 'Ofke gozyaslari - bastırılmis kizginlik',
      },
      archetypes: ['Yas Tutan', 'Ic Cocuk', 'Sifaci'],
      relatedSymbols: ['tears', 'sadness', 'rain', 'release'],
      shadowAspect: 'Bastirilmis keder, donukluk, yalnızlik',
      lightAspect: 'Duygusal sifa, arinma, otantiklik',
    ),

    DreamSymbolData(
      symbol: 'laughing',
      symbolTr: 'Gulmek',
      emoji: '😄',
      category: SymbolCategory.eylem,
      universalMeanings: [
        'Sevinc ve mutluluk',
        'Salıveris ve rahatlama',
        'Sosyal baglanti',
        'Iyilestirici guc',
        'Perspektif degisimi',
        'Ic huzur',
      ],
      emotionVariants: {
        EmotionalTone.heyecan: 'Gercek kahkaha - ic sevinc',
        EmotionalTone.korku: 'Alay edilme - utanc',
        EmotionalTone.huzur: 'Icten gulme - ic baris',
        EmotionalTone.donukluk: 'Zorlama gulus - maske',
      },
      archetypes: ['Soytari', 'Mutlu Cocuk', 'Sifaci'],
      relatedSymbols: ['joy', 'humor', 'celebration', 'friends'],
      shadowAspect: 'Sahte mutluluk, alay, kacis',
      lightAspect: 'Gercek sevinc, sifa, perspektif',
    ),

    DreamSymbolData(
      symbol: 'fighting',
      symbolTr: 'Dovusmek',
      emoji: '👊',
      category: SymbolCategory.eylem,
      universalMeanings: [
        'Ic catisma',
        'Savunma ve sinirlar',
        'Guc mucadelesi',
        'Bastırılmis öfke',
        'Kontrolucadele',
        'Kahramanlık testi',
      ],
      emotionVariants: {
        EmotionalTone.ofke: 'Aktif mucadele - ofke disavurumu',
        EmotionalTone.korku: 'Zorla karsi koyma - guc dengesizligi',
        EmotionalTone.heyecan: 'Savascı ruhu - meydan okuma',
        EmotionalTone.sucluluk: 'Siddet pismnaligi - zarar verme',
      },
      archetypes: ['Savasci', 'Savunucu', 'Golge'],
      relatedSymbols: ['enemy', 'war', 'weapon', 'victory'],
      shadowAspect: 'Yikici ofke, siddet, kontrol kaybi',
      lightAspect: 'Sinir koruma, cesaret, hakli mucadele',
    ),

    DreamSymbolData(
      symbol: 'kissing',
      symbolTr: 'Opmek',
      emoji: '💋',
      category: SymbolCategory.eylem,
      universalMeanings: [
        'Birlesme ve yakinlik',
        'Sevgi ifadesi',
        'Kabul ve onay',
        'Iliski dinamigi',
        'Anima/Animus birlesimi',
        'Kutsal birlık',
      ],
      emotionVariants: {
        EmotionalTone.huzur: 'Sevgi dolu opucuk - kabul',
        EmotionalTone.heyecan: 'Tutku - romantik baglanma',
        EmotionalTone.korku: 'İstenmeyen opucuk - sinir ihlali',
        EmotionalTone.merak: 'Beklenmedik kisi - golge entegrasyonu',
      },
      archetypes: ['Asik', 'Birlesik Benlik', 'Sevgi'],
      relatedSymbols: ['love', 'partner', 'intimacy', 'wedding'],
      shadowAspect: 'Sahte yakinlik, manipulasyon, ihanet',
      lightAspect: 'Gercek birlik, sevgi, ic evlilik',
    ),

    DreamSymbolData(
      symbol: 'eating',
      symbolTr: 'Yemek Yemek',
      emoji: '🍽️',
      category: SymbolCategory.eylem,
      universalMeanings: [
        'Beslenme ve entegrasyon',
        'Bilgi ve deneyim ozumlemek',
        'Fiziksel ihtiyaclar',
        'Zevk ve tatmin',
        'Duygusal doyum',
        'Icsellestime',
      ],
      emotionVariants: {
        EmotionalTone.huzur: 'Doyurucu yemek - tatmin',
        EmotionalTone.korku: 'Bozuk yemek - zararli sey ozumseme',
        EmotionalTone.merak: 'Yeni tatlar - yeni deneyimler',
        EmotionalTone.sucluluk: 'Asiri yeme - duygusal bosluğ',
      },
      archetypes: ['Besleyici', 'Tuketici', 'Hayatta Kalan'],
      relatedSymbols: ['food', 'hunger', 'table', 'mouth'],
      shadowAspect: 'Asırı tuketim, aclik, yoksunluk',
      lightAspect: 'Saglikli beslenme, entegrasyon, doyum',
    ),

    // ════════════════════════════════════════════════════════════════════════
    // FIZIKSEL DURUMLAR - 30+ Sembol
    // ════════════════════════════════════════════════════════════════════════
    DreamSymbolData(
      symbol: 'naked',
      symbolTr: 'Ciplak Olmak',
      emoji: '😳',
      category: SymbolCategory.eylem,
      universalMeanings: [
        'Savunmasizlik',
        'Gercek benligin aciga cikmasi',
        'Utanc ve ifsa',
        'Maskelerin dusmesi',
        'Otantiklik',
        'Kirilganlik gucu',
      ],
      emotionVariants: {
        EmotionalTone.korku: 'Ifsa olma korkusu - gercek sen gorunuyor',
        EmotionalTone.sucluluk: 'Sir aciga cikmis - utanc',
        EmotionalTone.huzur: 'Maskeleri atma - ozgurlesme',
        EmotionalTone.merak: 'Tepkiler - baskalarinin gorusu',
      },
      archetypes: ['Masum', 'Gercek Benlik', 'Kirilgan Cocuk'],
      relatedSymbols: ['exposure', 'shame', 'truth', 'vulnerability'],
      shadowAspect: 'Utanc, savunmasizlik, yetersizlik',
      lightAspect: 'Otantiklik, cesaret, kabul',
    ),

    DreamSymbolData(
      symbol: 'teeth_falling',
      symbolTr: 'Dis Dokulmus',
      emoji: '🦷',
      category: SymbolCategory.eylem,
      universalMeanings: [
        'Guc ve imaj kaybi',
        'Yaslanma korkusu',
        'Iletisim sorunlari',
        'Cekicilik endisesi',
        'Soylenmemis sozler',
        'Kontrol kaybi',
      ],
      emotionVariants: {
        EmotionalTone.korku: 'Guc kaybi - savunmasizlik',
        EmotionalTone.sucluluk: 'Soylenmemis sozler - pismanlik',
        EmotionalTone.donukluk: 'Cekicilik kaybi - yaslanma',
        EmotionalTone.ofke: 'Ifade edememe - hayal kirikligi',
      },
      archetypes: ['Persona', 'Guc', 'Iletisimci'],
      relatedSymbols: ['mouth', 'aging', 'image', 'speech'],
      shadowAspect: 'Gucsuzluk, cekicilik kaybi, sessizlik',
      lightAspect: 'Icsel deger, otantik guc, dogru zamanda konusma',
    ),

    DreamSymbolData(
      symbol: 'lost',
      symbolTr: 'Kaybolmak',
      emoji: '🧭',
      category: SymbolCategory.eylem,
      universalMeanings: [
        'Yon kaybi',
        'Kimlik karmasasi',
        'Hayat yolunda belirsizlik',
        'Aidiyet arayisi',
        'Ic pusula kaybi',
        'Dönüsum oncesi kaos',
      ],
      emotionVariants: {
        EmotionalTone.korku: 'Panik - neredeyim, nereye gidiyorum?',
        EmotionalTone.merak: 'Kesfetme firsati - yeni yollar',
        EmotionalTone.ozlem: 'Eve donus arzusu - kokler',
        EmotionalTone.donukluk: 'Yonsuzluk - pusula yok',
      },
      archetypes: ['Kayip Ruh', 'Gezgin', 'Arayan'],
      relatedSymbols: ['path', 'map', 'home', 'compass'],
      shadowAspect: 'Anlamsizlik, terkedilmislik, kimlik krizi',
      lightAspect: 'Keşfetme, yeni baslangiçlar, ic rehberlik',
    ),

    DreamSymbolData(
      symbol: 'drowning',
      symbolTr: 'Bogulmak',
      emoji: '🌊',
      category: SymbolCategory.eylem,
      universalMeanings: [
        'Duygusal bunalma',
        'Baskı altında ezilme',
        'Kontrol kaybetme',
        'Çaresizlik',
        'Nefes alamama',
        'Aşırı sorumluluk',
      ],
      emotionVariants: {
        EmotionalTone.korku: 'Ezilme - cok fazla geliyor',
        EmotionalTone.donukluk: 'Teslim olma - bırakma',
        EmotionalTone.ofke: 'Yardım gelmemesi - yalnızlık',
        EmotionalTone.sucluluk: 'Kendi hataların - sorumluluk',
      },
      archetypes: ['Kurban', 'Basinç Altında', 'Donusum'],
      relatedSymbols: ['water', 'ocean', 'breathing', 'rescue'],
      shadowAspect: 'Ezilme, caresizlik, yok olma',
      lightAspect: 'Duygusal sınırlar, yardım istemek, yuzmeyi ogrenmek',
    ),

    DreamSymbolData(
      symbol: 'paralyzed',
      symbolTr: 'Felc Olmak',
      emoji: '😶',
      category: SymbolCategory.eylem,
      universalMeanings: [
        'Hareket edememe',
        'Korku donuklugu',
        'Karar verememe',
        'Guc kaybı',
        'Uyku felci',
        'Tıkılıp kalmış hissi',
      ],
      emotionVariants: {
        EmotionalTone.korku: 'Tehdide tepki verememe - caresizlik',
        EmotionalTone.donukluk: 'Tam donukluk - tumuyle bloke',
        EmotionalTone.ofke: 'Hayal kirikligi - hareket istiyor',
        EmotionalTone.sucluluk: 'Hareketsizligin bedeli',
      },
      archetypes: ['Donmus Benlik', 'Tıkanmıs', 'Bekleyen'],
      relatedSymbols: ['frozen', 'stuck', 'fear', 'sleep_paralysis'],
      shadowAspect: 'Guc kaybı, kontrol yoksunlugu, korku',
      lightAspect: 'Bekleme bilgeligi, dogru zamanı kollama, teslimiyet',
    ),

    DreamSymbolData(
      symbol: 'pregnant',
      symbolTr: 'Hamile Olmak',
      emoji: '🤰',
      category: SymbolCategory.eylem,
      universalMeanings: [
        'Yaratici potansiyel',
        'Yeni proje/fikir',
        'Buyume ve gelisim',
        'Beklenti',
        'Icsel donusum',
        'Yeni yasam enerjisi',
      ],
      emotionVariants: {
        EmotionalTone.heyecan: 'Yenilik geliyor - yaratici hamilelik',
        EmotionalTone.korku: 'Hazır değilim - sorumluluk',
        EmotionalTone.merak: 'Ne dogacak? - potansiyel',
        EmotionalTone.huzur: 'Dogal surec - zamanlama',
      },
      archetypes: ['Yaratici', 'Anne', 'Potansiyel'],
      relatedSymbols: ['birth', 'baby', 'creation', 'growth'],
      shadowAspect: 'İstenmeyen sorumluluk, korku, hazırlıksızlık',
      lightAspect: 'Yaraticilik, yeni baslangic, buyume',
    ),

    DreamSymbolData(
      symbol: 'dying',
      symbolTr: 'Olmek',
      emoji: '💀',
      category: SymbolCategory.eylem,
      universalMeanings: [
        'Donusum ve son',
        'Eski benligin olumu',
        'Yeniden dogus',
        'Koklu degisim',
        'Ego transcendi',
        'Yasam dongüsu',
      ],
      emotionVariants: {
        EmotionalTone.korku: 'Degisim korkusu - neyin olmesi gerekiyor?',
        EmotionalTone.huzur: 'Bariscil gecis - kabul',
        EmotionalTone.sucluluk: 'Tamamlanmamis isler',
        EmotionalTone.donukluk: 'Dongunun parcasi - teslimiyet',
      },
      archetypes: ['Donusum', 'Son/Baslangic', 'Yeniden Dogus'],
      relatedSymbols: ['death', 'rebirth', 'transformation', 'ending'],
      shadowAspect: 'Olum korkusu, kayip, yok olma',
      lightAspect: 'Donusum, yenilenme, olumsuz ruh',
    ),

    DreamSymbolData(
      symbol: 'giving_birth',
      symbolTr: 'Dogum Yapmak',
      emoji: '👶',
      category: SymbolCategory.eylem,
      universalMeanings: [
        'Yeni baslangiç',
        'Yaratici urun',
        'Potansiyelin gerceklesmesi',
        'Aci ile donusum',
        'Hayata getirme',
        'Sorumluluk',
      ],
      emotionVariants: {
        EmotionalTone.heyecan: 'Yeni yaratim - projeni donyaya getir',
        EmotionalTone.korku: 'Dogum sancisi - zorluklar',
        EmotionalTone.huzur: 'Kolay dogum - dogal akis',
        EmotionalTone.sucluluk: 'Hazır mıyım? - yetersizlik',
      },
      archetypes: ['Yaratici Anne', 'Hayat Veren', 'Baslangic'],
      relatedSymbols: ['baby', 'pregnancy', 'creation', 'beginning'],
      shadowAspect: 'Aci, korku, sorumluluk',
      lightAspect: 'Yaratma sevinci, yeni yasam, tamamlanma',
    ),

    // ════════════════════════════════════════════════════════════════════════
    // MESLEKI & GUNLUK EYLEMLER - 30+ Sembol
    // ════════════════════════════════════════════════════════════════════════
    DreamSymbolData(
      symbol: 'working',
      symbolTr: 'Calismak',
      emoji: '💼',
      category: SymbolCategory.eylem,
      universalMeanings: [
        'Uretkenlik ve amac',
        'Kariyer ve kimlik',
        'Sorumluluk',
        'Hayatta kalma',
        'Basari arayisi',
        'Toplumsal rol',
      ],
      emotionVariants: {
        EmotionalTone.huzur: 'Anlamli calisma - tatmin',
        EmotionalTone.korku: 'Is stresi - baski',
        EmotionalTone.donukluk: 'Anlamsiz is - tukenme',
        EmotionalTone.heyecan: 'Yeni proje - motivasyon',
      },
      archetypes: ['İşçi', 'Uretici', 'Sağlayıcı'],
      relatedSymbols: ['office', 'boss', 'deadline', 'money'],
      shadowAspect: 'Tukenme, anlamsizlik, kolelık',
      lightAspect: 'Amac, basari, katki',
    ),

    DreamSymbolData(
      symbol: 'studying',
      symbolTr: 'Ders Calismak',
      emoji: '📚',
      category: SymbolCategory.eylem,
      universalMeanings: [
        'Ogrenme ve gelisim',
        'Sinav hazirligi',
        'Bilgi arayisi',
        'Kendini gelistirme',
        'Hayat dersleri',
        'Merak ve arastirma',
      ],
      emotionVariants: {
        EmotionalTone.korku: 'Hazırliksiz - sinav kaygisi',
        EmotionalTone.merak: 'Kesfetme keyfi - bilgi acil',
        EmotionalTone.donukluk: 'Zorunlu ogrenme - motivasyon eksikligi',
        EmotionalTone.heyecan: 'Yeni bilgiler - icgoruler',
      },
      archetypes: ['Ogrenci', 'Arayan', 'Bilge'],
      relatedSymbols: ['school', 'exam', 'book', 'teacher'],
      shadowAspect: 'Basarisizlik korkusu, yetersizlik',
      lightAspect: 'Surekli gelisim, ustalık, bilgelik',
    ),

    DreamSymbolData(
      symbol: 'cooking',
      symbolTr: 'Yemek Yapmak',
      emoji: '🍳',
      category: SymbolCategory.eylem,
      universalMeanings: [
        'Yaraticilik ve donusum',
        'Besleyicilik',
        'Kimyasal degisim - simya',
        'Bakim ve sevgi',
        'Kaynaklari birlestirme',
        'Icsel hazırlik',
      ],
      emotionVariants: {
        EmotionalTone.huzur: 'Keyifli pisirme - ozen',
        EmotionalTone.korku: 'Yemek yanmis - basarisiz donusum',
        EmotionalTone.heyecan: 'Yeni tarif - yaratici deney',
        EmotionalTone.sucluluk: 'Baskalarina sunamama - yetersizlik',
      },
      archetypes: ['Simyaci', 'Besleyici', 'Yaratici'],
      relatedSymbols: ['food', 'kitchen', 'fire', 'recipe'],
      shadowAspect: 'Basarisiz donusum, israf, yetersizlik',
      lightAspect: 'Yaratici donusum, besleme, ozen',
    ),

    DreamSymbolData(
      symbol: 'cleaning',
      symbolTr: 'Temizlik Yapmak',
      emoji: '🧹',
      category: SymbolCategory.eylem,
      universalMeanings: [
        'Arinma ve duzenleme',
        'Eski enerjileri temizleme',
        'Hayati düzene sokma',
        'Pismanlikları temizleme',
        'Yeni alan yaratma',
        'Ruhsal temizlik',
      ],
      emotionVariants: {
        EmotionalTone.huzur: 'Ferahlık - temiz baslangıc',
        EmotionalTone.donukluk: 'Sıkıcı is - zorunlu temizlik',
        EmotionalTone.sucluluk: 'Kirlilik - pismanlik',
        EmotionalTone.heyecan: 'Yeni duzenleme - degisim',
      },
      archetypes: ['Arindirici', 'Düzenleyici', 'Sifaci'],
      relatedSymbols: ['dirt', 'order', 'purification', 'organization'],
      shadowAspect: 'Takinti, kontrol, mükemmeliyetçilik',
      lightAspect: 'Arinma, düzen, yeni baslangıc',
    ),

    DreamSymbolData(
      symbol: 'building',
      symbolTr: 'Insa Etmek',
      emoji: '🏗️',
      category: SymbolCategory.eylem,
      universalMeanings: [
        'Yaraticilik ve üretim',
        'Hayat kurma',
        'Temeller atma',
        'Gelecek planlama',
        'Benlik insası',
        'Somut basari',
      ],
      emotionVariants: {
        EmotionalTone.heyecan: 'Yeni yapı - buyuk proje',
        EmotionalTone.huzur: 'Saglamtemel - güvenlik',
        EmotionalTone.korku: 'Yikilan yapı - basarisizlik',
        EmotionalTone.merak: 'Ne insa ediyorum? - hayat projesi',
      },
      archetypes: ['Mimar', 'Yaratici', 'Kurucu'],
      relatedSymbols: ['house', 'foundation', 'construction', 'plan'],
      shadowAspect: 'Yikilma, basarisizlik, temelsizlik',
      lightAspect: 'Yaraticilik, saglam temel, basarı',
    ),

    DreamSymbolData(
      symbol: 'teaching',
      symbolTr: 'Ogretmek',
      emoji: '👨‍🏫',
      category: SymbolCategory.eylem,
      universalMeanings: [
        'Bilgi paylasimi',
        'Rehberlik',
        'Ustalık ve deneyim',
        'Icsel bilgelik',
        'Kendi ogretmenin ol',
        'Miras birakma',
      ],
      emotionVariants: {
        EmotionalTone.huzur: 'Ilham verme - basarili aktarim',
        EmotionalTone.korku: 'Yetersiz hisstetme - bilgi eksikligi',
        EmotionalTone.heyecan: 'Yeni ogrenciler - etki alani',
        EmotionalTone.sucluluk: 'Yanlis ogretim - sorumluluk',
      },
      archetypes: ['Bilge', 'Ogretmen', 'Rehber'],
      relatedSymbols: ['student', 'wisdom', 'knowledge', 'mentor'],
      shadowAspect: 'Yanlis yonlendirme, bilgi eksikligi, kibir',
      lightAspect: 'Bilgelik paylasimi, miras, ilham',
    ),

    DreamSymbolData(
      symbol: 'healing',
      symbolTr: 'Iyilestirmek',
      emoji: '💚',
      category: SymbolCategory.eylem,
      universalMeanings: [
        'Sifa ve onarim',
        'Oz-bakım',
        'Baskalarına yardim',
        'Duygusal iyilesme',
        'Bütünlesme',
        'Dogal sifa gucu',
      ],
      emotionVariants: {
        EmotionalTone.huzur: 'Sifa akisi - iyilesme',
        EmotionalTone.merak: 'Sifa yolları - kesfetme',
        EmotionalTone.sucluluk: 'Hasar verme - pismanlik',
        EmotionalTone.heyecan: 'Sifa gucu - yetenek keşfi',
      },
      archetypes: ['Sifaci', 'Doktor', 'Saman'],
      relatedSymbols: ['medicine', 'wound', 'recovery', 'health'],
      shadowAspect: 'Yaralar, hasar, iyilesmeme',
      lightAspect: 'Dogal sifa, bütünlesme, bakim',
    ),

    DreamSymbolData(
      symbol: 'writing',
      symbolTr: 'Yazmak',
      emoji: '✍️',
      category: SymbolCategory.eylem,
      universalMeanings: [
        'İfade ve yaraticilik',
        'Kayıt ve belgeleme',
        'Düşünceleri şekillendirme',
        'Iletisim',
        'Miras bırakma',
        'Ic ses',
      ],
      emotionVariants: {
        EmotionalTone.huzur: 'Akici yazim - ifade ozgurlugu',
        EmotionalTone.korku: 'Bos sayfa - tikaniklik',
        EmotionalTone.merak: 'Ne yaziyorum? - bilincdisi mesaj',
        EmotionalTone.heyecan: 'Ilham - yaratici patlama',
      },
      archetypes: ['Yazar', 'Kahin', 'Haberci'],
      relatedSymbols: ['book', 'pen', 'message', 'letter'],
      shadowAspect: 'Tikaniklik, ifade edememe, kaybolan sozler',
      lightAspect: 'Yaratici ifade, miras, iletisim',
    ),

    // ════════════════════════════════════════════════════════════════════════
    // DINI & SPIRITÜEL EYLEMLER - 20+ Sembol
    // ════════════════════════════════════════════════════════════════════════
    DreamSymbolData(
      symbol: 'praying',
      symbolTr: 'Dua Etmek',
      emoji: '🙏',
      category: SymbolCategory.eylem,
      universalMeanings: [
        'Spiritüel baglanti',
        'Yardim isteme',
        'Teslimiyet',
        'Sukran',
        'Iç huzur arayisi',
        'Yüksek güçle iletisim',
      ],
      emotionVariants: {
        EmotionalTone.huzur: 'Derin baglanti - spirituel huzur',
        EmotionalTone.korku: 'Caresizce dua - son care',
        EmotionalTone.ozlem: 'Baglanti arayisi - yalnizlik',
        EmotionalTone.sucluluk: 'Af dileme - pismanlik',
      },
      archetypes: ['Ruhani', 'Ariyan', 'Teslim Olan'],
      relatedSymbols: ['temple', 'light', 'god', 'angel'],
      shadowAspect: 'Caresizlik, bagimliliк, kaçis',
      lightAspect: 'Spiritüel bütünlük, teslimiyet, huzur',
    ),

    DreamSymbolData(
      symbol: 'meditating',
      symbolTr: 'Meditasyon Yapmak',
      emoji: '🧘',
      category: SymbolCategory.eylem,
      universalMeanings: [
        'Ic huzur ve sessizlik',
        'Bilinc genislemesi',
        'Oz-farkindalik',
        'Spirituel pratik',
        'Zihin berrakliği',
        'Simdi aninda olma',
      ],
      emotionVariants: {
        EmotionalTone.huzur: 'Derin sessizlik - ic baris',
        EmotionalTone.merak: 'Bilinc keşfi - yeni farkindaliklar',
        EmotionalTone.donukluk: 'Odaklanamama - zihin dağınıklığı',
        EmotionalTone.heyecan: 'Içgörü - aydinlanma ani',
      },
      archetypes: ['Bilge', 'Mistik', 'Gozlemci'],
      relatedSymbols: ['peace', 'silence', 'breath', 'awareness'],
      shadowAspect: 'Kacis, dissosiyasyon, gerçeklikten kopma',
      lightAspect: 'Oz-farkindalik, huzur, bilinclilik',
    ),

    DreamSymbolData(
      symbol: 'baptism',
      symbolTr: 'Vaftiz Olmak',
      emoji: '💧',
      category: SymbolCategory.eylem,
      universalMeanings: [
        'Ruhsal yenilenme',
        'Arinma ve temizlenme',
        'Yeni baslangic',
        'Topluluga kabul',
        'Eski benliğin ölümü',
        'Kutsal donus',
      ],
      emotionVariants: {
        EmotionalTone.huzur: 'Ruhsal arinma - yeni hayat',
        EmotionalTone.heyecan: 'Kabul edilme - aidiyet',
        EmotionalTone.korku: 'Suyaaltina gitme - bogulma',
        EmotionalTone.merak: 'Donusum - ne degisiyor?',
      },
      archetypes: ['Yeniden Dogan', 'Arinmis', 'Kutsanmis'],
      relatedSymbols: ['water', 'purification', 'rebirth', 'ceremony'],
      shadowAspect: 'Zorla donusum, kimlik kaybı',
      lightAspect: 'Ruhsal yenilenme, arinma, yeni hayat',
    ),

    DreamSymbolData(
      symbol: 'ritual',
      symbolTr: 'Rituel Yapmak',
      emoji: '🕯️',
      category: SymbolCategory.eylem,
      universalMeanings: [
        'Kutsal eylem',
        'Geçiş töreni',
        'Spiritüel baglanti',
        'Topluluk',
        'Anlam yaratma',
        'Donusum',
      ],
      emotionVariants: {
        EmotionalTone.huzur: 'Kutsal an - derin baglanti',
        EmotionalTone.korku: 'Karanlik rituel - tehlike',
        EmotionalTone.merak: 'Anlam arayisi - ne anlama geliyor?',
        EmotionalTone.heyecan: 'Guc hissi - etki yaratma',
      },
      archetypes: ['Saman', 'Rahip', 'Basvuran'],
      relatedSymbols: ['ceremony', 'candle', 'altar', 'circle'],
      shadowAspect: 'Karanlik büyü, manipülasyon, kult',
      lightAspect: 'Kutsal eylem, dönüşüm, bağlantı',
    ),

    // ════════════════════════════════════════════════════════════════════════
    // OYUN & EGLENCE EYLEMLERI - 15+ Sembol
    // ════════════════════════════════════════════════════════════════════════
    DreamSymbolData(
      symbol: 'playing',
      symbolTr: 'Oynamak',
      emoji: '🎮',
      category: SymbolCategory.eylem,
      universalMeanings: [
        'Ic cocuk',
        'Yaraticilik ve spontanlık',
        'Stres atma',
        'Neseyle yasama',
        'Kural disi olma',
        'Kendi olma ozgurlugu',
      ],
      emotionVariants: {
        EmotionalTone.heyecan: 'Coskulu oyun - ic cocuk aktif',
        EmotionalTone.huzur: 'Sakin oyun - rahatlama',
        EmotionalTone.ozlem: 'Cocukluk - masumiyet',
        EmotionalTone.korku: 'Tehlikeli oyun - risk',
      },
      archetypes: ['Ic Cocuk', 'Oyunbaz', 'Yaratici'],
      relatedSymbols: ['child', 'toy', 'game', 'fun'],
      shadowAspect: 'Sorumsuzluk, kacis, olgunlasmama',
      lightAspect: 'Yaraticilik, neşe, spontanlık',
    ),

    DreamSymbolData(
      symbol: 'singing',
      symbolTr: 'Sarki Soylemek',
      emoji: '🎤',
      category: SymbolCategory.eylem,
      universalMeanings: [
        'Icsel ifade',
        'Ruh melodisi',
        'Duygusal dışavurum',
        'Toplulukla uyum',
        'Ozgun ses',
        'Kutlama',
      ],
      emotionVariants: {
        EmotionalTone.heyecan: 'Guçlu ses - ozgun ifade',
        EmotionalTone.huzur: 'Sakın melodi - ic harmoni',
        EmotionalTone.korku: 'Ses çıkmıyor - ifade engeli',
        EmotionalTone.ozlem: 'Eski şarkı - nostaljik anılar',
      },
      archetypes: ['Sair', 'Ifadeci', 'Ruh'],
      relatedSymbols: ['music', 'voice', 'stage', 'audience'],
      shadowAspect: 'Sessizlik, ifade edememe, uyumsuzluk',
      lightAspect: 'Ozgun ses, ruhsal ifade, uyum',
    ),

    DreamSymbolData(
      symbol: 'gambling',
      symbolTr: 'Kumar Oynamak',
      emoji: '🎰',
      category: SymbolCategory.eylem,
      universalMeanings: [
        'Risk alma',
        'Sans ve kader',
        'Kontrol ilusyonu',
        'Heyecan arayisi',
        'Kayıp korkusu',
        'Kolay kazanc fantezisi',
      ],
      emotionVariants: {
        EmotionalTone.heyecan: 'Buyuk kazanc - sans',
        EmotionalTone.korku: 'Her seyi kaybetme - risk',
        EmotionalTone.sucluluk: 'Bagimlilik - kontrol kaybı',
        EmotionalTone.merak: 'Sonuc ne olacak? - belirsizlik',
      },
      archetypes: ['Risk Alan', 'Sans Avcisi', 'Maceraci'],
      relatedSymbols: ['money', 'luck', 'cards', 'dice'],
      shadowAspect: 'Bagimlılık, kayıp, kontrolsuzluk',
      lightAspect: 'Hesaplı risk, sans, cesaret',
    ),

    // ════════════════════════════════════════════════════════════════════════
    // SIDDET & CATISMA EYLEMLERI - 15+ Sembol
    // ════════════════════════════════════════════════════════════════════════
    DreamSymbolData(
      symbol: 'killing',
      symbolTr: 'Oldurme',
      emoji: '⚔️',
      category: SymbolCategory.eylem,
      universalMeanings: [
        'Bir yonu bitirme',
        'Radikal dönusum',
        'Bastirilan ofke',
        'Guc ve kontrol',
        'Eski kimligin olumu',
        'Golge entegrasyonu',
      ],
      emotionVariants: {
        EmotionalTone.ofke: 'Siddet ile sonlandirma - yikici ofke',
        EmotionalTone.korku: 'Katil olmak - sucluluk',
        EmotionalTone.donukluk: 'Soğuk infaz - duygusuzluk',
        EmotionalTone.huzur: 'Gerekli son - baris',
      },
      archetypes: ['Savaşci', 'Dönüstürücü', 'Gölge'],
      relatedSymbols: ['death', 'weapon', 'enemy', 'blood'],
      shadowAspect: 'Yıkıcı dürtü, şiddet, suçluluk',
      lightAspect: 'Keskin karar, gereksiz olani bitirme, dönüsum',
    ),

    DreamSymbolData(
      symbol: 'stealing',
      symbolTr: 'Calmak',
      emoji: '🦹',
      category: SymbolCategory.eylem,
      universalMeanings: [
        'Eksiklik hissi',
        'Hakediş sorusu',
        'Kısayol arama',
        'Sinir ihlali',
        'Gizli arzular',
        'Guc alma',
      ],
      emotionVariants: {
        EmotionalTone.heyecan: 'Heyecanli hirsizlik - macera',
        EmotionalTone.sucluluk: 'Yakalanma korkusu - vicdan',
        EmotionalTone.korku: 'Cezalandırılma - sonuclar',
        EmotionalTone.merak: 'Ne çalıyorum? - gizli arzu',
      },
      archetypes: ['Hirsiz', 'Golge', 'Duzenbaz'],
      relatedSymbols: ['money', 'secret', 'crime', 'guilt'],
      shadowAspect: 'Dolandiricilik, etik ihlali, hak etmemek',
      lightAspect: 'Gucunu geri al, sinirları sorgula',
    ),

    DreamSymbolData(
      symbol: 'destroying',
      symbolTr: 'Yikmak',
      emoji: '💥',
      category: SymbolCategory.eylem,
      universalMeanings: [
        'Radikal son',
        'Yeniden yapılandirma oncesi yıkım',
        'Ofke disavurumu',
        'Eski kalıpları kirma',
        'Kaos ve yenilenme',
        'Ozgurlestirici yikim',
      ],
      emotionVariants: {
        EmotionalTone.ofke: 'Kontrolsuz yıkım - ofke patlaması',
        EmotionalTone.heyecan: 'Ozgurleştirici yıkım - kalibi kır',
        EmotionalTone.korku: 'Yikimin kurbanı - kontrol kaybı',
        EmotionalTone.sucluluk: 'Verdığin zarar - pismanlik',
      },
      archetypes: ['Yikici', 'Devrimci', 'Kaos'],
      relatedSymbols: ['fire', 'explosion', 'ruins', 'chaos'],
      shadowAspect: 'Kontrolsuz yikim, zarar, vicdan azabi',
      lightAspect: 'Temizlik, yeniden baslamc, ozgurluk',
    ),

    // ════════════════════════════════════════════════════════════════════════
    // TRANSFORMATIF EYLEMLER - 15+ Sembol
    // ════════════════════════════════════════════════════════════════════════
    DreamSymbolData(
      symbol: 'transforming',
      symbolTr: 'Dönüşmek',
      emoji: '🦋',
      category: SymbolCategory.eylem,
      universalMeanings: [
        'Metamorfoz',
        'Kimlik degisimi',
        'Evrim ve buyüme',
        'Simya',
        'Ruhsal dönüşüm',
        'Yeni benlik',
      ],
      emotionVariants: {
        EmotionalTone.heyecan: 'Mucizevi degişim - yeni ben',
        EmotionalTone.korku: 'Kim olacagim? - kimlik kaybı',
        EmotionalTone.merak: 'Neye dönüşüyorum? - potansiyel',
        EmotionalTone.huzur: 'Dogal evrim - kabul',
      },
      archetypes: ['Simyaci', 'Kelebek', 'Donusen'],
      relatedSymbols: ['butterfly', 'snake', 'rebirth', 'alchemy'],
      shadowAspect: 'Kimlik kaybı, zorla degisim',
      lightAspect: 'Evrim, buyume, yeni potansiyel',
    ),

    DreamSymbolData(
      symbol: 'ascending',
      symbolTr: 'Yukselmek',
      emoji: '⬆️',
      category: SymbolCategory.eylem,
      universalMeanings: [
        'Spiritüel yükseliş',
        'Başari ve ilerleme',
        'Bilinc genişlemesi',
        'Cennete yükselme',
        'Ego aşkınlığı',
        'Yüksek hedefler',
      ],
      emotionVariants: {
        EmotionalTone.heyecan: 'Zafer - hedefe ulasma',
        EmotionalTone.huzur: 'Spiritüel huzur - aydınlanma',
        EmotionalTone.korku: 'Dusme korkusu - yükseklik',
        EmotionalTone.merak: 'Yukarida ne var? - kesif',
      },
      archetypes: ['Kahraman', 'Mistik', 'Yukselen'],
      relatedSymbols: ['stairs', 'mountain', 'heaven', 'flying'],
      shadowAspect: 'Kibir, düşüş, temelsizlik',
      lightAspect: 'Ruhsal büyüme, başarı, aydınlanma',
    ),

    DreamSymbolData(
      symbol: 'descending',
      symbolTr: 'İnmek',
      emoji: '⬇️',
      category: SymbolCategory.eylem,
      universalMeanings: [
        'Bilinçaltına yolculuk',
        'Köklere dönüş',
        'Alçakgönüllülük',
        'Gölge çalışması',
        'Derinlere dalma',
        'Topraklama',
      ],
      emotionVariants: {
        EmotionalTone.merak: 'Keşfetme - derinliklere dalış',
        EmotionalTone.korku: 'Karanlığa inme - bilinmeyen',
        EmotionalTone.huzur: 'Kabul - köklere dönüş',
        EmotionalTone.donukluk: 'Düşüş - depresyon',
      },
      archetypes: ['Gölge Yolcusu', 'Dalgıç', 'Alçakgönüllü'],
      relatedSymbols: ['basement', 'cave', 'underground', 'depth'],
      shadowAspect: 'Depresyon, düşüş, karanlık',
      lightAspect: 'Gölge entegrasyonu, kökler, derinlik',
    ),

    DreamSymbolData(
      symbol: 'merging',
      symbolTr: 'Birleşmek',
      emoji: '🔄',
      category: SymbolCategory.eylem,
      universalMeanings: [
        'Birlik ve bütünleşme',
        'İlişki birleşmesi',
        'Karşıtların birliği',
        'Evrenle birleşme',
        'Ego sınırlarının çözülmesi',
        'Mistik deneyim',
      ],
      emotionVariants: {
        EmotionalTone.huzur: 'Uyum - derin birlik',
        EmotionalTone.heyecan: 'Birleşme - aşk',
        EmotionalTone.korku: 'Kimlik kaybı - erime',
        EmotionalTone.merak: 'Kiminle/neyle? - bütünleşme',
      },
      archetypes: ['Birleşik Benlik', 'Çift', 'Bütün'],
      relatedSymbols: ['union', 'marriage', 'wholeness', 'yin-yang'],
      shadowAspect: 'Kimlik kaybı, bağımlılık, erime',
      lightAspect: 'Bütünleşme, birlik, kutsal evlilik',
    ),

    DreamSymbolData(
      symbol: 'waking_up',
      symbolTr: 'Uyanmak',
      emoji: '👁️',
      category: SymbolCategory.eylem,
      universalMeanings: [
        'Farkındalık',
        'Yanılsamadan çıkış',
        'Yeni başlangıç',
        'Lucid rüya',
        'Aydınlanma',
        'Gerçeği görme',
      ],
      emotionVariants: {
        EmotionalTone.heyecan: 'Yeni farkındalık - aydınlanma',
        EmotionalTone.korku: 'Kabusa uyanmak - zor gerçek',
        EmotionalTone.huzur: 'Huzurlu uyanış - yeni gün',
        EmotionalTone.merak: 'Rüya içinde uyanmak - lucid',
      },
      archetypes: ['Uyanık', 'Görücü', 'Aydınlanmış'],
      relatedSymbols: ['light', 'dawn', 'awareness', 'truth'],
      shadowAspect: 'Zor gerçekler, hayal kırıklığı',
      lightAspect: 'Farkındalık, aydınlanma, yeni başlangıç',
    ),
  ];
}
