/// MEGA Dream Symbols Database Part 12 - Actions & Activities
/// Eylemler, Aktiviteler, Hareketler
library;

import '../models/dream_interpretation_models.dart';

/// Part 12: Eylemler ve Aktiviteler - 100+ Sembol
class MegaDreamSymbolsPart12 {
  static const List<DreamSymbolData> symbols = [
    // ════════════════════════════════════════════════════════════════════════
    // HAREKET VE ULASIM - 30+ Sembol
    // ════════════════════════════════════════════════════════════════════════
    DreamSymbolData(
      symbol: 'jumping',
      symbolTr: 'Ziplamak',
      emoji: '🦘',
      category: SymbolCategory.eylem,
      universalMeanings: [
        'Risk almak',
        'Engelleri asmak',
        'Heyecan',
        'Ileriye siçrama',
        'Enerji patlamasi',
        'Karar ani',
      ],
      emotionVariants: {
        EmotionalTone.heyecan: 'Adrenalin',
        EmotionalTone.korku: 'Düsme korkusu',
        EmotionalTone.huzur: 'Hafiflik hissi',
        EmotionalTone.merak: 'Nereye inecegim?',
      },
      archetypes: ['Cesur', 'Atilgan', 'Ozgur'],
      relatedSymbols: ['flying', 'risk', 'leap', 'freedom'],
      shadowAspect: 'Dusuncesiz hareket',
      lightAspect: 'Cesaret, ilerleme',
    ),

    DreamSymbolData(
      symbol: 'crawling',
      symbolTr: 'Surünmek',
      emoji: '🐛',
      category: SymbolCategory.eylem,
      universalMeanings: [
        'Alcakgonulluluk',
        'Yavas ilerleme',
        'Bebek donemi',
        'Zorluk',
        'Gizlilik',
        'Toprakla temas',
      ],
      emotionVariants: {
        EmotionalTone.korku: 'Yakalanmak',
        EmotionalTone.huzur: 'Toprakla birlik',
        EmotionalTone.sucluluk: 'Alik gonulluluk',
        EmotionalTone.merak: 'Gizli geçis',
      },
      archetypes: ['Alcak', 'Bebek', 'Gizli'],
      relatedSymbols: ['baby', 'humility', 'hiding', 'slow'],
      shadowAspect: 'Ezilmislik, kuculme',
      lightAspect: 'Sabir, temkinli ilerleme',
    ),

    DreamSymbolData(
      symbol: 'spinning',
      symbolTr: 'Dönmek',
      emoji: '🌀',
      category: SymbolCategory.eylem,
      universalMeanings: [
        'Bas dönmesi',
        'Kontrol kaybi',
        'Trans hali',
        'Spiritüel döngü',
        'Enerji akisi',
        'Kafasi karisiklik',
      ],
      emotionVariants: {
        EmotionalTone.korku: 'Kontrol kaybi',
        EmotionalTone.heyecan: 'Sarhos edici his',
        EmotionalTone.donukluk: 'Nerdeyim?',
        EmotionalTone.huzur: 'Sufi donusu',
      },
      archetypes: ['Saman', 'Dervis', 'Girdap'],
      relatedSymbols: ['vortex', 'confusion', 'dance', 'trance'],
      shadowAspect: 'Kaybolma, delilik',
      lightAspect: 'Spiritüel uyanis',
    ),

    DreamSymbolData(
      symbol: 'floating',
      symbolTr: 'Süzülmek',
      emoji: '🎈',
      category: SymbolCategory.eylem,
      universalMeanings: [
        'Agirsizlik',
        'Birakma',
        'Rüya bilinci',
        'Özgürlük',
        'Bedenle baglanti gevsetme',
        'Havada asili kalma',
      ],
      emotionVariants: {
        EmotionalTone.huzur: 'Tam birakis',
        EmotionalTone.korku: 'Kontrolsüzlük',
        EmotionalTone.merak: 'Nasil yapiyorum?',
        EmotionalTone.heyecan: 'Havada olma',
      },
      archetypes: ['Ruh', 'Özgür', 'Göksel'],
      relatedSymbols: ['flying', 'water', 'dream', 'spirit'],
      shadowAspect: 'Gerçeklikten kopus',
      lightAspect: 'Ruhsal hafiflik',
    ),

    DreamSymbolData(
      symbol: 'sinking',
      symbolTr: 'Batmak',
      emoji: '⚓',
      category: SymbolCategory.eylem,
      universalMeanings: [
        'Duygusal agirlik',
        'Depresyon',
        'Bilincdisina inis',
        'Basarisizlik hissi',
        'Yenilgi',
        'Kontrol kaybi',
      ],
      emotionVariants: {
        EmotionalTone.korku: 'Bogulma korkusu',
        EmotionalTone.donukluk: 'Ümitsizlik',
        EmotionalTone.huzur: 'Birakis',
        EmotionalTone.merak: 'Derinlerde ne var?',
      },
      archetypes: ['Batan Gemi', 'Yenilen', 'Derinlik'],
      relatedSymbols: ['water', 'drowning', 'depression', 'weight'],
      shadowAspect: 'Depresyon, yenilgi',
      lightAspect: 'Bilincdisina dalma',
    ),

    DreamSymbolData(
      symbol: 'sliding',
      symbolTr: 'Kaymak',
      emoji: '🛝',
      category: SymbolCategory.eylem,
      universalMeanings: [
        'Kolaylik',
        'Kontrol azalmasi',
        'Cocukluk nesesi',
        'Hiz kazanma',
        'Dusus tehlikesi',
        'Akisa birakma',
      ],
      emotionVariants: {
        EmotionalTone.heyecan: 'Eglencelii',
        EmotionalTone.korku: 'Kayip düsme',
        EmotionalTone.huzur: 'Rahat akis',
        EmotionalTone.merak: 'Nereye gidiyorum?',
      },
      archetypes: ['Cocuk', 'Kayan', 'Akis'],
      relatedSymbols: ['falling', 'ice', 'playground', 'speed'],
      shadowAspect: 'Kontrolsüz düsüs',
      lightAspect: 'Hayatin akisina güvenmek',
    ),

    DreamSymbolData(
      symbol: 'racing',
      symbolTr: 'Yaris',
      emoji: '🏎️',
      category: SymbolCategory.eylem,
      universalMeanings: [
        'Rekabet',
        'Basari arzusu',
        'Zamana karsi',
        'Hız ve adrenalin',
        'Karsılastirma',
        'Hedef odaklilik',
      ],
      emotionVariants: {
        EmotionalTone.heyecan: 'Yarış heyecani',
        EmotionalTone.korku: 'Kaybetme',
        EmotionalTone.ofke: 'Rekabet öfkesi',
        EmotionalTone.huzur: 'Kazanmanin keyfi',
      },
      archetypes: ['Yarışci', 'Kahraman', 'Rekabetçi'],
      relatedSymbols: ['competition', 'speed', 'winning', 'car'],
      shadowAspect: 'Asiiri rekabet, tukenme',
      lightAspect: 'Motivasyon, başari',
    ),

    DreamSymbolData(
      symbol: 'chasing',
      symbolTr: 'Kovalamak',
      emoji: '🏃',
      category: SymbolCategory.eylem,
      universalMeanings: [
        'Takip edilme korkusu',
        'Kacillan sey',
        'Hedef pesinde kosma',
        'Baskilanmis duygular',
        'Stres ve kaygi',
        'Yakalanmak',
      ],
      emotionVariants: {
        EmotionalTone.korku: 'Dehset verici takip',
        EmotionalTone.heyecan: 'Heyecanli kovalama',
        EmotionalTone.merak: 'Kim/ne kovaliyor?',
        EmotionalTone.ofke: 'Yakalama arzusu',
      },
      archetypes: ['Avci', 'Av', 'Kaçak'],
      relatedSymbols: ['running', 'fear', 'pursuit', 'escape'],
      shadowAspect: 'Kacilamayan korkular',
      lightAspect: 'Hedefe odaklanma',
    ),

    DreamSymbolData(
      symbol: 'escaping',
      symbolTr: 'Kaçmak',
      emoji: '🚪',
      category: SymbolCategory.eylem,
      universalMeanings: [
        'Özgürlük arayisi',
        'Tehlikeden kurtulma',
        'Sorumluluktan kacis',
        'Korkudan uzaklasma',
        'Tutssakliktan cikis',
        'Yeni baslangic',
      ],
      emotionVariants: {
        EmotionalTone.korku: 'Yakalanma korkusu',
        EmotionalTone.heyecan: 'Özgürlük yakinda',
        EmotionalTone.huzur: 'Kurtulus',
        EmotionalTone.sucluluk: 'Kaçis sucu',
      },
      archetypes: ['Kacak', 'Özgür', 'Baglari Kiran'],
      relatedSymbols: ['prison', 'freedom', 'door', 'running'],
      shadowAspect: 'Yuzlesmeden kacis',
      lightAspect: 'Özgürlük, kurtuluş',
    ),

    DreamSymbolData(
      symbol: 'carrying',
      symbolTr: 'Tasimak',
      emoji: '🎒',
      category: SymbolCategory.eylem,
      universalMeanings: [
        'Sorumluluk',
        'Yük',
        'Baskalarini destekleme',
        'Gecmis bagaj',
        'Görev',
        'Güç ve dayaniklilik',
      ],
      emotionVariants: {
        EmotionalTone.korku: 'Agir yuk',
        EmotionalTone.huzur: 'Taşiyabiliyorum',
        EmotionalTone.sucluluk: 'Baskasinin yuku',
        EmotionalTone.ofke: 'Neden ben?',
      },
      archetypes: ['Atlas', 'Tasıyicı', 'Sorumlu'],
      relatedSymbols: ['bag', 'burden', 'responsibility', 'weight'],
      shadowAspect: 'Ezici yük',
      lightAspect: 'Güçlü destek',
    ),

    DreamSymbolData(
      symbol: 'pushing',
      symbolTr: 'Itmek',
      emoji: '🤚',
      category: SymbolCategory.eylem,
      universalMeanings: [
        'Sinir koyma',
        'Uzaklastirma',
        'Güc kullanma',
        'Degisim cabbasi',
        'Itici güç',
        'Red',
      ],
      emotionVariants: {
        EmotionalTone.ofke: 'Saldirgan itme',
        EmotionalTone.huzur: 'Sinir belirleme',
        EmotionalTone.korku: 'Uzak tutma',
        EmotionalTone.merak: 'Ne itiiyorum?',
      },
      archetypes: ['Sinir Bekçisi', 'Güçlü', 'Direnen'],
      relatedSymbols: ['force', 'boundary', 'rejection', 'effort'],
      shadowAspect: 'Siddet, reddetme',
      lightAspect: 'Saglikli sinirlar',
    ),

    DreamSymbolData(
      symbol: 'pulling',
      symbolTr: 'Çekmek',
      emoji: '🧲',
      category: SymbolCategory.eylem,
      universalMeanings: [
        'Çekim gücü',
        'Yakinlastirma',
        'Arzu',
        'Mücadele',
        'Baglanti',
        'Kontrol',
      ],
      emotionVariants: {
        EmotionalTone.ozlem: 'Kendine çekme',
        EmotionalTone.korku: 'Çekilme',
        EmotionalTone.heyecan: 'Yakinlaşma',
        EmotionalTone.merak: 'Ne çekiyor?',
      },
      archetypes: ['Miknatis', 'Çekici', 'Baglayanı'],
      relatedSymbols: ['attraction', 'desire', 'connection', 'magnet'],
      shadowAspect: 'Manipülasyon, zorla alma',
      lightAspect: 'Dogal ceekim, baglanti',
    ),

    DreamSymbolData(
      symbol: 'breaking',
      symbolTr: 'Kirmak',
      emoji: '💔',
      category: SymbolCategory.eylem,
      universalMeanings: [
        'Son verme',
        'Yikim',
        'Özgürlesme',
        'Kirilan kalp',
        'Eski kaliplari yikma',
        'Kayip',
      ],
      emotionVariants: {
        EmotionalTone.korku: 'Geri dönüsüz kayip',
        EmotionalTone.ofke: 'Yikici öfke',
        EmotionalTone.huzur: 'Zincirlerden kurtulus',
        EmotionalTone.sucluluk: 'Birseyi bozmak',
      },
      archetypes: ['Yikici', 'Özgürleştirici', 'Son'],
      relatedSymbols: ['destruction', 'freedom', 'end', 'glass'],
      shadowAspect: 'Yikim, kayip',
      lightAspect: 'Eski kaliplardan kurtulus',
    ),

    DreamSymbolData(
      symbol: 'building',
      symbolTr: 'Inşa Etmek',
      emoji: '🏗️',
      category: SymbolCategory.eylem,
      universalMeanings: [
        'Yaraticilik',
        'Gelecek insasi',
        'Planlama',
        'Emek',
        'Yeni projeler',
        'Kalici eser',
      ],
      emotionVariants: {
        EmotionalTone.heyecan: 'Yaratma heyecani',
        EmotionalTone.huzur: 'İnşa tatmini',
        EmotionalTone.korku: 'Yikilma korkusu',
        EmotionalTone.merak: 'Ne yapiyorum?',
      },
      archetypes: ['Yaratici', 'Mimar', 'İnşaaci'],
      relatedSymbols: ['creation', 'house', 'work', 'future'],
      shadowAspect: 'Bitmeyyen proje',
      lightAspect: 'Kalici deger yaratma',
    ),

    DreamSymbolData(
      symbol: 'fixing',
      symbolTr: 'Tamir Etmek',
      emoji: '🔧',
      category: SymbolCategory.eylem,
      universalMeanings: [
        'Onarma',
        'Problem çözme',
        'Ilişki tamiri',
        'Yenilenme',
        'Beceri',
        'Düzeltme',
      ],
      emotionVariants: {
        EmotionalTone.huzur: 'Cöozüm bulma',
        EmotionalTone.heyecan: 'Basari hissi',
        EmotionalTone.korku: 'Tamir edilemez',
        EmotionalTone.merak: 'Nasil çalisiyor?',
      },
      archetypes: ['Tamirci', 'Şifaci', 'Problem Çözücü'],
      relatedSymbols: ['repair', 'tools', 'healing', 'solution'],
      shadowAspect: 'Tamir edilemeyen',
      lightAspect: 'Sorun çözme becerisi',
    ),

    // ════════════════════════════════════════════════════════════════════════
    // SOSYAL EYLEMLER - 30+ Sembol
    // ════════════════════════════════════════════════════════════════════════
    DreamSymbolData(
      symbol: 'talking',
      symbolTr: 'Konusmak',
      emoji: '💬',
      category: SymbolCategory.eylem,
      universalMeanings: [
        'İletişim',
        'İfade',
        'Paylaşim',
        'Bağlanti kurma',
        'Açiklama',
        'Diyalog',
      ],
      emotionVariants: {
        EmotionalTone.huzur: 'Rahat sohbet',
        EmotionalTone.korku: 'Soyleyememe',
        EmotionalTone.heyecan: 'Önemli konusma',
        EmotionalTone.merak: 'Ne diyorlar?',
      },
      archetypes: ['İletisimci', 'Mesajci', 'Baglayi'],
      relatedSymbols: ['voice', 'communication', 'words', 'meeting'],
      shadowAspect: 'Bos konusma, dedikodu',
      lightAspect: 'Etkili iletişim',
    ),

    DreamSymbolData(
      symbol: 'shouting',
      symbolTr: 'Bagirmak',
      emoji: '📣',
      category: SymbolCategory.eylem,
      universalMeanings: [
        'Duyulmak isteme',
        'Öfke ifadesi',
        'Acil uyari',
        'Hayal kirikligi',
        'Güçlü mesaj',
        'Bastiirilmis duygular',
      ],
      emotionVariants: {
        EmotionalTone.ofke: 'Patlamak',
        EmotionalTone.korku: 'Yardım çagirmak',
        EmotionalTone.heyecan: 'Zafer çigligi',
        EmotionalTone.donukluk: 'Ses çikarmaama',
      },
      archetypes: ['Uyarici', 'Öfkeli', 'Protestocu'],
      relatedSymbols: ['voice', 'anger', 'warning', 'frustration'],
      shadowAspect: 'Kontrolsüz öfke',
      lightAspect: 'Güçlü ifade',
    ),

    DreamSymbolData(
      symbol: 'whispering',
      symbolTr: 'Fisildamak',
      emoji: '🤫',
      category: SymbolCategory.eylem,
      universalMeanings: [
        'Gizlilik',
        'Yakinlik',
        'Sirlar',
        'Özel bilgi',
        'Gizli mesaj',
        'Dikkat cekici',
      ],
      emotionVariants: {
        EmotionalTone.merak: 'Ne söyleniyor?',
        EmotionalTone.korku: 'Dedikodu',
        EmotionalTone.huzur: 'Yakin paylasim',
        EmotionalTone.sucluluk: 'Gizli sir',
      },
      archetypes: ['Gizli', 'Yakin', 'Sir Saklayan'],
      relatedSymbols: ['secret', 'intimacy', 'gossip', 'silence'],
      shadowAspect: 'Dedikodu, gizlilik',
      lightAspect: 'Özel bag, güven',
    ),

    DreamSymbolData(
      symbol: 'laughing',
      symbolTr: 'Gülmek',
      emoji: '😂',
      category: SymbolCategory.eylem,
      universalMeanings: [
        'Neşe',
        'Rahatlamak',
        'Birlik',
        'Alay',
        'Sifa',
        'Özgürlük',
      ],
      emotionVariants: {
        EmotionalTone.huzur: 'Gercek neşe',
        EmotionalTone.korku: 'Alay konusu',
        EmotionalTone.heyecan: 'Sarsilmak',
        EmotionalTone.sucluluk: 'Uygunsuz gülme',
      },
      archetypes: ['Soytari', 'Neşeli', 'Sifaci'],
      relatedSymbols: ['joy', 'humor', 'friends', 'release'],
      shadowAspect: 'Alay, maskeli aci',
      lightAspect: 'Gercek mutluluk',
    ),

    DreamSymbolData(
      symbol: 'crying',
      symbolTr: 'Aglamak',
      emoji: '😢',
      category: SymbolCategory.eylem,
      universalMeanings: [
        'Duygusal bosalma',
        'Üzüntü',
        'Temizlenme',
        'Yardiim çagirma',
        'Kayip yasi',
        'Rahatlama',
      ],
      emotionVariants: {
        EmotionalTone.ozlem: 'Derin özlem',
        EmotionalTone.huzur: 'Rahatlatici aglama',
        EmotionalTone.korku: 'Kontrolsüz agllama',
        EmotionalTone.sucluluk: 'Pisman gözyaslari',
      },
      archetypes: ['Yas Tutan', 'Arinaan', 'Açilan'],
      relatedSymbols: ['tears', 'sadness', 'release', 'grief'],
      shadowAspect: 'Ümitsizlik',
      lightAspect: 'Duygusal arinma',
    ),

    DreamSymbolData(
      symbol: 'hugging',
      symbolTr: 'Sarilmak',
      emoji: '🤗',
      category: SymbolCategory.eylem,
      universalMeanings: [
        'Sevgi',
        'Kabul',
        'Güven',
        'Birlesme',
        'Destek',
        'Koruma',
      ],
      emotionVariants: {
        EmotionalTone.huzur: 'Sicak kabul',
        EmotionalTone.ozlem: 'Sarılma ihtiyacı',
        EmotionalTone.heyecan: 'Kavuşma',
        EmotionalTone.korku: 'Asiri yakinlik',
      },
      archetypes: ['Anne', 'Koruyucu', 'Sevgili'],
      relatedSymbols: ['love', 'warmth', 'connection', 'comfort'],
      shadowAspect: 'Yapisiklik',
      lightAspect: 'Kosulsuz sevgi',
    ),

    DreamSymbolData(
      symbol: 'kissing',
      symbolTr: 'Öpmek',
      emoji: '💋',
      category: SymbolCategory.eylem,
      universalMeanings: [
        'Romantik bağ',
        'Onay',
        'Birleşme',
        'Enerji alışverişi',
        'İhanet (Judas)',
        'Sevgi ifadesi',
      ],
      emotionVariants: {
        EmotionalTone.heyecan: 'Romantik heyecan',
        EmotionalTone.huzur: 'Sevgi dolu öpucuk',
        EmotionalTone.korku: 'Istenmeyen yakinlik',
        EmotionalTone.sucluluk: 'Yasak öpücük',
      },
      archetypes: ['Sevgili', 'Birleşik', 'Hain'],
      relatedSymbols: ['love', 'romance', 'intimacy', 'betrayal'],
      shadowAspect: 'Aldatma, ihanet',
      lightAspect: 'Gercek sevgi',
    ),

    DreamSymbolData(
      symbol: 'fighting_physical',
      symbolTr: 'Dövüşmek',
      emoji: '🥊',
      category: SymbolCategory.eylem,
      universalMeanings: [
        'İç çatışma',
        'Savunma',
        'Öfke ifadesi',
        'Güc mücadelesi',
        'Sinirları koruma',
        'Hayatta kalma',
      ],
      emotionVariants: {
        EmotionalTone.ofke: 'Siddetli öfke',
        EmotionalTone.korku: 'Hayatta kalma',
        EmotionalTone.heyecan: 'Adrenalinn',
        EmotionalTone.sucluluk: 'Siddet kullanma',
      },
      archetypes: ['Savasci', 'Savunucu', 'Öfkeli'],
      relatedSymbols: ['anger', 'conflict', 'power', 'enemy'],
      shadowAspect: 'Kontrolsüz siddet',
      lightAspect: 'Degerleri savunma',
    ),

    DreamSymbolData(
      symbol: 'stealing',
      symbolTr: 'Çalmak',
      emoji: '🦹',
      category: SymbolCategory.eylem,
      universalMeanings: [
        'Eksiklik hissi',
        'Gizli arzular',
        'Yetersizlik',
        'Etik siinama',
        'Hak edilmemis kazanc',
        'Kaybetme korkusu',
      ],
      emotionVariants: {
        EmotionalTone.sucluluk: 'Yanlis yapmak',
        EmotionalTone.korku: 'Yakalanma',
        EmotionalTone.heyecan: 'Yasak heyecan',
        EmotionalTone.merak: 'Ne çaliyorum?',
      },
      archetypes: ['Hirsiz', 'Gölge', 'Trickster'],
      relatedSymbols: ['guilt', 'lack', 'secret', 'desire'],
      shadowAspect: 'Düürüstlük eksikligi',
      lightAspect: 'Eksikliklerin farkindaaligi',
    ),

    DreamSymbolData(
      symbol: 'giving',
      symbolTr: 'Vermek',
      emoji: '🎁',
      category: SymbolCategory.eylem,
      universalMeanings: [
        'Cömertlik',
        'Paylaşim',
        'Sevgi ifadesi',
        'Birakma',
        'Yardim',
        'Enerji transferi',
      ],
      emotionVariants: {
        EmotionalTone.huzur: 'Vermenin keyfi',
        EmotionalTone.ozlem: 'Birseey birakma',
        EmotionalTone.sucluluk: 'Telafi',
        EmotionalTone.heyecan: 'Surpriz yapma',
      },
      archetypes: ['Comert', 'Yardımci', 'Sevgi Dolu'],
      relatedSymbols: ['gift', 'generosity', 'love', 'release'],
      shadowAspect: 'Kendini tüketme',
      lightAspect: 'Şartsiz verme',
    ),

    DreamSymbolData(
      symbol: 'receiving',
      symbolTr: 'Almak',
      emoji: '🤲',
      category: SymbolCategory.eylem,
      universalMeanings: [
        'Kabul',
        'Açıklık',
        'Hak etme',
        'Bolluk',
        'Şükran',
        'Alicilik',
      ],
      emotionVariants: {
        EmotionalTone.huzur: 'Kabul etme huzuru',
        EmotionalTone.heyecan: 'Hediye almak',
        EmotionalTone.sucluluk: 'Hak etmeme',
        EmotionalTone.merak: 'Ne aliyorum?',
      },
      archetypes: ['Alici', 'Açik', 'Kabul Eden'],
      relatedSymbols: ['gift', 'abundance', 'acceptance', 'worthy'],
      shadowAspect: 'Bencilik, almak isteme',
      lightAspect: 'Açik yüreklilik',
    ),

    DreamSymbolData(
      symbol: 'teaching',
      symbolTr: 'Öğretmek',
      emoji: '👨‍🏫',
      category: SymbolCategory.eylem,
      universalMeanings: [
        'Bilgi paylaşimi',
        'Rehberlik',
        'Sorumluluk',
        'Miras birakmak',
        'Öğrenerek öğretmek',
        'Otorite',
      ],
      emotionVariants: {
        EmotionalTone.huzur: 'Paylaşimin keyfi',
        EmotionalTone.heyecan: 'Öğretme heyecani',
        EmotionalTone.korku: 'Yetersizlik',
        EmotionalTone.sucluluk: 'Yanliş öğretme',
      },
      archetypes: ['Öğretmen', 'Bilge', 'Rehber'],
      relatedSymbols: ['school', 'wisdom', 'knowledge', 'guidance'],
      shadowAspect: 'Bilgiclik, kibirlilik',
      lightAspect: 'Bilgi aktarimi',
    ),

    DreamSymbolData(
      symbol: 'learning',
      symbolTr: 'Öğrenmek',
      emoji: '📚',
      category: SymbolCategory.eylem,
      universalMeanings: [
        'Gelisim',
        'Açiklik',
        'Yeni beceriler',
        'Merak',
        'Yasam dersleri',
        'Donuşum',
      ],
      emotionVariants: {
        EmotionalTone.heyecan: 'Keşif heyecani',
        EmotionalTone.korku: 'Ögrenememe',
        EmotionalTone.huzur: 'Öğrenme keyfi',
        EmotionalTone.merak: 'Daha fazla!',
      },
      archetypes: ['Öğrenci', 'Arayişci', 'Çaylak'],
      relatedSymbols: ['book', 'school', 'growth', 'curiosity'],
      shadowAspect: 'Bilmemek utanci',
      lightAspect: 'Sürekli gelisim',
    ),

    DreamSymbolData(
      symbol: 'healing',
      symbolTr: 'İyileştirmek',
      emoji: '💊',
      category: SymbolCategory.eylem,
      universalMeanings: [
        'Şifa',
        'Onarma',
        'Dönüşüm',
        'Bakım',
        'Yenilenme',
        'Sevgi',
      ],
      emotionVariants: {
        EmotionalTone.huzur: 'Şifa enerjisi',
        EmotionalTone.heyecan: 'İyileşme belirtisi',
        EmotionalTone.ozlem: 'Şifa arayışı',
        EmotionalTone.merak: 'Nasıl iyileşir?',
      },
      archetypes: ['Şifacı', 'Doktor', 'Saman'],
      relatedSymbols: ['medicine', 'doctor', 'recovery', 'care'],
      shadowAspect: 'Sahte şifa',
      lightAspect: 'Gerçek iyileşme',
    ),

    DreamSymbolData(
      symbol: 'protecting',
      symbolTr: 'Korumak',
      emoji: '🛡️',
      category: SymbolCategory.eylem,
      universalMeanings: [
        'Savunma',
        'Güvenlik',
        'Sorumluluk',
        'Sevgi',
        'Sınır koyma',
        'Bekçilik',
      ],
      emotionVariants: {
        EmotionalTone.huzur: 'Güvende tutma',
        EmotionalTone.korku: 'Tehdit algısı',
        EmotionalTone.ofke: 'Savunmaci öfke',
        EmotionalTone.sucluluk: 'Koruyamama',
      },
      archetypes: ['Koruyucu', 'Bekci', 'Kahraman'],
      relatedSymbols: ['shield', 'safety', 'guardian', 'family'],
      shadowAspect: 'Aşırı koruyuculuk',
      lightAspect: 'Sağlıklı koruma',
    ),

    // ════════════════════════════════════════════════════════════════════════
    // YARATICI EYLEMLER - 25+ Sembol
    // ════════════════════════════════════════════════════════════════════════
    DreamSymbolData(
      symbol: 'painting',
      symbolTr: 'Resim Yapmak',
      emoji: '🎨',
      category: SymbolCategory.eylem,
      universalMeanings: [
        'Yaraticilik',
        'İfade',
        'Renklerle konuşma',
        'İç dünya',
        'Güzellik yaratma',
        'Duygulari görselleştirme',
      ],
      emotionVariants: {
        EmotionalTone.huzur: 'Yaratma keyfi',
        EmotionalTone.heyecan: 'Sanatsal ilham',
        EmotionalTone.korku: 'Yetenek yetersizliği',
        EmotionalTone.merak: 'Ne ciziyorum?',
      },
      archetypes: ['Sanatçı', 'Yaratıcı', 'Görsel Şair'],
      relatedSymbols: ['art', 'colors', 'creativity', 'expression'],
      shadowAspect: 'Mükemmeliyetcilik',
      lightAspect: 'Saf yaratıcılık',
    ),

    DreamSymbolData(
      symbol: 'singing',
      symbolTr: 'Şarkı Söylemek',
      emoji: '🎤',
      category: SymbolCategory.eylem,
      universalMeanings: [
        'Ses ile ifade',
        'Duygusal özgürlük',
        'Iç melodiler',
        'Birleştirici güç',
        'Spiritüel bağ',
        'Şifa sesi',
      ],
      emotionVariants: {
        EmotionalTone.huzur: 'Içten gelen sarki',
        EmotionalTone.heyecan: 'Sahne heyecani',
        EmotionalTone.korku: 'Sesini kaybetme',
        EmotionalTone.ozlem: 'Özgürce söyleme',
      },
      archetypes: ['Ozan', 'Şarkıcı', 'Ruh'],
      relatedSymbols: ['voice', 'music', 'expression', 'freedom'],
      shadowAspect: 'Sessizlik, söyleyememe',
      lightAspect: 'Özgür ifade',
    ),

    DreamSymbolData(
      symbol: 'dancing',
      symbolTr: 'Dans Etmek',
      emoji: '💃',
      category: SymbolCategory.eylem,
      universalMeanings: [
        'Bedensel ifade',
        'Ritim ve uyum',
        'Kutlama',
        'Özgürlük',
        'Enerji akışı',
        'Yaşam sevinci',
      ],
      emotionVariants: {
        EmotionalTone.heyecan: 'Coşku ve enerji',
        EmotionalTone.huzur: 'Bedende olmak',
        EmotionalTone.korku: 'Performans kaygısı',
        EmotionalTone.ozlem: 'Özgürce hareket',
      },
      archetypes: ['Dansçı', 'Özgür Ruh', 'Kutlayan'],
      relatedSymbols: ['music', 'body', 'celebration', 'freedom'],
      shadowAspect: 'Utanç, hareket edememe',
      lightAspect: 'Tam bedensel ifade',
    ),

    DreamSymbolData(
      symbol: 'writing',
      symbolTr: 'Yazmak',
      emoji: '✍️',
      category: SymbolCategory.eylem,
      universalMeanings: [
        'Düşünceleri kaydetme',
        'Yaratıcılık',
        'Ifade',
        'Kalıcı iz',
        'İletişim',
        'Hikaye anlatımı',
      ],
      emotionVariants: {
        EmotionalTone.huzur: 'Yazma akışı',
        EmotionalTone.heyecan: 'İlham anı',
        EmotionalTone.korku: 'Yazamama',
        EmotionalTone.merak: 'Ne yazıyorum?',
      },
      archetypes: ['Yazar', 'Hikaye Anlatıcı', 'Şair'],
      relatedSymbols: ['pen', 'book', 'words', 'story'],
      shadowAspect: 'Blokaj, ifade edememe',
      lightAspect: 'Fiikirleri somutlaştırma',
    ),

    DreamSymbolData(
      symbol: 'cooking',
      symbolTr: 'Yemek Pişirmek',
      emoji: '👨‍🍳',
      category: SymbolCategory.eylem,
      universalMeanings: [
        'Dönüşüm',
        'Besleme',
        'Yaratıcılık',
        'Ev yapımı sevgi',
        'Simya',
        'Hazırlık',
      ],
      emotionVariants: {
        EmotionalTone.huzur: 'Mutfak keyfi',
        EmotionalTone.heyecan: 'Yeni tarif',
        EmotionalTone.korku: 'Yakma, bozma',
        EmotionalTone.merak: 'Nasıl olacak?',
      },
      archetypes: ['Anne', 'Simyacı', 'Yaratıcı'],
      relatedSymbols: ['food', 'kitchen', 'transformation', 'nurture'],
      shadowAspect: 'Yanık yemek, başarısızlık',
      lightAspect: 'Dönüştürücü sevgi',
    ),

    DreamSymbolData(
      symbol: 'gardening',
      symbolTr: 'Bahçe İşleri',
      emoji: '🌱',
      category: SymbolCategory.eylem,
      universalMeanings: [
        'Büyütme',
        'Sabır',
        'Doğa ile bağ',
        'Yaşam döngüsü',
        'Bakım',
        'Gelecek hazırlığı',
      ],
      emotionVariants: {
        EmotionalTone.huzur: 'Toprakla temas',
        EmotionalTone.heyecan: 'Filiz görme',
        EmotionalTone.ozlem: 'Bahçe özlemi',
        EmotionalTone.merak: 'Ne yetişecek?',
      },
      archetypes: ['Bahçıvan', 'Büyütücü', 'Toprak Ana'],
      relatedSymbols: ['plant', 'growth', 'nature', 'patience'],
      shadowAspect: 'Kuruyan bitkiler',
      lightAspect: 'Yaşam büyütme',
    ),

    DreamSymbolData(
      symbol: 'sewing',
      symbolTr: 'Dikiş Dikmek',
      emoji: '🧵',
      category: SymbolCategory.eylem,
      universalMeanings: [
        'Birleştirme',
        'Onarma',
        'Yaratma',
        'Detaylara dikkat',
        'Sabır',
        'Geleneksel beceri',
      ],
      emotionVariants: {
        EmotionalTone.huzur: 'Dikişin ritmi',
        EmotionalTone.merak: 'Ne dikiyorum?',
        EmotionalTone.korku: 'İğne batması',
        EmotionalTone.ozlem: 'El işi geleneği',
      },
      archetypes: ['Dokumacı', 'Onarıcı', 'Kader'],
      relatedSymbols: ['thread', 'needle', 'repair', 'creation'],
      shadowAspect: 'Yırtık, tamir edilemez',
      lightAspect: 'Kaderı dokumak',
    ),

    DreamSymbolData(
      symbol: 'sculpting',
      symbolTr: 'Heykel Yapmak',
      emoji: '🗿',
      category: SymbolCategory.eylem,
      universalMeanings: [
        'Form verme',
        'Kalıcı eser',
        'İç vizyonu dışa vurma',
        'Sabır ve ustalık',
        'Fazlalıkları atma',
        'Gerçeği ortaya çıkarma',
      ],
      emotionVariants: {
        EmotionalTone.huzur: 'Form vermenin keyfi',
        EmotionalTone.heyecan: 'Yaratma gücü',
        EmotionalTone.merak: 'İçinde ne var?',
        EmotionalTone.korku: 'Kırma, hata',
      },
      archetypes: ['Sanatçı', 'Yaratıcı Tanrı', 'Usta'],
      relatedSymbols: ['stone', 'art', 'creation', 'form'],
      shadowAspect: 'Kırık heykel, başarısızlık',
      lightAspect: 'Formun içinden özü çıkarma',
    ),

    DreamSymbolData(
      symbol: 'playing_instrument',
      symbolTr: 'Enstrüman Çalmak',
      emoji: '🎸',
      category: SymbolCategory.eylem,
      universalMeanings: [
        'Yaratıcı ifade',
        'Uyum ve ritim',
        'Bireysel yetenek',
        'Duygusal kanalização',
        'Pratik ve ustalık',
        'Evrensel dil',
      ],
      emotionVariants: {
        EmotionalTone.huzur: 'Müzikle birlik',
        EmotionalTone.heyecan: 'Performans',
        EmotionalTone.korku: 'Yanlış nota',
        EmotionalTone.ozlem: 'Çalma arzusu',
      },
      archetypes: ['Müzisyen', 'Ozan', 'Orfeus'],
      relatedSymbols: ['music', 'harmony', 'expression', 'practice'],
      shadowAspect: 'Ses çıkaramama',
      lightAspect: 'Müzikle ifade',
    ),

    DreamSymbolData(
      symbol: 'photographing',
      symbolTr: 'Fotoğraf Çekmek',
      emoji: '📸',
      category: SymbolCategory.eylem,
      universalMeanings: [
        'Anı yakalama',
        'Gözlem',
        'Perspektif',
        'Gerçekliği kaydetme',
        'Dikkat ve farkındalık',
        'Zamani dondurma',
      ],
      emotionVariants: {
        EmotionalTone.huzur: 'Anı yaşama',
        EmotionalTone.merak: 'Görsel keşif',
        EmotionalTone.ozlem: 'Geçmişi tutma',
        EmotionalTone.heyecan: 'Mükemmel kare',
      },
      archetypes: ['Gözlemci', 'Tanık', 'Belgeleyici'],
      relatedSymbols: ['camera', 'memory', 'observation', 'moment'],
      shadowAspect: 'Yaşamak yerine kaydetme',
      lightAspect: 'Anın değeri',
    ),

    // ════════════════════════════════════════════════════════════════════════
    // GÜNLÜK EYLEMLER - 20+ Sembol
    // ════════════════════════════════════════════════════════════════════════
    DreamSymbolData(
      symbol: 'eating',
      symbolTr: 'Yemek Yemek',
      emoji: '🍽️',
      category: SymbolCategory.eylem,
      universalMeanings: [
        'Beslenme',
        'Tatmin',
        'Hayatta kalma',
        'Zevk',
        'Özümseme',
        'Enerji alma',
      ],
      emotionVariants: {
        EmotionalTone.huzur: 'Doygunluk',
        EmotionalTone.heyecan: 'Lezzetli yemek',
        EmotionalTone.korku: 'Yiyememe',
        EmotionalTone.sucluluk: 'Aşırı yeme',
      },
      archetypes: ['Doyuran', 'Tüketen', 'Yaşayan'],
      relatedSymbols: ['food', 'hunger', 'satisfaction', 'nourishment'],
      shadowAspect: 'Obur tüketim',
      lightAspect: 'Sağlıklı beslenme',
    ),

    DreamSymbolData(
      symbol: 'drinking',
      symbolTr: 'İçmek',
      emoji: '🥤',
      category: SymbolCategory.eylem,
      universalMeanings: [
        'Susuzluğu giderme',
        'Yaşam suyu',
        'Bilgi içmek',
        'Sarhoşluk',
        'Duygusal ihtiyaç',
        'Arinma',
      ],
      emotionVariants: {
        EmotionalTone.huzur: 'Susuzluğu giderme',
        EmotionalTone.korku: 'Zehir içme',
        EmotionalTone.heyecan: 'Kutlama içkisi',
        EmotionalTone.ozlem: 'Susuzluk',
      },
      archetypes: ['Yaşayan', 'Arınan', 'Sarhoş'],
      relatedSymbols: ['water', 'thirst', 'alcohol', 'life'],
      shadowAspect: 'Bağımlılık',
      lightAspect: 'Hayat suyu',
    ),

    DreamSymbolData(
      symbol: 'sleeping_action',
      symbolTr: 'Uyumak',
      emoji: '😴',
      category: SymbolCategory.eylem,
      universalMeanings: [
        'Dinlenme',
        'Bilincdışı',
        'Kaçış',
        'Yenilenme',
        'Ölüm benzeri',
        'Hayal görme',
      ],
      emotionVariants: {
        EmotionalTone.huzur: 'Derin dinlenme',
        EmotionalTone.korku: 'Uyanamama',
        EmotionalTone.donukluk: 'Uyuşukluk',
        EmotionalTone.merak: 'Nerede uyuyorum?',
      },
      archetypes: ['Uyuyan Güzel', 'Bilinçdışı', 'Rüya Görücü'],
      relatedSymbols: ['dream', 'bed', 'rest', 'unconscious'],
      shadowAspect: 'Gerçeklikten kaçış',
      lightAspect: 'Dinleyici yenilenme',
    ),

    DreamSymbolData(
      symbol: 'waking',
      symbolTr: 'Uyanmak',
      emoji: '⏰',
      category: SymbolCategory.eylem,
      universalMeanings: [
        'Farkındalık',
        'Yeni başlangıç',
        'Ayılma',
        'Spiritüel uyanış',
        'Gerçekle yüzleşme',
        'Bilinç',
      ],
      emotionVariants: {
        EmotionalTone.huzur: 'Taze sabah',
        EmotionalTone.korku: 'Kabusdan uyanma',
        EmotionalTone.heyecan: 'Yeni gün',
        EmotionalTone.merak: 'Neredeyim?',
      },
      archetypes: ['Uyanık', 'Ayik', 'Bilinçli'],
      relatedSymbols: ['morning', 'awakening', 'consciousness', 'light'],
      shadowAspect: 'İsteksiz uyanış',
      lightAspect: 'Bilinç genişlemesi',
    ),

    DreamSymbolData(
      symbol: 'bathing',
      symbolTr: 'Banyo Yapmak',
      emoji: '🛁',
      category: SymbolCategory.eylem,
      universalMeanings: [
        'Arınma',
        'Temizlenme',
        'Rahatlama',
        'Yeniden doğuş',
        'Öz bakım',
        'Suyla birlik',
      ],
      emotionVariants: {
        EmotionalTone.huzur: 'Derin rahatlama',
        EmotionalTone.heyecan: 'Yenilenme',
        EmotionalTone.korku: 'Çıplak savunmasızlık',
        EmotionalTone.merak: 'Temizlenen ne?',
      },
      archetypes: ['Arınan', 'Yeniden Doğan', 'Bakıcı'],
      relatedSymbols: ['water', 'cleansing', 'relaxation', 'purity'],
      shadowAspect: 'Obsesif temizlik',
      lightAspect: 'Ruhsal arınma',
    ),

    DreamSymbolData(
      symbol: 'dressing',
      symbolTr: 'Giyinmek',
      emoji: '👔',
      category: SymbolCategory.eylem,
      universalMeanings: [
        'Kimlik hazırlığı',
        'Sosyal maske',
        'Rol üstlenme',
        'Koruma',
        'İmaj',
        'Dönüşüm',
      ],
      emotionVariants: {
        EmotionalTone.huzur: 'Hazır hissetme',
        EmotionalTone.korku: 'Yanlış kıyafet',
        EmotionalTone.merak: 'Ne giymeliyim?',
        EmotionalTone.heyecan: 'Özel kıyafet',
      },
      archetypes: ['Maske Takan', 'Aktör', 'Sosyal Ben'],
      relatedSymbols: ['clothes', 'identity', 'mask', 'preparation'],
      shadowAspect: 'Sahte görünüm',
      lightAspect: 'Özgün ifade',
    ),

    DreamSymbolData(
      symbol: 'cleaning',
      symbolTr: 'Temizlik Yapmak',
      emoji: '🧹',
      category: SymbolCategory.eylem,
      universalMeanings: [
        'Düzenleme',
        'Arınma',
        'Eski enerji temizleme',
        'Yenilenme',
        'Kontrol',
        'Baştan başlama',
      ],
      emotionVariants: {
        EmotionalTone.huzur: 'Düzenin huzuru',
        EmotionalTone.heyecan: 'Temiz başlangıç',
        EmotionalTone.korku: 'Bitmeyen pislik',
        EmotionalTone.ofke: 'Zoraki temizlik',
      },
      archetypes: ['Düzenleyici', 'Arındırıcı', 'Yenileyici'],
      relatedSymbols: ['order', 'purity', 'organization', 'fresh'],
      shadowAspect: 'Obsesif temizlik',
      lightAspect: 'Enerji temizliği',
    ),

    DreamSymbolData(
      symbol: 'packing',
      symbolTr: 'Bavul Toplamak',
      emoji: '🧳',
      category: SymbolCategory.eylem,
      universalMeanings: [
        'Yolculuk hazırlığı',
        'Değişim',
        'Ne alacağım seçimi',
        'Geçmişi taşıma',
        'Yeni başlangıç',
        'Organizasyon',
      ],
      emotionVariants: {
        EmotionalTone.heyecan: 'Yolculuk heyecanı',
        EmotionalTone.korku: 'Birşey unutma',
        EmotionalTone.ozlem: 'Gitme zamanı',
        EmotionalTone.merak: 'Nereye gidiyorum?',
      },
      archetypes: ['Yolcu', 'Gezgin', 'Değişen'],
      relatedSymbols: ['journey', 'travel', 'change', 'luggage'],
      shadowAspect: 'Fazla bagaj',
      lightAspect: 'Esasları seçme',
    ),

    DreamSymbolData(
      symbol: 'shopping',
      symbolTr: 'Alışveriş',
      emoji: '🛒',
      category: SymbolCategory.eylem,
      universalMeanings: [
        'Seçim yapma',
        'İhtiyaçları karşılama',
        'Tüketim',
        'Arayış',
        'Değer değişimi',
        'Karar verme',
      ],
      emotionVariants: {
        EmotionalTone.heyecan: 'Yeni şeyler',
        EmotionalTone.korku: 'Para yetmeme',
        EmotionalTone.sucluluk: 'Gereksiz harcama',
        EmotionalTone.merak: 'Ne arıyorum?',
      },
      archetypes: ['Arayışçı', 'Tüketici', 'Seçen'],
      relatedSymbols: ['money', 'choice', 'desire', 'abundance'],
      shadowAspect: 'Bağımlı tüketim',
      lightAspect: 'Bilinçli seçim',
    ),

    DreamSymbolData(
      symbol: 'waiting',
      symbolTr: 'Beklemek',
      emoji: '⏳',
      category: SymbolCategory.eylem,
      universalMeanings: [
        'Sabır',
        'Belirsizlik',
        'Zaman geçişi',
        'Kontrol dışı',
        'Beklenti',
        'Pasiflik',
      ],
      emotionVariants: {
        EmotionalTone.huzur: 'Sakin bekleme',
        EmotionalTone.korku: 'Sonsuza kadar',
        EmotionalTone.merak: 'Neyi bekliyorum?',
        EmotionalTone.ofke: 'Sabırsızlık',
      },
      archetypes: ['Bekleyen', 'Sabırlı', 'Pasif'],
      relatedSymbols: ['time', 'patience', 'uncertainty', 'passive'],
      shadowAspect: 'Hareketsizlik',
      lightAspect: 'Bilge sabır',
    ),
  ];
}
