/// MEGA Dream Symbols Database Part 14 - People, Roles & Archetypes
/// Insanlar, Roller, Arketipler, Figürler
library;

import '../models/dream_interpretation_models.dart';

/// Part 14: Insanlar ve Roller - 100+ Sembol
class MegaDreamSymbolsPart14 {
  static const List<DreamSymbolData> symbols = [
    // ════════════════════════════════════════════════════════════════════════
    // AILE ÜYELERI - 25+ Sembol
    // ════════════════════════════════════════════════════════════════════════
    DreamSymbolData(
      symbol: 'grandmother',
      symbolTr: 'Büyükanne',
      emoji: '👵',
      category: SymbolCategory.insan,
      universalMeanings: [
        'Bilgelik',
        'Şefkat',
        'Kökler',
        'Gelenek',
        'Koruma',
        'Atasal bilgi',
      ],
      emotionVariants: {
        EmotionalTone.huzur: 'Anne şefkati',
        EmotionalTone.ozlem: 'Geçmiş anılar',
        EmotionalTone.merak: 'Atasal mesaj',
        EmotionalTone.korku: 'Ölüm, kayıp',
      },
      archetypes: ['Bilge Kadın', 'Anne', 'Ata'],
      relatedSymbols: ['wisdom', 'family', 'ancestors', 'tradition'],
      shadowAspect: 'Eski kalıplar, baskı',
      lightAspect: 'Koşulsuz sevgi, bilgelik',
    ),

    DreamSymbolData(
      symbol: 'grandfather',
      symbolTr: 'Büyükbaba',
      emoji: '👴',
      category: SymbolCategory.insan,
      universalMeanings: [
        'Bilgelik',
        'Otorite',
        'Koruma',
        'Deneyim',
        'Miras',
        'Yaşlı bilge',
      ],
      emotionVariants: {
        EmotionalTone.huzur: 'Güvenli koruma',
        EmotionalTone.ozlem: 'Kayıp rehber',
        EmotionalTone.merak: 'Atasal öğreti',
        EmotionalTone.korku: 'Ölümü hatırlama',
      },
      archetypes: ['Yaşlı Bilge', 'Baba', 'Ata'],
      relatedSymbols: ['wisdom', 'authority', 'heritage', 'elder'],
      shadowAspect: 'Katı kurallar',
      lightAspect: 'Rehberlik, miras',
    ),

    DreamSymbolData(
      symbol: 'sister',
      symbolTr: 'Kız Kardeş',
      emoji: '👧',
      category: SymbolCategory.insan,
      universalMeanings: [
        'Benzer taraf',
        'Rekabet',
        'Destek',
        'Paylaşım',
        'Büyümee ortağı',
        'Kadınlık yansıması',
      ],
      emotionVariants: {
        EmotionalTone.huzur: 'Yakın bağ',
        EmotionalTone.ofke: 'Kardeş rekabeti',
        EmotionalTone.ozlem: 'Uzak kardeş',
        EmotionalTone.heyecan: 'Ortak macera',
      },
      archetypes: ['Kardeş', 'Yansıma', 'Ortak'],
      relatedSymbols: ['sibling', 'mirror', 'rivalry', 'bond'],
      shadowAspect: 'Kıskançlık',
      lightAspect: 'Derin dostluk',
    ),

    DreamSymbolData(
      symbol: 'brother',
      symbolTr: 'Erkek Kardeş',
      emoji: '👦',
      category: SymbolCategory.insan,
      universalMeanings: [
        'Erkeksi taraf',
        'Rekabet',
        'Koruyucu',
        'Ortak',
        'Benzer yol',
        'Animus yansıması',
      ],
      emotionVariants: {
        EmotionalTone.huzur: 'Güvenilir destek',
        EmotionalTone.ofke: 'Rekabet',
        EmotionalTone.ozlem: 'Uzaklık',
        EmotionalTone.heyecan: 'Birlikte macera',
      },
      archetypes: ['Kardeş', 'Savaşçı', 'Koruyucu'],
      relatedSymbols: ['sibling', 'rivalry', 'protection', 'bond'],
      shadowAspect: 'Kain ve Habil',
      lightAspect: 'Kardeşlik bağı',
    ),

    DreamSymbolData(
      symbol: 'uncle',
      symbolTr: 'Amca/Dayı',
      emoji: '👨',
      category: SymbolCategory.insan,
      universalMeanings: [
        'Alternatif baba',
        'Rehber',
        'Aile bağı',
        'Dış perspektif',
        'Koruyucu',
        'Model',
      ],
      emotionVariants: {
        EmotionalTone.huzur: 'Güvenilir yetişkin',
        EmotionalTone.merak: 'Farklı bakış',
        EmotionalTone.ozlem: 'Kayıp bağ',
        EmotionalTone.heyecan: 'Macera ortağı',
      },
      archetypes: ['Akıl Hocası', 'Alternatif Baba', 'Rehber'],
      relatedSymbols: ['mentor', 'family', 'guidance', 'wisdom'],
      shadowAspect: 'Karışan aile',
      lightAspect: 'Bilge destek',
    ),

    DreamSymbolData(
      symbol: 'aunt',
      symbolTr: 'Hala/Teyze',
      emoji: '👩',
      category: SymbolCategory.insan,
      universalMeanings: [
        'Alternatif anne',
        'Şefkat',
        'Kadın bilgeliği',
        'Aile sırları',
        'Koruyucu',
        'Rehber',
      ],
      emotionVariants: {
        EmotionalTone.huzur: 'Anlayışlı yetişkin',
        EmotionalTone.merak: 'Aile hikayeleri',
        EmotionalTone.ozlem: 'Şefkat arayışı',
        EmotionalTone.korku: 'Aile draması',
      },
      archetypes: ['İkinci Anne', 'Kadın Bilge', 'Koruyucu'],
      relatedSymbols: ['family', 'nurture', 'wisdom', 'secret'],
      shadowAspect: 'Dedikodu, aile politikası',
      lightAspect: 'Koşulsuz destek',
    ),

    DreamSymbolData(
      symbol: 'cousin',
      symbolTr: 'Kuzen',
      emoji: '🧑',
      category: SymbolCategory.insan,
      universalMeanings: [
        'Paralel yaşam',
        'Aile bağı',
        'Alternatif yol',
        'Çocukluk ortağı',
        'Karşılaştırma',
        'Geniş aile',
      ],
      emotionVariants: {
        EmotionalTone.huzur: 'Tanıdık bağ',
        EmotionalTone.merak: 'Paralel hayatlar',
        EmotionalTone.heyecan: 'Buluşma',
        EmotionalTone.ofke: 'Karşılaştırma',
      },
      archetypes: ['Paralel Ben', 'Aile', 'Çocukluk'],
      relatedSymbols: ['family', 'parallel', 'childhood', 'bond'],
      shadowAspect: 'Kıyaslama',
      lightAspect: 'Geniş aile bağı',
    ),

    DreamSymbolData(
      symbol: 'son',
      symbolTr: 'Oğul',
      emoji: '👦',
      category: SymbolCategory.insan,
      universalMeanings: [
        'Miras',
        'Gelecek',
        'Genç erkeksi enerji',
        'Süreklilik',
        'Sorumluluk',
        'İç erkek çocuk',
      ],
      emotionVariants: {
        EmotionalTone.huzur: 'Gurur',
        EmotionalTone.korku: 'Kayıp korkusu',
        EmotionalTone.ozlem: 'Uzaklaşma',
        EmotionalTone.heyecan: 'Gelişim',
      },
      archetypes: ['Varış', 'Gelecek', 'Prens'],
      relatedSymbols: ['child', 'future', 'inheritance', 'youth'],
      shadowAspect: 'Beklentiler',
      lightAspect: 'Umut ve devam',
    ),

    DreamSymbolData(
      symbol: 'daughter',
      symbolTr: 'Kız',
      emoji: '👧',
      category: SymbolCategory.insan,
      universalMeanings: [
        'Kadınsı geleceek',
        'İç kız çocuk',
        'Süreklilik',
        'Şefkat mirası',
        'Hassasiyet',
        'Genç kadın',
      ],
      emotionVariants: {
        EmotionalTone.huzur: 'Derin bağ',
        EmotionalTone.korku: 'Koruma ihtiyacı',
        EmotionalTone.ozlem: 'Büyüme hüznü',
        EmotionalTone.heyecan: 'Gelişim',
      },
      archetypes: ['Prenses', 'Genç Kız', 'Gelecek'],
      relatedSymbols: ['child', 'feminine', 'future', 'innocence'],
      shadowAspect: 'Aşırı koruma',
      lightAspect: 'Koşulsuz sevgi',
    ),

    DreamSymbolData(
      symbol: 'spouse',
      symbolTr: 'Eş',
      emoji: '💑',
      category: SymbolCategory.insan,
      universalMeanings: [
        'Partner',
        'Tamamlayıcı',
        'Bağlılık',
        'Ayna',
        'Birlik',
        'Anima/Animus',
      ],
      emotionVariants: {
        EmotionalTone.huzur: 'Derin bağ',
        EmotionalTone.korku: 'Kayıp korkusu',
        EmotionalTone.ofke: 'Çatışma',
        EmotionalTone.ozlem: 'Eski günler',
      },
      archetypes: ['Partner', 'Ayna', 'Sevgili'],
      relatedSymbols: ['marriage', 'love', 'commitment', 'mirror'],
      shadowAspect: 'Bağımlılık, çatışma',
      lightAspect: 'Derin ortaklık',
    ),

    // ════════════════════════════════════════════════════════════════════════
    // MESLEKLER VE ROLLER - 35+ Sembol
    // ════════════════════════════════════════════════════════════════════════
    DreamSymbolData(
      symbol: 'doctor',
      symbolTr: 'Doktor',
      emoji: '👨‍⚕️',
      category: SymbolCategory.insan,
      universalMeanings: [
        'Şifa',
        'Otorite',
        'Yardım',
        'Sağlık kaygısı',
        'Teşhis',
        'İç şifacı',
      ],
      emotionVariants: {
        EmotionalTone.huzur: 'Şifa bulma',
        EmotionalTone.korku: 'Kötü haber',
        EmotionalTone.merak: 'Teşhis nedir?',
        EmotionalTone.ozlem: 'İyileşme arzusu',
      },
      archetypes: ['Şifacı', 'Bilge', 'Kurtarıcı'],
      relatedSymbols: ['healing', 'medicine', 'health', 'care'],
      shadowAspect: 'Tanrı kompleksi',
      lightAspect: 'Gerçek şifa',
    ),

    DreamSymbolData(
      symbol: 'nurse',
      symbolTr: 'Hemşire',
      emoji: '👩‍⚕️',
      category: SymbolCategory.insan,
      universalMeanings: [
        'Bakım',
        'Şefkat',
        'Yardım',
        'Hastane',
        'İyileşme süreci',
        'Annelik',
      ],
      emotionVariants: {
        EmotionalTone.huzur: 'Bakım görme',
        EmotionalTone.korku: 'Hastalık',
        EmotionalTone.ozlem: 'Bakım ihtiyacı',
        EmotionalTone.sucluluk: 'Başkalarına bakım',
      },
      archetypes: ['Bakıcı', 'Anne', 'Şifacı'],
      relatedSymbols: ['care', 'hospital', 'healing', 'nurture'],
      shadowAspect: 'Tükenme',
      lightAspect: 'Şefkatli bakım',
    ),

    DreamSymbolData(
      symbol: 'lawyer',
      symbolTr: 'Avukat',
      emoji: '👨‍⚖️',
      category: SymbolCategory.insan,
      universalMeanings: [
        'Savunma',
        'Adalet',
        'Tartışma',
        'Kurallar',
        'Hak arama',
        'Koruma',
      ],
      emotionVariants: {
        EmotionalTone.korku: 'Mahkeme',
        EmotionalTone.huzur: 'Savunulma',
        EmotionalTone.ofke: 'Adaletsizlik',
        EmotionalTone.merak: 'Hukuki durum',
      },
      archetypes: ['Savunucu', 'Adalet', 'Koruyucu'],
      relatedSymbols: ['justice', 'court', 'defense', 'rules'],
      shadowAspect: 'Manipülasyon',
      lightAspect: 'Hak savunuculuğu',
    ),

    DreamSymbolData(
      symbol: 'police_officer',
      symbolTr: 'Polis',
      emoji: '👮',
      category: SymbolCategory.insan,
      universalMeanings: [
        'Otorite',
        'Kural',
        'Koruma',
        'Suçluluk',
        'Düzen',
        'İç eleştirmen',
      ],
      emotionVariants: {
        EmotionalTone.korku: 'Yakalanma',
        EmotionalTone.huzur: 'Korunma',
        EmotionalTone.sucluluk: 'Yasak ihlali',
        EmotionalTone.ofke: 'Haksız müdahale',
      },
      archetypes: ['Bekçi', 'Yargıç', 'Otorite'],
      relatedSymbols: ['authority', 'rules', 'guilt', 'protection'],
      shadowAspect: 'Baskı, kontrol',
      lightAspect: 'Koruyucu düzen',
    ),

    DreamSymbolData(
      symbol: 'firefighter',
      symbolTr: 'İtfaiyeci',
      emoji: '👨‍🚒',
      category: SymbolCategory.insan,
      universalMeanings: [
        'Kahraman',
        'Kurtarıcı',
        'Tehlike ile mücadele',
        'Koruyucu',
        'Cesaret',
        'Acil müdahale',
      ],
      emotionVariants: {
        EmotionalTone.huzur: 'Kurtarılma',
        EmotionalTone.korku: 'Yangın, tehlike',
        EmotionalTone.heyecan: 'Aksiyon',
        EmotionalTone.merak: 'Krizle başa çıkma',
      },
      archetypes: ['Kahraman', 'Kurtarıcı', 'Cesur'],
      relatedSymbols: ['fire', 'rescue', 'danger', 'courage'],
      shadowAspect: 'Çok geç',
      lightAspect: 'Zamanında kurtarış',
    ),

    DreamSymbolData(
      symbol: 'pilot',
      symbolTr: 'Pilot',
      emoji: '👨‍✈️',
      category: SymbolCategory.insan,
      universalMeanings: [
        'Kontrol',
        'Yön bulma',
        'Yükseklik',
        'Özgürlük',
        'Sorumluluk',
        'Liderlik',
      ],
      emotionVariants: {
        EmotionalTone.heyecan: 'Uçuş heyecanı',
        EmotionalTone.korku: 'Kontrolü kaybetme',
        EmotionalTone.huzur: 'Güvenli uçuş',
        EmotionalTone.merak: 'Yeni ufuklar',
      },
      archetypes: ['Kaptan', 'Rehber', 'Kaşif'],
      relatedSymbols: ['airplane', 'flying', 'control', 'freedom'],
      shadowAspect: 'Düşüş',
      lightAspect: 'Hayatın kontrolü',
    ),

    DreamSymbolData(
      symbol: 'chef',
      symbolTr: 'Aşçı',
      emoji: '👨‍🍳',
      category: SymbolCategory.insan,
      universalMeanings: [
        'Yaratıcılık',
        'Besleme',
        'Dönüştürme',
        'Ustalık',
        'Şefkat',
        'Simya',
      ],
      emotionVariants: {
        EmotionalTone.huzur: 'Yaratma keyfi',
        EmotionalTone.heyecan: 'Yeni tarifler',
        EmotionalTone.korku: 'Başarısız yemek',
        EmotionalTone.merak: 'Malzemeler',
      },
      archetypes: ['Yaratıcı', 'Besleyen', 'Simyacı'],
      relatedSymbols: ['cooking', 'food', 'creation', 'nurture'],
      shadowAspect: 'Eleştiri',
      lightAspect: 'Sevgiyle besleme',
    ),

    DreamSymbolData(
      symbol: 'artist',
      symbolTr: 'Sanatçı',
      emoji: '👨‍🎨',
      category: SymbolCategory.insan,
      universalMeanings: [
        'Yaratıcılık',
        'İfade',
        'Benzersizlik',
        'Güzellik',
        'Spiritüel bağ',
        'Dış dünyaya yansıtma',
      ],
      emotionVariants: {
        EmotionalTone.heyecan: 'Yaratma ilhamı',
        EmotionalTone.huzur: 'Sanatsal akış',
        EmotionalTone.korku: 'Yaratıcı blok',
        EmotionalTone.merak: 'Ne yaratıyorum?',
      },
      archetypes: ['Yaratıcı', 'Vizyoner', 'İfadeci'],
      relatedSymbols: ['creation', 'beauty', 'expression', 'vision'],
      shadowAspect: 'Anlaşılmama',
      lightAspect: 'Saf yaratıcılık',
    ),

    DreamSymbolData(
      symbol: 'musician',
      symbolTr: 'Müzisyen',
      emoji: '🎸',
      category: SymbolCategory.insan,
      universalMeanings: [
        'Uyum',
        'İfade',
        'Duygusal bağ',
        'Evrensel dil',
        'Ritim',
        'Ruh',
      ],
      emotionVariants: {
        EmotionalTone.huzur: 'Müzikle bir olma',
        EmotionalTone.heyecan: 'Performans',
        EmotionalTone.ozlem: 'Müzik yapma',
        EmotionalTone.korku: 'Yanlış nota',
      },
      archetypes: ['Orpheus', 'Şair', 'Uyumlu'],
      relatedSymbols: ['music', 'harmony', 'expression', 'soul'],
      shadowAspect: 'Ses çıkaramama',
      lightAspect: 'Evrensel uyum',
    ),

    DreamSymbolData(
      symbol: 'scientist',
      symbolTr: 'Bilim İnsanı',
      emoji: '👨‍🔬',
      category: SymbolCategory.insan,
      universalMeanings: [
        'Keşif',
        'Analiz',
        'Gerçek arayışı',
        'Merak',
        'Mantık',
        'İlerleme',
      ],
      emotionVariants: {
        EmotionalTone.heyecan: 'Keşif anı',
        EmotionalTone.merak: 'Soru sorma',
        EmotionalTone.huzur: 'Anlama',
        EmotionalTone.korku: 'Bilinmeyen',
      },
      archetypes: ['Araştırmacı', 'Bilge', 'Keşifçi'],
      relatedSymbols: ['discovery', 'truth', 'knowledge', 'curiosity'],
      shadowAspect: 'Soğuk mantık',
      lightAspect: 'Gerçeğin peşinde',
    ),

    DreamSymbolData(
      symbol: 'writer',
      symbolTr: 'Yazar',
      emoji: '✍️',
      category: SymbolCategory.insan,
      universalMeanings: [
        'İfade',
        'Hikaye anlatımı',
        'Kayıt',
        'Yaratıcılık',
        'Düşünce dışavurumu',
        'Miras bırakma',
      ],
      emotionVariants: {
        EmotionalTone.heyecan: 'İlham',
        EmotionalTone.huzur: 'Yazma akışı',
        EmotionalTone.korku: 'Boş sayfa',
        EmotionalTone.merak: 'Hikaye nereye gidiyor?',
      },
      archetypes: ['Hikaye Anlatıcı', 'Yaratıcı', 'Belgeleyici'],
      relatedSymbols: ['book', 'story', 'creation', 'expression'],
      shadowAspect: 'Yazma blokajı',
      lightAspect: 'Kelimelerle dünya yaratma',
    ),

    DreamSymbolData(
      symbol: 'farmer',
      symbolTr: 'Çiftçi',
      emoji: '👨‍🌾',
      category: SymbolCategory.insan,
      universalMeanings: [
        'Emek',
        'Hasat',
        'Doğa ile bağ',
        'Sabır',
        'Döngü',
        'Toprakla çalışma',
      ],
      emotionVariants: {
        EmotionalTone.huzur: 'Toprak bağı',
        EmotionalTone.heyecan: 'Hasat zamanı',
        EmotionalTone.korku: 'Kuraklık',
        EmotionalTone.ozlem: 'Basit yaşam',
      },
      archetypes: ['Ekici', 'Toprak', 'Sabırlı'],
      relatedSymbols: ['harvest', 'earth', 'patience', 'nature'],
      shadowAspect: 'Verimsiz toprak',
      lightAspect: 'Emeğin meyvesi',
    ),

    DreamSymbolData(
      symbol: 'builder',
      symbolTr: 'İnşaatçı',
      emoji: '👷',
      category: SymbolCategory.insan,
      universalMeanings: [
        'Yaratma',
        'Yapı',
        'Temel atma',
        'Kalıcı eser',
        'Emek',
        'Fiziksel güç',
      ],
      emotionVariants: {
        EmotionalTone.heyecan: 'İnşa etme',
        EmotionalTone.huzur: 'Somut başarı',
        EmotionalTone.korku: 'Çöken yapı',
        EmotionalTone.merak: 'Ne inşa ediyorum?',
      },
      archetypes: ['Mimar', 'Yaratıcı', 'Temel Atıcı'],
      relatedSymbols: ['building', 'foundation', 'creation', 'structure'],
      shadowAspect: 'Yıkıntı',
      lightAspect: 'Kalıcı değer',
    ),

    DreamSymbolData(
      symbol: 'driver',
      symbolTr: 'Şoför',
      emoji: '🚗',
      category: SymbolCategory.insan,
      universalMeanings: [
        'Kontrol',
        'Yön',
        'Yaşam yolculuğu',
        'Sorumluluk',
        'Hız',
        'Karar verme',
      ],
      emotionVariants: {
        EmotionalTone.huzur: 'Rahat sürüş',
        EmotionalTone.korku: 'Kaza, kontrol kaybı',
        EmotionalTone.heyecan: 'Özgürlük',
        EmotionalTone.merak: 'Nereye gidiyorum?',
      },
      archetypes: ['Yolcu', 'Kontrol Eden', 'Yön Bulucu'],
      relatedSymbols: ['car', 'journey', 'control', 'direction'],
      shadowAspect: 'Kaybolma, kaza',
      lightAspect: 'Hayatın kontrolü',
    ),

    // ════════════════════════════════════════════════════════════════════════
    // ARKETIPSEL FIGÜRLER - 30+ Sembol
    // ════════════════════════════════════════════════════════════════════════
    DreamSymbolData(
      symbol: 'wise_old_man',
      symbolTr: 'Yaşlı Bilge',
      emoji: '🧙',
      category: SymbolCategory.insan,
      universalMeanings: [
        'Bilgelik',
        'Rehberlik',
        'İç ses',
        'Spiritüel öğretmen',
        'Deneyim',
        'Kolektif bilinç',
      ],
      emotionVariants: {
        EmotionalTone.huzur: 'Rehberlik',
        EmotionalTone.merak: 'Öğreti nedir?',
        EmotionalTone.korku: 'Ağır sınavlar',
        EmotionalTone.heyecan: 'Sırların açılması',
      },
      archetypes: ['Senex', 'Mentor', 'Guru'],
      relatedSymbols: ['wisdom', 'guidance', 'teacher', 'knowledge'],
      shadowAspect: 'Dogmatik, katı',
      lightAspect: 'Gerçek bilgelik',
    ),

    DreamSymbolData(
      symbol: 'divine_child',
      symbolTr: 'İlahi Çocuk',
      emoji: '👼',
      category: SymbolCategory.insan,
      universalMeanings: [
        'Yeni başlangıç',
        'Masumiyet',
        'Potansiyel',
        'Umut',
        'Saf enerji',
        'Gelecek vaat',
      ],
      emotionVariants: {
        EmotionalTone.huzur: 'Saf sevgi',
        EmotionalTone.heyecan: 'Yeni olanaklar',
        EmotionalTone.korku: 'Koruma ihtiyacı',
        EmotionalTone.merak: 'Ne olacak?',
      },
      archetypes: ['Puer', 'Yeni', 'Umut'],
      relatedSymbols: ['baby', 'innocence', 'potential', 'future'],
      shadowAspect: 'Olgunlaşmama',
      lightAspect: 'Saf potansiyel',
    ),

    DreamSymbolData(
      symbol: 'trickster',
      symbolTr: 'Trickster/Düzenbaz',
      emoji: '🃏',
      category: SymbolCategory.insan,
      universalMeanings: [
        'Kural yıkıcı',
        'Kaos',
        'Değişim ajanı',
        'Mizah',
        'Öğretici aldatma',
        'Sınır aşma',
      ],
      emotionVariants: {
        EmotionalTone.heyecan: 'Beklenmedik',
        EmotionalTone.korku: 'Aldatılma',
        EmotionalTone.merak: 'Oyun nedir?',
        EmotionalTone.ofke: 'Kandırılma',
      },
      archetypes: ['Hermes', 'Loki', 'Joker'],
      relatedSymbols: ['chaos', 'change', 'humor', 'deception'],
      shadowAspect: 'Yıkıcı aldatma',
      lightAspect: 'Dönüştürücü bilgelik',
    ),

    DreamSymbolData(
      symbol: 'shadow_figure',
      symbolTr: 'Gölge Figür',
      emoji: '👤',
      category: SymbolCategory.insan,
      universalMeanings: [
        'Bastırılmış taraf',
        'Reddedilen ben',
        'Karanlık yön',
        'Bilinçdışı',
        'Bütünleşme çağrısı',
        'Korku kaynağı',
      ],
      emotionVariants: {
        EmotionalTone.korku: 'Kaçınılan yüzleşme',
        EmotionalTone.merak: 'Kim bu?',
        EmotionalTone.ofke: 'İç çatışma',
        EmotionalTone.huzur: 'Kabul',
      },
      archetypes: ['Gölge', 'Karanlık İkiz', 'Bastırılmış'],
      relatedSymbols: ['darkness', 'fear', 'unconscious', 'self'],
      shadowAspect: 'Kendinin görülmeyen yüzü',
      lightAspect: 'Bütünleşme fırsatı',
    ),

    DreamSymbolData(
      symbol: 'anima',
      symbolTr: 'Anima/İç Kadın',
      emoji: '👸',
      category: SymbolCategory.insan,
      universalMeanings: [
        'İç kadınsılık',
        'Duygusal taraf',
        'Yaratıcılık',
        'İlham perisi',
        'Ruh rehberi',
        'Gizemli kadın',
      ],
      emotionVariants: {
        EmotionalTone.huzur: 'İç uyum',
        EmotionalTone.ozlem: 'Aranan parça',
        EmotionalTone.heyecan: 'Büyüleyici',
        EmotionalTone.korku: 'Yutulma',
      },
      archetypes: ['Muse', 'İç Kadın', 'Ruh'],
      relatedSymbols: ['feminine', 'soul', 'creativity', 'emotion'],
      shadowAspect: 'Kapris, yutma',
      lightAspect: 'Ruhsal bütünlük',
    ),

    DreamSymbolData(
      symbol: 'animus',
      symbolTr: 'Animus/İç Erkek',
      emoji: '🤴',
      category: SymbolCategory.insan,
      universalMeanings: [
        'İç erkeksilik',
        'Eylem gücü',
        'Mantık',
        'Karar verme',
        'Koruyucu',
        'Gizemli erkek',
      ],
      emotionVariants: {
        EmotionalTone.huzur: 'Güç hissi',
        EmotionalTone.heyecan: 'Çekici güç',
        EmotionalTone.korku: 'Dominant',
        EmotionalTone.merak: 'Kim bu adam?',
      },
      archetypes: ['Prens', 'İç Erkek', 'Koruyucu'],
      relatedSymbols: ['masculine', 'action', 'logic', 'protection'],
      shadowAspect: 'Sert, kontrol eden',
      lightAspect: 'Dengeli güç',
    ),

    DreamSymbolData(
      symbol: 'great_mother',
      symbolTr: 'Ulu Anne',
      emoji: '🌍',
      category: SymbolCategory.insan,
      universalMeanings: [
        'Koşulsuz sevgi',
        'Koruma',
        'Doğurganlık',
        'Besleme',
        'Doğa',
        'Kaynak',
      ],
      emotionVariants: {
        EmotionalTone.huzur: 'Sarılma',
        EmotionalTone.ozlem: 'Anne kucağı',
        EmotionalTone.korku: 'Yutulma',
        EmotionalTone.merak: 'Kökenler',
      },
      archetypes: ['Terra', 'Gaia', 'Anne Tanrıça'],
      relatedSymbols: ['mother', 'earth', 'nurture', 'protection'],
      shadowAspect: 'Boğucu anne',
      lightAspect: 'Koşulsuz kabul',
    ),

    DreamSymbolData(
      symbol: 'hero',
      symbolTr: 'Kahraman',
      emoji: '🦸',
      category: SymbolCategory.insan,
      universalMeanings: [
        'Cesaret',
        'Mücadele',
        'Dönüşüm',
        'Kurban',
        'Zafer',
        'Ego gelişimi',
      ],
      emotionVariants: {
        EmotionalTone.heyecan: 'Macera çağrısı',
        EmotionalTone.korku: 'Canavar karşısında',
        EmotionalTone.huzur: 'Zafer sonrası',
        EmotionalTone.merak: 'Görev nedir?',
      },
      archetypes: ['Kahraman', 'Savaşçı', 'Kurtarıcı'],
      relatedSymbols: ['journey', 'battle', 'victory', 'transformation'],
      shadowAspect: 'Kibir, düşüş',
      lightAspect: 'Gerçek cesaret',
    ),

    DreamSymbolData(
      symbol: 'villain',
      symbolTr: 'Kötü Adam',
      emoji: '🦹‍♂️',
      category: SymbolCategory.insan,
      universalMeanings: [
        'Gölge',
        'Düşman',
        'İç çatışma',
        'Korku kaynağı',
        'Engelleyici',
        'Dönüştürücü sınav',
      ],
      emotionVariants: {
        EmotionalTone.korku: 'Tehdit',
        EmotionalTone.ofke: 'Düşmanla savaş',
        EmotionalTone.merak: 'Motivasyonu ne?',
        EmotionalTone.sucluluk: 'İçimdeki kötü',
      },
      archetypes: ['Gölge', 'Düşman', 'Karanlık'],
      relatedSymbols: ['enemy', 'fear', 'shadow', 'obstacle'],
      shadowAspect: 'İçsel şeytan',
      lightAspect: 'Dönüşüm fırsatı',
    ),

    DreamSymbolData(
      symbol: 'sage',
      symbolTr: 'Bilge',
      emoji: '🧓',
      category: SymbolCategory.insan,
      universalMeanings: [
        'Spiritüel bilgelik',
        'İç rehber',
        'Üst bilinç',
        'Öğretmen',
        'Evrensel hakikat',
        'Aydınlanma',
      ],
      emotionVariants: {
        EmotionalTone.huzur: 'Derin anlayış',
        EmotionalTone.merak: 'Öğretiler',
        EmotionalTone.heyecan: 'Sırların açılması',
        EmotionalTone.ozlem: 'Bilgelik arayışı',
      },
      archetypes: ['Guru', 'Üstat', 'Aydınlanmış'],
      relatedSymbols: ['wisdom', 'enlightenment', 'teaching', 'truth'],
      shadowAspect: 'Sahte guru',
      lightAspect: 'Gerçek aydınlanma',
    ),

    DreamSymbolData(
      symbol: 'magician',
      symbolTr: 'Büyücü',
      emoji: '🪄',
      category: SymbolCategory.insan,
      universalMeanings: [
        'Dönüşüm gücü',
        'Gizli bilgi',
        'İrade',
        'Yaratma',
        'Evrensel güçler',
        'Simya',
      ],
      emotionVariants: {
        EmotionalTone.heyecan: 'Sihir gücü',
        EmotionalTone.korku: 'Karanlık büyü',
        EmotionalTone.merak: 'Nasıl yapıyor?',
        EmotionalTone.huzur: 'İçsel güç',
      },
      archetypes: ['Merlin', 'Simyacı', 'Şaman'],
      relatedSymbols: ['magic', 'transformation', 'power', 'knowledge'],
      shadowAspect: 'Kara büyü, manipülasyon',
      lightAspect: 'Dönüştürücü bilgelik',
    ),

    DreamSymbolData(
      symbol: 'healer',
      symbolTr: 'Şifacı',
      emoji: '🙏',
      category: SymbolCategory.insan,
      universalMeanings: [
        'Şifa',
        'Onarım',
        'Spiritüel yardım',
        'Empati',
        'Dönüştürme',
        'Kutsal dokunuş',
      ],
      emotionVariants: {
        EmotionalTone.huzur: 'Şifa bulma',
        EmotionalTone.ozlem: 'İyileşme arzusu',
        EmotionalTone.heyecan: 'Mucize',
        EmotionalTone.merak: 'Şifa nasıl?',
      },
      archetypes: ['Şifacı', 'Şaman', 'Aziz'],
      relatedSymbols: ['healing', 'medicine', 'transformation', 'love'],
      shadowAspect: 'Yarılı şifacı',
      lightAspect: 'Gerçek şifa gücü',
    ),

    DreamSymbolData(
      symbol: 'warrior',
      symbolTr: 'Savaşçı',
      emoji: '⚔️',
      category: SymbolCategory.insan,
      universalMeanings: [
        'Güç',
        'Mücadele',
        'Koruma',
        'Cesaret',
        'Disiplin',
        'Şeref',
      ],
      emotionVariants: {
        EmotionalTone.heyecan: 'Savaş ruhu',
        EmotionalTone.korku: 'Ölümcül düşman',
        EmotionalTone.huzur: 'Zafer sonrası',
        EmotionalTone.ofke: 'Savaş öfkesi',
      },
      archetypes: ['Mars', 'Ares', 'Samuray'],
      relatedSymbols: ['battle', 'courage', 'strength', 'honor'],
      shadowAspect: 'Yıkıcı şiddet',
      lightAspect: 'Haklı mücadele',
    ),

    DreamSymbolData(
      symbol: 'lover_archetype',
      symbolTr: 'Aşık (Arketip)',
      emoji: '💕',
      category: SymbolCategory.insan,
      universalMeanings: [
        'Tutku',
        'Bağlanma',
        'Güzellik takdiri',
        'Derin bağ',
        'Yaşam sevinci',
        'Hassasiyet',
      ],
      emotionVariants: {
        EmotionalTone.huzur: 'Derin bağ',
        EmotionalTone.heyecan: 'Tutkulu aşk',
        EmotionalTone.ozlem: 'Sevgiye hasret',
        EmotionalTone.korku: 'Kayıp',
      },
      archetypes: ['Afrodit', 'Eros', 'Romeo'],
      relatedSymbols: ['love', 'passion', 'beauty', 'connection'],
      shadowAspect: 'Bağımlılık, obsesyon',
      lightAspect: 'Koşulsuz sevgi',
    ),

    DreamSymbolData(
      symbol: 'ruler',
      symbolTr: 'Hükümdar',
      emoji: '👑',
      category: SymbolCategory.insan,
      universalMeanings: [
        'Otorite',
        'Kontrol',
        'Sorumluluk',
        'Düzen',
        'Liderlik',
        'Güç',
      ],
      emotionVariants: {
        EmotionalTone.huzur: 'Düzen hissi',
        EmotionalTone.korku: 'Tiranlık',
        EmotionalTone.heyecan: 'Güç kullanma',
        EmotionalTone.sucluluk: 'Ağır sorumluluk',
      },
      archetypes: ['Kral', 'Kraliçe', 'İmparator'],
      relatedSymbols: ['power', 'authority', 'crown', 'order'],
      shadowAspect: 'Zorba',
      lightAspect: 'Bilge lider',
    ),

    DreamSymbolData(
      symbol: 'orphan',
      symbolTr: 'Öksüz',
      emoji: '😢',
      category: SymbolCategory.insan,
      universalMeanings: [
        'Terkedilmişlik',
        'Yalnızlık',
        'Bağımsızlık zorunluluğu',
        'Kayıp',
        'Arayış',
        'Kurban',
      ],
      emotionVariants: {
        EmotionalTone.ozlem: 'Ait olma isteği',
        EmotionalTone.korku: 'Terkedilme',
        EmotionalTone.huzur: 'Kabul bulma',
        EmotionalTone.merak: 'Kökler nerede?',
      },
      archetypes: ['Oliver Twist', 'Kayıp Çocuk', 'Arayışçı'],
      relatedSymbols: ['abandonment', 'loneliness', 'search', 'belonging'],
      shadowAspect: 'Kurban rolü',
      lightAspect: 'Bağımsız güç',
    ),

    DreamSymbolData(
      symbol: 'caregiver',
      symbolTr: 'Bakıcı',
      emoji: '🤱',
      category: SymbolCategory.insan,
      universalMeanings: [
        'Şefkat',
        'Fedakarlık',
        'Koruma',
        'Besleme',
        'Hizmet',
        'Sevgi',
      ],
      emotionVariants: {
        EmotionalTone.huzur: 'Verme keyfi',
        EmotionalTone.sucluluk: 'Yeterince bakamama',
        EmotionalTone.ozlem: 'Bakım ihtiyacı',
        EmotionalTone.korku: 'Tükenme',
      },
      archetypes: ['Anne', 'Hemşire', 'Aziz'],
      relatedSymbols: ['nurture', 'care', 'love', 'sacrifice'],
      shadowAspect: 'Kendini ihmal',
      lightAspect: 'Koşulsuz bakım',
    ),

    DreamSymbolData(
      symbol: 'rebel',
      symbolTr: 'Asi',
      emoji: '✊',
      category: SymbolCategory.insan,
      universalMeanings: [
        'Özgürlük arayışı',
        'Kural yıkma',
        'Değişim',
        'Bireysellik',
        'Protestocu',
        'Devrimci',
      ],
      emotionVariants: {
        EmotionalTone.ofke: 'Sisteme karşı',
        EmotionalTone.heyecan: 'Devrim ruhu',
        EmotionalTone.korku: 'Sonuçlar',
        EmotionalTone.huzur: 'Özgürlük',
      },
      archetypes: ['Prometheus', 'Che', 'Devrimci'],
      relatedSymbols: ['freedom', 'change', 'protest', 'individuality'],
      shadowAspect: 'Yıkıcılık',
      lightAspect: 'Gerekli değişim',
    ),

    DreamSymbolData(
      symbol: 'creator',
      symbolTr: 'Yaratıcı',
      emoji: '🎨',
      category: SymbolCategory.insan,
      universalMeanings: [
        'Yaratma gücü',
        'Vizyon',
        'Yenilik',
        'İfade',
        'İcat',
        'Sanat',
      ],
      emotionVariants: {
        EmotionalTone.heyecan: 'Yaratma ilhamı',
        EmotionalTone.huzur: 'Akış hali',
        EmotionalTone.korku: 'Yaratıcı blok',
        EmotionalTone.merak: 'Ne yaratmalı?',
      },
      archetypes: ['Daedalus', 'Leonardo', 'İcat'],
      relatedSymbols: ['art', 'creation', 'vision', 'innovation'],
      shadowAspect: 'Mükemmeliyetçilik',
      lightAspect: 'Saf yaratıcılık',
    ),

    DreamSymbolData(
      symbol: 'explorer',
      symbolTr: 'Kaşif',
      emoji: '🧭',
      category: SymbolCategory.insan,
      universalMeanings: [
        'Keşif',
        'Macera',
        'Özgürlük',
        'Bilinmeyene yolculuk',
        'Merak',
        'Bağımsızlık',
      ],
      emotionVariants: {
        EmotionalTone.heyecan: 'Keşif heyecanı',
        EmotionalTone.korku: 'Kaybolma',
        EmotionalTone.merak: 'Ötede ne var?',
        EmotionalTone.huzur: 'Özgürlük hissi',
      },
      archetypes: ['Odysseus', 'Marco Polo', 'Gezgin'],
      relatedSymbols: ['journey', 'discovery', 'freedom', 'adventure'],
      shadowAspect: 'Kaçış, köksüzlük',
      lightAspect: 'Gerçek keşif',
    ),
  ];
}
