/// MEGA Dream Symbols Database Part 2 - 500+ Sembol
/// Hayvanlar, Insanlar, Bedensel, Nesneler
library;

import '../models/dream_interpretation_models.dart';

/// Part 2: Hayvanlar, Insanlar, Beden - 500+ Sembol
class MegaDreamSymbolsPart2 {
  static const List<DreamSymbolData> symbols = [
    // ════════════════════════════════════════════════════════════════════════
    // HAYVANLAR - 150+ Sembol
    // ════════════════════════════════════════════════════════════════════════

    // Evcil Hayvanlar
    DreamSymbolData(
      symbol: 'dog',
      symbolTr: 'Kopek',
      emoji: '🐕',
      category: SymbolCategory.hayvan,
      universalMeanings: [
        'Sadakat ve dostluk',
        'Koruma ve guvenlik',
        'Icguduler',
        'Kosulsuz sevgi',
        'Rehberlik',
        'Sadik yoldas',
      ],
      emotionVariants: {
        EmotionalTone.huzur: 'Guvenilir dost, sadakat',
        EmotionalTone.korku: 'Saldirgan kopek - tehdit',
        EmotionalTone.ozlem: 'Kayip dost',
        EmotionalTone.heyecan: 'Yeni dostluk',
      },
      archetypes: ['Dost', 'Koruyucu', 'Sadik'],
      relatedSymbols: ['loyalty', 'protection', 'friend', 'wolf'],
      shadowAspect: 'Saldirganlik, kontrolsuz icgudu',
      lightAspect: 'Sadakat, dostluk, koruma',
    ),

    DreamSymbolData(
      symbol: 'cat',
      symbolTr: 'Kedi',
      emoji: '🐈',
      category: SymbolCategory.hayvan,
      universalMeanings: [
        'Bagimsizlik',
        'Gizem ve sezgi',
        'Feminen guc',
        'Dokuz canlı - yenilenme',
        'Karanlik gorme',
        'Zarif guc',
      ],
      emotionVariants: {
        EmotionalTone.huzur: 'Bagimsiz huzur',
        EmotionalTone.merak: 'Gizemli mesaj',
        EmotionalTone.korku: 'Kara kedi - ugursuzluk inanisi',
        EmotionalTone.heyecan: 'Sezgisel uyanis',
      },
      archetypes: ['Feminen', 'Gizem', 'Bagimsiz'],
      relatedSymbols: ['night', 'mystery', 'independence', 'witch'],
      shadowAspect: 'Soguk bagimsizlik, kapris',
      lightAspect: 'Sezgi, bagimsizlik, zarfet',
    ),

    DreamSymbolData(
      symbol: 'horse',
      symbolTr: 'At',
      emoji: '🐴',
      category: SymbolCategory.hayvan,
      universalMeanings: [
        'Guc ve ozgurluk',
        'Nobil enerji',
        'Cinsellik ve tutku',
        'Yolculuk ve ilerleme',
        'Vahsi doga',
        'Zafer',
      ],
      emotionVariants: {
        EmotionalTone.heyecan: 'Guc ve ozgurluk',
        EmotionalTone.huzur: 'Kontrollü guc',
        EmotionalTone.korku: 'Serbest at - kontrolsuz enerji',
        EmotionalTone.ozlem: 'Ozgurluge kosmak',
      },
      archetypes: ['Guc', 'Ozgurluk', 'Asalet'],
      relatedSymbols: ['riding', 'speed', 'freedom', 'wild'],
      shadowAspect: 'Kontrolsuz tutku, vahsi enerji',
      lightAspect: 'Guc, ozgurluk, asalet',
    ),

    DreamSymbolData(
      symbol: 'cow',
      symbolTr: 'Inek',
      emoji: '🐄',
      category: SymbolCategory.hayvan,
      universalMeanings: [
        'Beslenme ve bolluk',
        'Analik',
        'Huzur ve sabir',
        'Kutsal (Hindu)',
        'Verimlilik',
        'Topraklanma',
      ],
      emotionVariants: {
        EmotionalTone.huzur: 'Besleyici huzur',
        EmotionalTone.ozlem: 'Analik enerjisi',
        EmotionalTone.merak: 'Bolluk kapisi',
        EmotionalTone.donukluk: 'Hareketsizlik',
      },
      archetypes: ['Ana', 'Bereket', 'Sabir'],
      relatedSymbols: ['milk', 'farm', 'abundance', 'mother'],
      shadowAspect: 'Pasiflik, hareketsizlik',
      lightAspect: 'Bereket, beslenme, sabir',
    ),

    DreamSymbolData(
      symbol: 'pig',
      symbolTr: 'Domuz',
      emoji: '🐷',
      category: SymbolCategory.hayvan,
      universalMeanings: [
        'Bolluk ve sans',
        'Zeka',
        'Oburluk (gölge)',
        'Topraklanma',
        'Bereket',
        'Pratiklik',
      ],
      emotionVariants: {
        EmotionalTone.huzur: 'Bolluk ve sans',
        EmotionalTone.sucluluk: 'Asirilik, oburluk',
        EmotionalTone.merak: 'Gizli zeka',
        EmotionalTone.heyecan: 'Bereket haberi',
      },
      archetypes: ['Bereket', 'Zeka', 'Toprak'],
      relatedSymbols: ['farm', 'abundance', 'luck', 'greed'],
      shadowAspect: 'Oburluk, acgozluluk',
      lightAspect: 'Sans, bolluk, zeka',
    ),

    // Vahsi Hayvanlar
    DreamSymbolData(
      symbol: 'lion',
      symbolTr: 'Aslan',
      emoji: '🦁',
      category: SymbolCategory.hayvan,
      universalMeanings: [
        'Krallik ve guc',
        'Cesaret',
        'Gurur ve onur',
        'Liderlik',
        'Gunes enerjisi',
        'Koruyucu guc',
      ],
      emotionVariants: {
        EmotionalTone.heyecan: 'Ic aslanini uyandir',
        EmotionalTone.korku: 'Tehditkar guc',
        EmotionalTone.huzur: 'Koruyucu aslan',
        EmotionalTone.ozlem: 'Guc ve cesaret',
      },
      archetypes: ['Kral', 'Guc', 'Cesaret'],
      relatedSymbols: ['crown', 'sun', 'pride', 'courage'],
      shadowAspect: 'Tiranlık, egemen ofke',
      lightAspect: 'Guc, cesaret, liderlik',
    ),

    DreamSymbolData(
      symbol: 'tiger',
      symbolTr: 'Kaplan',
      emoji: '🐅',
      category: SymbolCategory.hayvan,
      universalMeanings: [
        'Ham guc',
        'Tutku ve saldirganlik',
        'Bagimsiz avcı',
        'Guzellik ve tehlike',
        'Kontrollü vahsilik',
        'Korkusuzluk',
      ],
      emotionVariants: {
        EmotionalTone.korku: 'Tehlikeli tutku',
        EmotionalTone.heyecan: 'Vahsi guc',
        EmotionalTone.huzur: 'Evcil kaplan - kontrollü guc',
        EmotionalTone.merak: 'Gizli yirticilik',
      },
      archetypes: ['Avcı', 'Tutku', 'Guc'],
      relatedSymbols: ['jungle', 'stripes', 'hunt', 'power'],
      shadowAspect: 'Kontrolsuz ofke, tehlike',
      lightAspect: 'Korkusuzluk, guc, guzellik',
    ),

    DreamSymbolData(
      symbol: 'wolf',
      symbolTr: 'Kurt',
      emoji: '🐺',
      category: SymbolCategory.hayvan,
      universalMeanings: [
        'Suru ve aile',
        'Sadakat',
        'Vahsi ozgurluk',
        'Ogretmen (Kurt Ogretici)',
        'Ayisik ve gece',
        'Icgudulerin sesi',
      ],
      emotionVariants: {
        EmotionalTone.korku: 'Saldirgan tehdit',
        EmotionalTone.huzur: 'Suruyle birlik',
        EmotionalTone.ozlem: 'Vahsi ozgurluk',
        EmotionalTone.merak: 'Kurtun mesaji',
      },
      archetypes: ['Ogretmen', 'Aile', 'Vahsi'],
      relatedSymbols: ['moon', 'pack', 'howl', 'wilderness'],
      shadowAspect: 'Yirtici tehdit, yalniz kurt',
      lightAspect: 'Sadakat, ozgurluk, rehberlik',
    ),

    DreamSymbolData(
      symbol: 'bear',
      symbolTr: 'Ayi',
      emoji: '🐻',
      category: SymbolCategory.hayvan,
      universalMeanings: [
        'Guc ve koruma',
        'Analik (disi ayi)',
        'Kis uykusu - ic yolculuk',
        'Saman bilgeligi',
        'Vahsi doga',
        'Topraklanma',
      ],
      emotionVariants: {
        EmotionalTone.korku: 'Tehlikeli guc',
        EmotionalTone.huzur: 'Koruyucu guc',
        EmotionalTone.donukluk: 'Kis uykusu, icsel cekilme',
        EmotionalTone.merak: 'Magaradaki sirlar',
      },
      archetypes: ['Koruyucu', 'Saman', 'Guc'],
      relatedSymbols: ['cave', 'hibernation', 'mother', 'forest'],
      shadowAspect: 'Ofkeli saldiri, tehlike',
      lightAspect: 'Koruma, guc, ic bilgelik',
    ),

    DreamSymbolData(
      symbol: 'fox',
      symbolTr: 'Tilki',
      emoji: '🦊',
      category: SymbolCategory.hayvan,
      universalMeanings: [
        'Kurnazlik ve zeka',
        'Uyum saglama',
        'Aldaticilik (gölge)',
        'Ceviklik',
        'Gizem',
        'Cinlik ve oyunbazlik',
      ],
      emotionVariants: {
        EmotionalTone.merak: 'Akilli strateji',
        EmotionalTone.korku: 'Aldatilma',
        EmotionalTone.heyecan: 'Zeki cozumler',
        EmotionalTone.huzur: 'Uyumlu zeka',
      },
      archetypes: ['Kurnaz', 'Uyumlu', 'Oyuncu'],
      relatedSymbols: ['cunning', 'forest', 'trickster', 'red'],
      shadowAspect: 'Aldaticilik, duzenbazlik',
      lightAspect: 'Zeka, uyum, ceviklik',
    ),

    DreamSymbolData(
      symbol: 'deer',
      symbolTr: 'Geyik',
      emoji: '🦌',
      category: SymbolCategory.hayvan,
      universalMeanings: [
        'Zarafet ve guzellik',
        'Masumiyet',
        'Hassasiyet ve farkindalik',
        'Dogayla baglanti',
        'Yenilenme (boynuz)',
        'Ruhani rehber',
      ],
      emotionVariants: {
        EmotionalTone.huzur: 'Zarafet ve huzur',
        EmotionalTone.ozlem: 'Masumiyete donus',
        EmotionalTone.korku: 'Kacan geyik - kacirilan firsat',
        EmotionalTone.merak: 'Ormanin rehberi',
      },
      archetypes: ['Zarafet', 'Masumiyet', 'Rehber'],
      relatedSymbols: ['forest', 'antlers', 'grace', 'spirit'],
      shadowAspect: 'Kirilganlik, kacis',
      lightAspect: 'Zarafet, masumiyet, rehberlik',
    ),

    DreamSymbolData(
      symbol: 'rabbit',
      symbolTr: 'Tavsan',
      emoji: '🐰',
      category: SymbolCategory.hayvan,
      universalMeanings: [
        'Bereket ve dogurganlik',
        'Sans',
        'Korkaklik veya dikkat',
        'Ay baglantisi',
        'Hiz',
        'Yaraticilik',
      ],
      emotionVariants: {
        EmotionalTone.huzur: 'Sans ve bereket',
        EmotionalTone.korku: 'Kacis modunda',
        EmotionalTone.heyecan: 'Yaratici enerji',
        EmotionalTone.merak: 'Tavsan deliginde ne var?',
      },
      archetypes: ['Bereket', 'Sans', 'Ay'],
      relatedSymbols: ['moon', 'fertility', 'luck', 'speed'],
      shadowAspect: 'Korkaklik, kacis',
      lightAspect: 'Bereket, sans, yaraticilik',
    ),

    DreamSymbolData(
      symbol: 'mouse',
      symbolTr: 'Fare',
      emoji: '🐭',
      category: SymbolCategory.hayvan,
      universalMeanings: [
        'Detaylara dikkat',
        'Kucuk ama onemli',
        'Gizlilik',
        'Kuculme (gölge)',
        'Kaynaklari biriktirme',
        'Korunma',
      ],
      emotionVariants: {
        EmotionalTone.merak: 'Kucuk detaylar',
        EmotionalTone.korku: 'Kemirilme, zarar',
        EmotionalTone.huzur: 'Kucuk mutluluklar',
        EmotionalTone.donukluk: 'Kendini kucumseme',
      },
      archetypes: ['Detay', 'Gizlilik', 'Kucuk'],
      relatedSymbols: ['small', 'hidden', 'cheese', 'fear'],
      shadowAspect: 'Kuculme, onemsizlik',
      lightAspect: 'Detay, kaynak yonetimi',
    ),

    DreamSymbolData(
      symbol: 'rat',
      symbolTr: 'Sican',
      emoji: '🐀',
      category: SymbolCategory.hayvan,
      universalMeanings: [
        'Hayatta kalma',
        'Uyum saglama',
        'Kirlilik veya hastalik (gölge)',
        'Zeka',
        'Biriktirme',
        'Gizli aktivite',
      ],
      emotionVariants: {
        EmotionalTone.korku: 'Hastalik, tehlike',
        EmotionalTone.merak: 'Hayatta kalma stratejileri',
        EmotionalTone.sucluluk: 'Gizli eylemler',
        EmotionalTone.heyecan: 'Zeki cozumler',
      },
      archetypes: ['Hayatta Kalma', 'Uyum', 'Gizli'],
      relatedSymbols: ['survival', 'disease', 'hidden', 'cunning'],
      shadowAspect: 'Hastalik, hainet',
      lightAspect: 'Uyum, zeka, hayatta kalma',
    ),

    DreamSymbolData(
      symbol: 'elephant',
      symbolTr: 'Fil',
      emoji: '🐘',
      category: SymbolCategory.hayvan,
      universalMeanings: [
        'Hafiza ve bilgelik',
        'Guc ve dayaniklilik',
        'Aile baglari',
        'Sans (Ganesha)',
        'Sabir',
        'Kutsal',
      ],
      emotionVariants: {
        EmotionalTone.huzur: 'Bilge guc',
        EmotionalTone.ozlem: 'Aile ve kokler',
        EmotionalTone.merak: 'Kadim bilgelik',
        EmotionalTone.korku: 'Ezici buyukluk',
      },
      archetypes: ['Bilge', 'Aile', 'Guc'],
      relatedSymbols: ['memory', 'wisdom', 'family', 'sacred'],
      shadowAspect: 'Unutulamayan aci, agirlik',
      lightAspect: 'Bilgelik, guc, aile',
    ),

    DreamSymbolData(
      symbol: 'monkey',
      symbolTr: 'Maymun',
      emoji: '🐒',
      category: SymbolCategory.hayvan,
      universalMeanings: [
        'Oyunculuk ve nese',
        'Taklit ve ogrenme',
        'Zeka',
        'Kaos (maymun zihni)',
        'Ceviklik',
        'Ilkel doga',
      ],
      emotionVariants: {
        EmotionalTone.heyecan: 'Oyuncu enerji',
        EmotionalTone.merak: 'Kesif ve ogrenme',
        EmotionalTone.korku: 'Kontrolsuz kaos',
        EmotionalTone.huzur: 'Oyunculuk',
      },
      archetypes: ['Oyuncu', 'Taklit', 'Kaos'],
      relatedSymbols: ['play', 'imitation', 'jungle', 'chaos'],
      shadowAspect: 'Kaotik zihin, taklit',
      lightAspect: 'Oyun, ogrenme, ceviklik',
    ),

    DreamSymbolData(
      symbol: 'snake',
      symbolTr: 'Yilan',
      emoji: '🐍',
      category: SymbolCategory.hayvan,
      universalMeanings: [
        'Donusum ve yenilenme',
        'Kundalini enerjisi',
        'Sifa (Asclepius)',
        'Bilgelik veya aldatma',
        'Ilkel korku',
        'Cinsellik',
      ],
      emotionVariants: {
        EmotionalTone.korku: 'Ilkel tehlike',
        EmotionalTone.merak: 'Donusum sirlari',
        EmotionalTone.huzur: 'Sifa yilani',
        EmotionalTone.heyecan: 'Enerji uyanisi',
      },
      archetypes: ['Donusum', 'Sifa', 'Bilgelik'],
      relatedSymbols: ['transformation', 'healing', 'wisdom', 'danger'],
      shadowAspect: 'Aldatma, tehlike, ihanet',
      lightAspect: 'Donusum, sifa, bilgelik',
    ),

    DreamSymbolData(
      symbol: 'spider',
      symbolTr: 'Orumcek',
      emoji: '🕷️',
      category: SymbolCategory.hayvan,
      universalMeanings: [
        'Yaraticilik (ag orgusu)',
        'Kader dokumacisi',
        'Feminin guc',
        'Tuzak ve manipulasyon (gölge)',
        'Sabir',
        'Baglanticilik',
      ],
      emotionVariants: {
        EmotionalTone.korku: 'Tuzak, fobi',
        EmotionalTone.merak: 'Yaratici surecler',
        EmotionalTone.huzur: 'Sabir ve strateji',
        EmotionalTone.donukluk: 'Aga yakalanma',
      },
      archetypes: ['Yaratici', 'Kader', 'Dokumaci'],
      relatedSymbols: ['web', 'creation', 'trap', 'patience'],
      shadowAspect: 'Tuzak, manipulasyon',
      lightAspect: 'Yaraticilik, sabir, baglanti',
    ),

    DreamSymbolData(
      symbol: 'bee',
      symbolTr: 'Ari',
      emoji: '🐝',
      category: SymbolCategory.hayvan,
      universalMeanings: [
        'Caliskanlik',
        'Topluluk ve isbirligi',
        'Tatlilik (bal)',
        'Uretkenlik',
        'Dogayla uyum',
        'Ruhun ölümsuzlugu',
      ],
      emotionVariants: {
        EmotionalTone.huzur: 'Verimli calisma',
        EmotionalTone.heyecan: 'Uretkenlik',
        EmotionalTone.korku: 'Arisokulmasi - acı',
        EmotionalTone.merak: 'Kovanin sirlari',
      },
      archetypes: ['Iscı', 'Topluluk', 'Uretken'],
      relatedSymbols: ['honey', 'hive', 'flower', 'work'],
      shadowAspect: 'Isbirlakcilık, surü',
      lightAspect: 'Caliskanlik, uretkenlik, topluluk',
    ),

    DreamSymbolData(
      symbol: 'ant',
      symbolTr: 'Karinca',
      emoji: '🐜',
      category: SymbolCategory.hayvan,
      universalMeanings: [
        'Sabir ve caliskanlik',
        'Topluluk gucu',
        'Kucuk adimlarla ilerleme',
        'Organizasyon',
        'Dayaniklilik',
        'Hazirlik',
      ],
      emotionVariants: {
        EmotionalTone.huzur: 'Sistemli calisma',
        EmotionalTone.merak: 'Koloni zekasi',
        EmotionalTone.donukluk: 'Tekrar eden is',
        EmotionalTone.heyecan: 'Kolektif guc',
      },
      archetypes: ['Isci', 'Sabir', 'Kolektif'],
      relatedSymbols: ['work', 'patience', 'colony', 'small'],
      shadowAspect: 'Bireyselliği kaybi, monotonluk',
      lightAspect: 'Sabir, dayaniklilik, organizasyon',
    ),

    DreamSymbolData(
      symbol: 'frog',
      symbolTr: 'Kurbaga',
      emoji: '🐸',
      category: SymbolCategory.hayvan,
      universalMeanings: [
        'Donusum (iribastan kurbagaya)',
        'Bereket',
        'Temizlik',
        'Gecis (su-kara)',
        'Sans',
        'Yagmur cagrisi',
      ],
      emotionVariants: {
        EmotionalTone.huzur: 'Donusum huzuru',
        EmotionalTone.heyecan: 'Metamorfoz',
        EmotionalTone.merak: 'Prens mi kurbaga mi?',
        EmotionalTone.korku: 'Tiksinme',
      },
      archetypes: ['Donusum', 'Gecis', 'Bereket'],
      relatedSymbols: ['transformation', 'water', 'rain', 'prince'],
      shadowAspect: 'Tiksinme, donusememe',
      lightAspect: 'Donusum, bereket, temizlik',
    ),

    DreamSymbolData(
      symbol: 'turtle',
      symbolTr: 'Kaplumbaga',
      emoji: '🐢',
      category: SymbolCategory.hayvan,
      universalMeanings: [
        'Sabir ve yavaslik',
        'Koruma (kabuk)',
        'Bilgelik',
        'Uzun omur',
        'Topraklanma',
        'Evren tasıyıcısı (mitoloji)',
      ],
      emotionVariants: {
        EmotionalTone.huzur: 'Yavas ama kararlı',
        EmotionalTone.donukluk: 'Kabuguna cekilme',
        EmotionalTone.merak: 'Kadim bilgelik',
        EmotionalTone.ozlem: 'Korunma ihtiyaci',
      },
      archetypes: ['Bilge', 'Koruma', 'Sabir'],
      relatedSymbols: ['slow', 'shell', 'wisdom', 'longevity'],
      shadowAspect: 'Cekilme, kacinma',
      lightAspect: 'Sabir, koruma, bilgelik',
    ),

    DreamSymbolData(
      symbol: 'crocodile',
      symbolTr: 'Timsah',
      emoji: '🐊',
      category: SymbolCategory.hayvan,
      universalMeanings: [
        'Ilkel tehlike',
        'Gizli tehdit',
        'Guclu icgudu',
        'Hayatta kalma',
        'Karanlık sularda',
        'Sabir (avci)',
      ],
      emotionVariants: {
        EmotionalTone.korku: 'Gizli tehdit',
        EmotionalTone.merak: 'Ilkel guc',
        EmotionalTone.donukluk: 'Bekleyen avci',
        EmotionalTone.heyecan: 'Tehlikeyle yuzlesme',
      },
      archetypes: ['Avcı', 'Tehlike', 'Ilkel'],
      relatedSymbols: ['water', 'danger', 'hidden', 'survival'],
      shadowAspect: 'Gizli tehdit, yikici guc',
      lightAspect: 'Guc, hayatta kalma, sabir',
    ),

    DreamSymbolData(
      symbol: 'scorpion',
      symbolTr: 'Akrep',
      emoji: '🦂',
      category: SymbolCategory.hayvan,
      universalMeanings: [
        'Tehlike ve zehir',
        'Donusum (Akrep burcu)',
        'Kendini koruma',
        'Gizli guc',
        'Olum ve yeniden dogus',
        'Tutku',
      ],
      emotionVariants: {
        EmotionalTone.korku: 'Oldurücu tehdit',
        EmotionalTone.merak: 'Karanlik güc',
        EmotionalTone.heyecan: 'Donusum enerjisi',
        EmotionalTone.donukluk: 'Uyusmus tehlike',
      },
      archetypes: ['Donusum', 'Olum', 'Guc'],
      relatedSymbols: ['poison', 'death', 'rebirth', 'passion'],
      shadowAspect: 'Zehirli saldirı, intikam',
      lightAspect: 'Donusum, koruma, guc',
    ),

    // Kuslar (devam)
    DreamSymbolData(
      symbol: 'swan',
      symbolTr: 'Kugu',
      emoji: '🦢',
      category: SymbolCategory.hayvan,
      universalMeanings: [
        'Zarafet ve guzellik',
        'Donusum (cirkin ordek)',
        'Sadakat (cift)',
        'Saflik',
        'Son sarki (mitoloji)',
        'Ruhun yolculugu',
      ],
      emotionVariants: {
        EmotionalTone.huzur: 'Zarafet ve guzellik',
        EmotionalTone.ozlem: 'Donusum arzusu',
        EmotionalTone.merak: 'Gizli guzellik',
        EmotionalTone.heyecan: 'Metamorfoz',
      },
      archetypes: ['Zarafet', 'Donusum', 'Guzellik'],
      relatedSymbols: ['transformation', 'beauty', 'lake', 'grace'],
      shadowAspect: 'Gurur, soguk guzellik',
      lightAspect: 'Zarafet, donusum, sadakat',
    ),

    DreamSymbolData(
      symbol: 'peacock',
      symbolTr: 'Tavuskusu',
      emoji: '🦚',
      category: SymbolCategory.hayvan,
      universalMeanings: [
        'Gurur ve gosteris',
        'Guzellik',
        'Yenilenme',
        'Kutsal (Hindu)',
        'Gosteris',
        'Ic guzelligin disavurumu',
      ],
      emotionVariants: {
        EmotionalTone.heyecan: 'Gösterişli kendini ifade',
        EmotionalTone.huzur: 'Güzellik takdiri',
        EmotionalTone.sucluluk: 'Aşırı gurur',
        EmotionalTone.merak: 'Neden bu kadar güzel?',
      },
      archetypes: ['Gurur', 'Guzellik', 'Gösteris'],
      relatedSymbols: ['feathers', 'eyes', 'beauty', 'pride'],
      shadowAspect: 'Kibir, yüzeysellik',
      lightAspect: 'Guzellik, özgüven, ifade',
    ),

    DreamSymbolData(
      symbol: 'raven',
      symbolTr: 'Kuzgun',
      emoji: '🐦‍⬛',
      category: SymbolCategory.hayvan,
      universalMeanings: [
        'Gizem ve sihir',
        'Olumun habercisi',
        'Donusum',
        'Bilgelik',
        'Mesajci',
        'Karanlik bilgi',
      ],
      emotionVariants: {
        EmotionalTone.korku: 'Ugursuz haber',
        EmotionalTone.merak: 'Gizemli mesaj',
        EmotionalTone.huzur: 'Bilge rehber',
        EmotionalTone.heyecan: 'Sihirli donus',
      },
      archetypes: ['Haberci', 'Sihir', 'Bilge'],
      relatedSymbols: ['death', 'magic', 'wisdom', 'black'],
      shadowAspect: 'Olum, ugursuzluk',
      lightAspect: 'Bilgelik, donusum, sihir',
    ),

    DreamSymbolData(
      symbol: 'dove',
      symbolTr: 'Guvercin',
      emoji: '🕊️',
      category: SymbolCategory.hayvan,
      universalMeanings: [
        'Baris ve huzur',
        'Kutsal Ruh',
        'Masumiyet',
        'Ask',
        'Umut',
        'Mesaj',
      ],
      emotionVariants: {
        EmotionalTone.huzur: 'Baris ve umut',
        EmotionalTone.heyecan: 'Kutsal mesaj',
        EmotionalTone.ozlem: 'Baris arayisi',
        EmotionalTone.merak: 'Nereden geliyor?',
      },
      archetypes: ['Baris', 'Kutsal', 'Umut'],
      relatedSymbols: ['peace', 'love', 'message', 'white'],
      shadowAspect: 'Naiflik, savunmasizlik',
      lightAspect: 'Baris, umut, kutsal',
    ),

    DreamSymbolData(
      symbol: 'parrot',
      symbolTr: 'Papagan',
      emoji: '🦜',
      category: SymbolCategory.hayvan,
      universalMeanings: [
        'Iletisim',
        'Taklit',
        'Renklilik',
        'Sosyallik',
        'Tekrar',
        'Egzotik',
      ],
      emotionVariants: {
        EmotionalTone.heyecan: 'Canli iletisim',
        EmotionalTone.merak: 'Ne söylüyor?',
        EmotionalTone.huzur: 'Renkli ifade',
        EmotionalTone.donukluk: 'Tekrar, özgünlük yok',
      },
      archetypes: ['Iletisim', 'Taklit', 'Renk'],
      relatedSymbols: ['speech', 'colors', 'mimicry', 'tropical'],
      shadowAspect: 'Bos tekrar, anlamsiz laf',
      lightAspect: 'Iletisim, canlilik, ifade',
    ),

    // ════════════════════════════════════════════════════════════════════════
    // INSANLAR VE ARKETIPLER - 100+ Sembol
    // ════════════════════════════════════════════════════════════════════════
    DreamSymbolData(
      symbol: 'mother',
      symbolTr: 'Anne',
      emoji: '👩',
      category: SymbolCategory.insan,
      universalMeanings: [
        'Beslenme ve bakim',
        'Kaynak',
        'Kosulsuz sevgi',
        'Koruma',
        'Ic ana',
        'Dogum ve yasam',
      ],
      emotionVariants: {
        EmotionalTone.huzur: 'Besleyici sevgi',
        EmotionalTone.ozlem: 'Analiga ozlem',
        EmotionalTone.korku: 'Bogcu ana',
        EmotionalTone.sucluluk: 'Anne iliskisi sorunlari',
      },
      archetypes: ['Ana', 'Besleyici', 'Koruyucu'],
      relatedSymbols: ['nurture', 'home', 'birth', 'love'],
      shadowAspect: 'Bogcu, kontrolcu ana',
      lightAspect: 'Sevgi, bakim, kaynak',
    ),

    DreamSymbolData(
      symbol: 'father',
      symbolTr: 'Baba',
      emoji: '👨',
      category: SymbolCategory.insan,
      universalMeanings: [
        'Otorite ve yapi',
        'Koruma',
        'Rehberlik',
        'Kurallar',
        'Guc',
        'Onay ve kabul',
      ],
      emotionVariants: {
        EmotionalTone.huzur: 'Koruyucu guc',
        EmotionalTone.korku: 'Otoriter baba',
        EmotionalTone.ozlem: 'Baba figuru',
        EmotionalTone.sucluluk: 'Baba beklentileri',
      },
      archetypes: ['Baba', 'Otorite', 'Koruyucu'],
      relatedSymbols: ['authority', 'protection', 'guidance', 'rules'],
      shadowAspect: 'Zorba, mesafeli baba',
      lightAspect: 'Koruma, rehberlik, guc',
    ),

    DreamSymbolData(
      symbol: 'child',
      symbolTr: 'Cocuk',
      emoji: '👶',
      category: SymbolCategory.insan,
      universalMeanings: [
        'Ic cocuk',
        'Masumiyet',
        'Yeni baslangic',
        'Yaraticilik',
        'Bagimsizlik',
        'Potansiyel',
      ],
      emotionVariants: {
        EmotionalTone.huzur: 'Masum mutluluk',
        EmotionalTone.ozlem: 'Kayip masumiyet',
        EmotionalTone.korku: 'Korunmasiz cocuk',
        EmotionalTone.heyecan: 'Yeni potansiyel',
      },
      archetypes: ['Ic Cocuk', 'Masumiyet', 'Baslangic'],
      relatedSymbols: ['innocence', 'play', 'beginning', 'potential'],
      shadowAspect: 'Yarali cocuk, olgunlasamama',
      lightAspect: 'Masumiyet, yaraticilik, nese',
    ),

    DreamSymbolData(
      symbol: 'baby',
      symbolTr: 'Bebek',
      emoji: '👶',
      category: SymbolCategory.insan,
      universalMeanings: [
        'Yeni baslangic',
        'Savunmasizlik',
        'Potansiyel',
        'Bakim ihtiyaci',
        'Ic yenilenme',
        'Proje veya fikir',
      ],
      emotionVariants: {
        EmotionalTone.huzur: 'Yeni yasam, umut',
        EmotionalTone.korku: 'Sorumluluk, yetersizlik',
        EmotionalTone.heyecan: 'Yeni baslangic',
        EmotionalTone.ozlem: 'Cocuk arzusu',
      },
      archetypes: ['Yenilik', 'Potansiyel', 'Savunmasiz'],
      relatedSymbols: ['birth', 'new', 'innocent', 'care'],
      shadowAspect: 'Bakim yukleri, kaygi',
      lightAspect: 'Yenilik, umut, potansiyel',
    ),

    DreamSymbolData(
      symbol: 'old_man',
      symbolTr: 'Yasli Adam / Bilge',
      emoji: '👴',
      category: SymbolCategory.insan,
      universalMeanings: [
        'Bilgelik',
        'Deneyim',
        'Rehberlik',
        'Ust Benlik',
        'Atalar',
        'Zaman',
      ],
      emotionVariants: {
        EmotionalTone.huzur: 'Bilge rehberlik',
        EmotionalTone.merak: 'Ogrenilecek dersler',
        EmotionalTone.korku: 'Yaslanma, olum',
        EmotionalTone.ozlem: 'Bilgelik arayisi',
      },
      archetypes: ['Bilge', 'Rehber', 'Ata'],
      relatedSymbols: ['wisdom', 'time', 'guidance', 'experience'],
      shadowAspect: 'Katı gelenek, eskimislik',
      lightAspect: 'Bilgelik, rehberlik, deneyim',
    ),

    DreamSymbolData(
      symbol: 'old_woman',
      symbolTr: 'Yasli Kadin / Bilge Kadin',
      emoji: '👵',
      category: SymbolCategory.insan,
      universalMeanings: [
        'Kadim feminen bilgelik',
        'Sezgi',
        'Cadi arketipi',
        'Yasam dongusu',
        'Anneanne',
        'Sifa',
      ],
      emotionVariants: {
        EmotionalTone.huzur: 'Bilge kadin rehberligi',
        EmotionalTone.merak: 'Kadim sirlar',
        EmotionalTone.korku: 'Cadi korkusu',
        EmotionalTone.ozlem: 'Feminen bilgelik',
      },
      archetypes: ['Cadi', 'Bilge Kadin', 'Ata Ana'],
      relatedSymbols: ['wisdom', 'intuition', 'healing', 'cycles'],
      shadowAspect: 'Korkunc cadi, kiskanclik',
      lightAspect: 'Sifa, sezgi, bilgelik',
    ),

    DreamSymbolData(
      symbol: 'stranger',
      symbolTr: 'Yabanci',
      emoji: '🧑',
      category: SymbolCategory.insan,
      universalMeanings: [
        'Bilinmeyen kendlik',
        'Golge tarafi',
        'Kesfedilmemis potansiyel',
        'Tehdit veya firsat',
        'Projeksiyon',
        'Gelecekteki ben',
      ],
      emotionVariants: {
        EmotionalTone.korku: 'Bilinmeyen tehdit',
        EmotionalTone.merak: 'Kim bu?',
        EmotionalTone.heyecan: 'Yeni olasıilik',
        EmotionalTone.huzur: 'Tanıdık yabancı',
      },
      archetypes: ['Golge', 'Bilinmeyen', 'Olasilik'],
      relatedSymbols: ['unknown', 'shadow', 'potential', 'meeting'],
      shadowAspect: 'Tehdit, korku',
      lightAspect: 'Yeni olasıilik, kesif',
    ),

    DreamSymbolData(
      symbol: 'king',
      symbolTr: 'Kral',
      emoji: '👑',
      category: SymbolCategory.insan,
      universalMeanings: [
        'Otorite ve guc',
        'Olgun maskulen',
        'Liderlik',
        'Kontrol',
        'Sorumluluk',
        'Hakimiyet',
      ],
      emotionVariants: {
        EmotionalTone.huzur: 'Ic otoriteyle baglanti',
        EmotionalTone.heyecan: 'Guc ve liderlik',
        EmotionalTone.korku: 'Tiran',
        EmotionalTone.ozlem: 'Guc arayisi',
      },
      archetypes: ['Kral', 'Otorite', 'Lider'],
      relatedSymbols: ['crown', 'throne', 'power', 'authority'],
      shadowAspect: 'Tiran, diktatör',
      lightAspect: 'Adil lider, koruyucu',
    ),

    DreamSymbolData(
      symbol: 'queen',
      symbolTr: 'Kralice',
      emoji: '👸',
      category: SymbolCategory.insan,
      universalMeanings: [
        'Feminen guc',
        'Olgun feminen',
        'Bereket',
        'Sezgi ve bilgelik',
        'Asalet',
        'Ic kralice',
      ],
      emotionVariants: {
        EmotionalTone.huzur: 'Feminen gucle baglanti',
        EmotionalTone.heyecan: 'Zarafet ve guc',
        EmotionalTone.korku: 'Zalim kralice',
        EmotionalTone.ozlem: 'Ic kraliceni bulmak',
      },
      archetypes: ['Kralice', 'Feminin Guc', 'Bereket'],
      relatedSymbols: ['crown', 'throne', 'fertility', 'wisdom'],
      shadowAspect: 'Zalim, manipulatif',
      lightAspect: 'Bilge lider, koruyucu',
    ),

    DreamSymbolData(
      symbol: 'hero',
      symbolTr: 'Kahraman',
      emoji: '🦸',
      category: SymbolCategory.insan,
      universalMeanings: [
        'Cesaret ve guc',
        'Engelleri asma',
        'Ego gelisimi',
        'Mucadele',
        'Kurtarici',
        'Potansiyel benlik',
      ],
      emotionVariants: {
        EmotionalTone.heyecan: 'Ic kahraman uyanisi',
        EmotionalTone.ozlem: 'Kahramanlik arzusu',
        EmotionalTone.huzur: 'Ic güce guven',
        EmotionalTone.korku: 'Basarisizlik korkusu',
      },
      archetypes: ['Kahraman', 'Kurtarici', 'Savasci'],
      relatedSymbols: ['sword', 'battle', 'victory', 'journey'],
      shadowAspect: 'Ego siismesi, kayıp',
      lightAspect: 'Cesaret, guc, zafer',
    ),

    DreamSymbolData(
      symbol: 'villain',
      symbolTr: 'Kotu Adam / Antagonist',
      emoji: '🦹',
      category: SymbolCategory.insan,
      universalMeanings: [
        'Golge tarafi',
        'Ic dusman',
        'Reddedilen parcalar',
        'Korku ve engel',
        'Donusum potansiyeli',
        'Disi dusmanlik',
      ],
      emotionVariants: {
        EmotionalTone.korku: 'Tehdit ve korkular',
        EmotionalTone.merak: 'Golgenin mesaji',
        EmotionalTone.sucluluk: 'Reddedilen kendilik',
        EmotionalTone.heyecan: 'Yuzlesme zamani',
      },
      archetypes: ['Golge', 'Dusman', 'Karanlik'],
      relatedSymbols: ['shadow', 'fear', 'enemy', 'darkness'],
      shadowAspect: 'Reddedilen kendilik',
      lightAspect: 'Entegrasyon potansiyeli',
    ),

    DreamSymbolData(
      symbol: 'teacher',
      symbolTr: 'Ogretmen',
      emoji: '👩‍🏫',
      category: SymbolCategory.insan,
      universalMeanings: [
        'Rehberlik',
        'Bilgi aktarimi',
        'Otorite figuru',
        'Ic rehber',
        'Ders ve ogrenme',
        'Değerlendirme',
      ],
      emotionVariants: {
        EmotionalTone.huzur: 'Guvenilir rehber',
        EmotionalTone.korku: 'Sinav kaygisi',
        EmotionalTone.merak: 'Ogrenilecekler',
        EmotionalTone.ozlem: 'Rehberlik ihtiyaci',
      },
      archetypes: ['Rehber', 'Bilge', 'Otorite'],
      relatedSymbols: ['school', 'lesson', 'exam', 'wisdom'],
      shadowAspect: 'Elestirel, basarici',
      lightAspect: 'Rehberlik, bilgi, gelisim',
    ),

    DreamSymbolData(
      symbol: 'doctor',
      symbolTr: 'Doktor',
      emoji: '👨‍⚕️',
      category: SymbolCategory.insan,
      universalMeanings: [
        'Sifa ve tedavi',
        'Otorite',
        'Teshis',
        'Ic sifaci',
        'Yardim',
        'Saglik endisi',
      ],
      emotionVariants: {
        EmotionalTone.huzur: 'Sifa yolunda',
        EmotionalTone.korku: 'Hastalk kaygisi',
        EmotionalTone.merak: 'Teshis ne?',
        EmotionalTone.ozlem: 'Sifa ihtiyaci',
      },
      archetypes: ['Sifaci', 'Bilge', 'Kurtarici'],
      relatedSymbols: ['healing', 'medicine', 'hospital', 'health'],
      shadowAspect: 'Korkunc haber, hastalik',
      lightAspect: 'Sifa, tedavi, yardim',
    ),

    DreamSymbolData(
      symbol: 'priest',
      symbolTr: 'Din Adamı / Rahip',
      emoji: '🧑‍⚖️',
      category: SymbolCategory.insan,
      universalMeanings: [
        'Spirituel otorite',
        'Aracı (insan-ilahi)',
        'Kutsal',
        'Ahlak ve etik',
        'Itiraf ve bagislanma',
        'Rehberlik',
      ],
      emotionVariants: {
        EmotionalTone.huzur: 'Spirituel rehberlik',
        EmotionalTone.sucluluk: 'Itiraf ihtiyaci',
        EmotionalTone.korku: 'Yargilanma',
        EmotionalTone.merak: 'Ilahi mesaj',
      },
      archetypes: ['Rahip', 'Araci', 'Kutsal'],
      relatedSymbols: ['church', 'confession', 'spiritual', 'sacred'],
      shadowAspect: 'Yargilayici, baskici',
      lightAspect: 'Rehberlik, kutsama, bagis',
    ),

    DreamSymbolData(
      symbol: 'soldier',
      symbolTr: 'Asker',
      emoji: '💂',
      category: SymbolCategory.insan,
      universalMeanings: [
        'Disiplin',
        'Koruma',
        'Itaat',
        'Mucadele',
        'Kurban',
        'Birlik',
      ],
      emotionVariants: {
        EmotionalTone.korku: 'Savas, catisma',
        EmotionalTone.heyecan: 'Mucadele ruhu',
        EmotionalTone.huzur: 'Koruma altinda',
        EmotionalTone.donukluk: 'Mekanik itaat',
      },
      archetypes: ['Savasci', 'Koruyucu', 'Disiplin'],
      relatedSymbols: ['war', 'uniform', 'weapon', 'battle'],
      shadowAspect: 'Kor itaat, siddet',
      lightAspect: 'Koruma, cesaret, disiplin',
    ),

    DreamSymbolData(
      symbol: 'thief',
      symbolTr: 'Hirsiz',
      emoji: '🥷',
      category: SymbolCategory.insan,
      universalMeanings: [
        'Kayip ve alinma',
        'Golge arzuları',
        'Ihlal',
        'Gizli ihtiyaclar',
        'Guvensizlik',
        'Kendi kendinden calmak',
      ],
      emotionVariants: {
        EmotionalTone.korku: 'Kayip, ihlal',
        EmotionalTone.sucluluk: 'Gizli arzular',
        EmotionalTone.merak: 'Ne calindi?',
        EmotionalTone.heyecan: 'Gizli macera',
      },
      archetypes: ['Golge', 'Trickster', 'Ihlal'],
      relatedSymbols: ['stealing', 'loss', 'hidden', 'shadow'],
      shadowAspect: 'Ihlal, haksizlik',
      lightAspect: 'Gizli ihtiyaclarin farkindalgı',
    ),

    // ════════════════════════════════════════════════════════════════════════
    // BEDEN VE BEDENSEL SEMBOLLER - 80+ Sembol
    // ════════════════════════════════════════════════════════════════════════
    DreamSymbolData(
      symbol: 'eye',
      symbolTr: 'Goz',
      emoji: '👁️',
      category: SymbolCategory.soyut,
      universalMeanings: [
        'Gorüs ve algı',
        'Farkindlik',
        'Ruhun penceresi',
        'Ucuncu goz',
        'Izlenme',
        'Icgoru',
      ],
      emotionVariants: {
        EmotionalTone.merak: 'Ne göruyor?',
        EmotionalTone.korku: 'Izlenme, gozetim',
        EmotionalTone.huzur: 'Berrak gorus',
        EmotionalTone.heyecan: 'Yeni farkindlik',
      },
      archetypes: ['Gorus', 'Farkindaik', 'Sezgi'],
      relatedSymbols: ['vision', 'third_eye', 'watching', 'insight'],
      shadowAspect: 'Gozetim, kor nokta',
      lightAspect: 'Icgoru, farkindaik, sezgi',
    ),

    DreamSymbolData(
      symbol: 'hand',
      symbolTr: 'El',
      emoji: '✋',
      category: SymbolCategory.soyut,
      universalMeanings: [
        'Eylem ve yapma',
        'Guc ve kontrol',
        'Dokunma ve baglanti',
        'Yaraticilik',
        'Verme ve alma',
        'Beceri',
      ],
      emotionVariants: {
        EmotionalTone.huzur: 'Yaratici eller',
        EmotionalTone.korku: 'El kaybi, gücsuzluk',
        EmotionalTone.heyecan: 'Eylem zamani',
        EmotionalTone.ozlem: 'Dokunma arzusu',
      },
      archetypes: ['Yaratici', 'Guc', 'Baglanti'],
      relatedSymbols: ['touch', 'creation', 'grip', 'action'],
      shadowAspect: 'Guc kaybi, zarar verme',
      lightAspect: 'Yaratim, baglanti, eylem',
    ),

    DreamSymbolData(
      symbol: 'heart',
      symbolTr: 'Kalp',
      emoji: '❤️',
      category: SymbolCategory.soyut,
      universalMeanings: [
        'Ask ve duygular',
        'Merkez ve oz',
        'Cesaret (cor)',
        'Tutku',
        'Ruhsal kalp',
        'Yasam enerjisi',
      ],
      emotionVariants: {
        EmotionalTone.huzur: 'Kalpten yasama',
        EmotionalTone.ozlem: 'Ask arayisi',
        EmotionalTone.korku: 'Kalp kirikligi',
        EmotionalTone.heyecan: 'Tutku',
      },
      archetypes: ['Ask', 'Merkez', 'Cesaret'],
      relatedSymbols: ['love', 'emotion', 'courage', 'center'],
      shadowAspect: 'Kirik kalp, kalpsizlik',
      lightAspect: 'Ask, cesaret, tutku',
    ),

    DreamSymbolData(
      symbol: 'teeth',
      symbolTr: 'Disler',
      emoji: '🦷',
      category: SymbolCategory.soyut,
      universalMeanings: [
        'Guc ve saldirganlik',
        'Yaslanma korkusu',
        'Ozguven',
        'Ifade ve iletisim',
        'Kayip',
        'Donusum',
      ],
      emotionVariants: {
        EmotionalTone.korku: 'Dis kaybi - guc kaybi',
        EmotionalTone.sucluluk: 'Soylediklerim',
        EmotionalTone.donukluk: 'Kendine guven eksikligi',
        EmotionalTone.merak: 'Donusum sureci',
      },
      archetypes: ['Guc', 'Kayip', 'Ifade'],
      relatedSymbols: ['falling', 'power', 'aging', 'loss'],
      shadowAspect: 'Guc kaybi, yaslanma',
      lightAspect: 'Guc, ifade, donusum',
    ),

    DreamSymbolData(
      symbol: 'hair',
      symbolTr: 'Sac',
      emoji: '💇',
      category: SymbolCategory.soyut,
      universalMeanings: [
        'Guc (Samson)',
        'Kimlik ve imaj',
        'Cinsellik',
        'Dusunce',
        'Ozgurluk veya kisitlama',
        'Yasam enerjisi',
      ],
      emotionVariants: {
        EmotionalTone.korku: 'Sac dokulmesi - guc kaybi',
        EmotionalTone.heyecan: 'Yeni imaj',
        EmotionalTone.huzur: 'Guzel saclar',
        EmotionalTone.ozlem: 'Degisim arzusu',
      },
      archetypes: ['Guc', 'Kimlik', 'Cinsellik'],
      relatedSymbols: ['power', 'identity', 'cutting', 'beauty'],
      shadowAspect: 'Kayip, gucsusluk',
      lightAspect: 'Guc, kimlik, guzellik',
    ),

    DreamSymbolData(
      symbol: 'blood',
      symbolTr: 'Kan',
      emoji: '🩸',
      category: SymbolCategory.soyut,
      universalMeanings: [
        'Yasam enerjisi',
        'Aile baglari',
        'Kurban',
        'Tutku',
        'Yaralanma',
        'Donusum',
      ],
      emotionVariants: {
        EmotionalTone.korku: 'Yaralanma, kayip',
        EmotionalTone.heyecan: 'Tutku ve enerji',
        EmotionalTone.sucluluk: 'Sucluluk ve kurban',
        EmotionalTone.merak: 'Kan baglari',
      },
      archetypes: ['Yasam', 'Kurban', 'Aile'],
      relatedSymbols: ['life', 'family', 'wound', 'passion'],
      shadowAspect: 'Siddet, kayip',
      lightAspect: 'Yasam, tutku, baglanti',
    ),

    DreamSymbolData(
      symbol: 'naked',
      symbolTr: 'Cipkaklik',
      emoji: '🫣',
      category: SymbolCategory.soyut,
      universalMeanings: [
        'Savunmasizlik',
        'Gercek kendilik',
        'Utanc veya ozgurluk',
        'Masumiyet',
        'Açık olma',
        'Gizlerin acilmasi',
      ],
      emotionVariants: {
        EmotionalTone.korku: 'Utanc, if olmak',
        EmotionalTone.huzur: 'Ozgurluk, doğallık',
        EmotionalTone.sucluluk: 'Gizlerin acilmasi',
        EmotionalTone.heyecan: 'Ozgun ifade',
      },
      archetypes: ['Gercek Ben', 'Savunmasiz', 'Ozgur'],
      relatedSymbols: ['shame', 'freedom', 'truth', 'vulnerability'],
      shadowAspect: 'Utanc, savunmasizlik',
      lightAspect: 'Ozgurluk, otantiklik',
    ),

    DreamSymbolData(
      symbol: 'pregnancy',
      symbolTr: 'Hamilelik',
      emoji: '🤰',
      category: SymbolCategory.soyut,
      universalMeanings: [
        'Yeni proje veya fikir',
        'Yaraticilik',
        'Potansiyelin gelisimi',
        'Bekleme sureci',
        'Donusum',
        'Doguma hazirlik',
      ],
      emotionVariants: {
        EmotionalTone.heyecan: 'Yeni baslangic',
        EmotionalTone.korku: 'Sorumluluk, hazir olmama',
        EmotionalTone.huzur: 'Yaratici sure',
        EmotionalTone.merak: 'Ne dogacak?',
      },
      archetypes: ['Yaratim', 'Potansiyel', 'Bekeyis'],
      relatedSymbols: ['birth', 'creation', 'waiting', 'new'],
      shadowAspect: 'Hazir olmama, korku',
      lightAspect: 'Yaraticilik, potansiyel',
    ),

    DreamSymbolData(
      symbol: 'death',
      symbolTr: 'Olum',
      emoji: '💀',
      category: SymbolCategory.soyut,
      universalMeanings: [
        'Donusum ve degisim',
        'Son ve baslangic',
        'Ego olumu',
        'Birakis',
        'Yeniden dogus',
        'Korku ve kabul',
      ],
      emotionVariants: {
        EmotionalTone.korku: 'Varolussal korku',
        EmotionalTone.huzur: 'Kabul ve birakis',
        EmotionalTone.ozlem: 'Dönüsüm arzusu',
        EmotionalTone.donukluk: 'Son, bitis',
      },
      archetypes: ['Donusum', 'Son', 'Yeniden Dogus'],
      relatedSymbols: ['transformation', 'ending', 'rebirth', 'skeleton'],
      shadowAspect: 'Korku, kayip',
      lightAspect: 'Donusum, birakis, yenilenme',
    ),

    DreamSymbolData(
      symbol: 'wound',
      symbolTr: 'Yara',
      emoji: '🩹',
      category: SymbolCategory.soyut,
      universalMeanings: [
        'Duygusal yara',
        'Gecmis travma',
        'Sifa ihtiyaci',
        'Kirilganlik',
        'Aci',
        'Buyume potansiyeli',
      ],
      emotionVariants: {
        EmotionalTone.korku: 'Acı, hasar',
        EmotionalTone.sucluluk: 'Yarattığım yaralar',
        EmotionalTone.ozlem: 'Sifa arayisi',
        EmotionalTone.huzur: 'Iyilesen yara',
      },
      archetypes: ['Yarali Sifaci', 'Travma', 'Sifa'],
      relatedSymbols: ['healing', 'pain', 'scar', 'blood'],
      shadowAspect: 'Acı, travma',
      lightAspect: 'Sifa, büyume, guc',
    ),

    DreamSymbolData(
      symbol: 'running',
      symbolTr: 'Kosmak',
      emoji: '🏃',
      category: SymbolCategory.eylem,
      universalMeanings: [
        'Kacis veya takip',
        'Hedefe kosma',
        'Korku veya motivasyon',
        'Enerji ve hareket',
        'Zaman baskisi',
        'Ozgurluk',
      ],
      emotionVariants: {
        EmotionalTone.korku: 'Kacis, takip edilme',
        EmotionalTone.heyecan: 'Hedefe kosma',
        EmotionalTone.donukluk: 'Kosamama, yavaslik',
        EmotionalTone.huzur: 'Ozgur kosma',
      },
      archetypes: ['Kacis', 'Hedef', 'Enerji'],
      relatedSymbols: ['chase', 'escape', 'speed', 'goal'],
      shadowAspect: 'Kacis, takip, korku',
      lightAspect: 'Motivasyon, enerji, ozgurluk',
    ),

    DreamSymbolData(
      symbol: 'climbing',
      symbolTr: 'Tirmanma',
      emoji: '🧗',
      category: SymbolCategory.eylem,
      universalMeanings: [
        'Ilerleme ve basari',
        'Engelleri asma',
        'Hedeflere ulasma',
        'Caba ve mucadele',
        'Spirituel yukselis',
        'Kariyer',
      ],
      emotionVariants: {
        EmotionalTone.heyecan: 'Yukselis heyecani',
        EmotionalTone.korku: 'Dusme korkusu',
        EmotionalTone.huzur: 'Kararli ilerleme',
        EmotionalTone.donukluk: 'Tirmanamama',
      },
      archetypes: ['Hedef', 'Mucadele', 'Yukselis'],
      relatedSymbols: ['mountain', 'ladder', 'success', 'height'],
      shadowAspect: 'Dusme, basarisizlik',
      lightAspect: 'Basari, gelisim, yukselis',
    ),
  ];
}
