// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
 show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
/// options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
 static FirebaseOptions get currentPlatform {
 if (kIsWeb) {
 return web;
 }
 switch (defaultTargetPlatform) {
 case TargetPlatform.android:
 return android;
 case TargetPlatform.iOS:
 return ios;
 case TargetPlatform.macOS:
 throw UnsupportedError(
 'DefaultFirebaseOptions have not been configured for macos - '
 'you can reconfigure this by running the FlutterFire CLI again.',
 );
 case TargetPlatform.windows:
 throw UnsupportedError(
 'DefaultFirebaseOptions have not been configured for windows - '
 'you can reconfigure this by running the FlutterFire CLI again.',
 );
 case TargetPlatform.linux:
 throw UnsupportedError(
 'DefaultFirebaseOptions have not been configured for linux - '
 'you can reconfigure this by running the FlutterFire CLI again.',
 );
 default:
 throw UnsupportedError(
 'DefaultFirebaseOptions are not supported for this platform.',
 );
 }
 }

 static const FirebaseOptions web = FirebaseOptions(
 apiKey: 'AIzaSyC0s5XbIr-NW4QmxGa0puBty0ZrJLnmCh8',
 appId: '1:115442315544:web:e13c070f57b2353e4a6e6d',
 messagingSenderId: '115442315544',
 projectId: 'celestial-95a95',
 authDomain: 'celestial-95a95.firebaseapp.com',
 storageBucket: 'celestial-95a95.firebasestorage.app',
 measurementId: 'G-JG0CWR2ZG4',
 );

 static const FirebaseOptions android = FirebaseOptions(
 apiKey: 'AIzaSyDQkNN-5NEGtLTa31rK4570eCrzLwgecus',
 appId: '1:115442315544:android:7371a9df5f7708344a6e6d',
 messagingSenderId: '115442315544',
 projectId: 'celestial-95a95',
 storageBucket: 'celestial-95a95.firebasestorage.app',
 );

 static const FirebaseOptions ios = FirebaseOptions(
 apiKey: 'AIzaSyCBbKykiAW3A5LrxKduYJVNSvGQcZaYA_Y',
 appId: '1:115442315544:ios:ab05e3c8875a4ee54a6e6d',
 messagingSenderId: '115442315544',
 projectId: 'celestial-95a95',
 storageBucket: 'celestial-95a95.firebasestorage.app',
 iosBundleId: 'com.umut.astrologyApp',
 );
}
