name: i18n Compliance Check

on:
  pull_request:
    branches: [ main, develop ]
    paths:
      - '**.swift'
      - '**.strings'
      - 'Resources/**'
      - 'scripts/i18n_*.swift'
  push:
    branches: [ main ]

jobs:
  i18n-guard:
    name: i18n Compliance Guard
    runs-on: macos-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable
      
      - name: Run i18n Guard
        run: |
          echo "ðŸ” Running i18n compliance checks..."
          swift scripts/i18n_guard.swift
        continue-on-error: false
      
      - name: Run i18n Sync Check
        run: |
          echo "ðŸŒ Checking localization synchronization..."
          swift scripts/i18n_sync.swift --check
        continue-on-error: false
      
      - name: Run Localization Tests
        run: |
          echo "ðŸ§ª Running automated i18n tests..."
          swift test --filter LocalizationTests
        continue-on-error: false
  
  i18n-report:
    name: Generate i18n Coverage Report
    runs-on: macos-latest
    needs: i18n-guard
    if: always()
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Generate Coverage Report
        run: |
          echo "ðŸ“Š i18n Coverage Report" > i18n_report.txt
          echo "======================" >> i18n_report.txt
          echo "" >> i18n_report.txt
          
          # Count keys per locale
          for locale in en tr; do
            file="Resources/${locale}.lproj/Localizable.strings"
            if [ -f "$file" ]; then
              count=$(grep -c "^\"" "$file" || echo "0")
              echo "${locale}: ${count} keys" >> i18n_report.txt
            fi
          done
          
          cat i18n_report.txt
      
      - name: Upload Report
        uses: actions/upload-artifact@v3
        with:
          name: i18n-coverage-report
          path: i18n_report.txt
          retention-days: 30
